// Code generated by ent, DO NOT EDIT.

package inventory

import (
	"entgo.io/ent/dialect/sql"
	"gitee.com/meinongyihe/travel-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldTenantID, v))
}

// MerchantID applies equality check predicate on the "merchant_id" field. It's identical to MerchantIDEQ.
func MerchantID(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldMerchantID, v))
}

// PackageID applies equality check predicate on the "package_id" field. It's identical to PackageIDEQ.
func PackageID(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldPackageID, v))
}

// ServiceDate applies equality check predicate on the "service_date" field. It's identical to ServiceDateEQ.
func ServiceDate(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldServiceDate, v))
}

// TimeSlot applies equality check predicate on the "time_slot" field. It's identical to TimeSlotEQ.
func TimeSlot(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldTimeSlot, v))
}

// Capacity applies equality check predicate on the "capacity" field. It's identical to CapacityEQ.
func Capacity(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldCapacity, v))
}

// Reserved applies equality check predicate on the "reserved" field. It's identical to ReservedEQ.
func Reserved(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldReserved, v))
}

// UnitPrice applies equality check predicate on the "unit_price" field. It's identical to UnitPriceEQ.
func UnitPrice(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldUnitPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldCurrency, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldStatus, v))
}

// InventoryMode applies equality check predicate on the "inventory_mode" field. It's identical to InventoryModeEQ.
func InventoryMode(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldInventoryMode, v))
}

// TotalCapacity applies equality check predicate on the "total_capacity" field. It's identical to TotalCapacityEQ.
func TotalCapacity(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldTotalCapacity, v))
}

// IsOpen applies equality check predicate on the "is_open" field. It's identical to IsOpenEQ.
func IsOpen(v bool) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldIsOpen, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldTenantID, v))
}

// MerchantIDEQ applies the EQ predicate on the "merchant_id" field.
func MerchantIDEQ(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldMerchantID, v))
}

// MerchantIDNEQ applies the NEQ predicate on the "merchant_id" field.
func MerchantIDNEQ(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldMerchantID, v))
}

// MerchantIDIn applies the In predicate on the "merchant_id" field.
func MerchantIDIn(vs ...int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldMerchantID, vs...))
}

// MerchantIDNotIn applies the NotIn predicate on the "merchant_id" field.
func MerchantIDNotIn(vs ...int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldMerchantID, vs...))
}

// MerchantIDGT applies the GT predicate on the "merchant_id" field.
func MerchantIDGT(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldMerchantID, v))
}

// MerchantIDGTE applies the GTE predicate on the "merchant_id" field.
func MerchantIDGTE(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldMerchantID, v))
}

// MerchantIDLT applies the LT predicate on the "merchant_id" field.
func MerchantIDLT(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldMerchantID, v))
}

// MerchantIDLTE applies the LTE predicate on the "merchant_id" field.
func MerchantIDLTE(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldMerchantID, v))
}

// PackageIDEQ applies the EQ predicate on the "package_id" field.
func PackageIDEQ(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldPackageID, v))
}

// PackageIDNEQ applies the NEQ predicate on the "package_id" field.
func PackageIDNEQ(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldPackageID, v))
}

// PackageIDIn applies the In predicate on the "package_id" field.
func PackageIDIn(vs ...int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldPackageID, vs...))
}

// PackageIDNotIn applies the NotIn predicate on the "package_id" field.
func PackageIDNotIn(vs ...int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldPackageID, vs...))
}

// PackageIDGT applies the GT predicate on the "package_id" field.
func PackageIDGT(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldPackageID, v))
}

// PackageIDGTE applies the GTE predicate on the "package_id" field.
func PackageIDGTE(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldPackageID, v))
}

// PackageIDLT applies the LT predicate on the "package_id" field.
func PackageIDLT(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldPackageID, v))
}

// PackageIDLTE applies the LTE predicate on the "package_id" field.
func PackageIDLTE(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldPackageID, v))
}

// ServiceDateEQ applies the EQ predicate on the "service_date" field.
func ServiceDateEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldServiceDate, v))
}

// ServiceDateNEQ applies the NEQ predicate on the "service_date" field.
func ServiceDateNEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldServiceDate, v))
}

// ServiceDateIn applies the In predicate on the "service_date" field.
func ServiceDateIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldServiceDate, vs...))
}

// ServiceDateNotIn applies the NotIn predicate on the "service_date" field.
func ServiceDateNotIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldServiceDate, vs...))
}

// ServiceDateGT applies the GT predicate on the "service_date" field.
func ServiceDateGT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldServiceDate, v))
}

// ServiceDateGTE applies the GTE predicate on the "service_date" field.
func ServiceDateGTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldServiceDate, v))
}

// ServiceDateLT applies the LT predicate on the "service_date" field.
func ServiceDateLT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldServiceDate, v))
}

// ServiceDateLTE applies the LTE predicate on the "service_date" field.
func ServiceDateLTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldServiceDate, v))
}

// ServiceDateContains applies the Contains predicate on the "service_date" field.
func ServiceDateContains(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContains(FieldServiceDate, v))
}

// ServiceDateHasPrefix applies the HasPrefix predicate on the "service_date" field.
func ServiceDateHasPrefix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasPrefix(FieldServiceDate, v))
}

// ServiceDateHasSuffix applies the HasSuffix predicate on the "service_date" field.
func ServiceDateHasSuffix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasSuffix(FieldServiceDate, v))
}

// ServiceDateEqualFold applies the EqualFold predicate on the "service_date" field.
func ServiceDateEqualFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEqualFold(FieldServiceDate, v))
}

// ServiceDateContainsFold applies the ContainsFold predicate on the "service_date" field.
func ServiceDateContainsFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContainsFold(FieldServiceDate, v))
}

// TimeSlotEQ applies the EQ predicate on the "time_slot" field.
func TimeSlotEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldTimeSlot, v))
}

// TimeSlotNEQ applies the NEQ predicate on the "time_slot" field.
func TimeSlotNEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldTimeSlot, v))
}

// TimeSlotIn applies the In predicate on the "time_slot" field.
func TimeSlotIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldTimeSlot, vs...))
}

// TimeSlotNotIn applies the NotIn predicate on the "time_slot" field.
func TimeSlotNotIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldTimeSlot, vs...))
}

// TimeSlotGT applies the GT predicate on the "time_slot" field.
func TimeSlotGT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldTimeSlot, v))
}

// TimeSlotGTE applies the GTE predicate on the "time_slot" field.
func TimeSlotGTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldTimeSlot, v))
}

// TimeSlotLT applies the LT predicate on the "time_slot" field.
func TimeSlotLT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldTimeSlot, v))
}

// TimeSlotLTE applies the LTE predicate on the "time_slot" field.
func TimeSlotLTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldTimeSlot, v))
}

// TimeSlotContains applies the Contains predicate on the "time_slot" field.
func TimeSlotContains(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContains(FieldTimeSlot, v))
}

// TimeSlotHasPrefix applies the HasPrefix predicate on the "time_slot" field.
func TimeSlotHasPrefix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasPrefix(FieldTimeSlot, v))
}

// TimeSlotHasSuffix applies the HasSuffix predicate on the "time_slot" field.
func TimeSlotHasSuffix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasSuffix(FieldTimeSlot, v))
}

// TimeSlotIsNil applies the IsNil predicate on the "time_slot" field.
func TimeSlotIsNil() predicate.Inventory {
	return predicate.Inventory(sql.FieldIsNull(FieldTimeSlot))
}

// TimeSlotNotNil applies the NotNil predicate on the "time_slot" field.
func TimeSlotNotNil() predicate.Inventory {
	return predicate.Inventory(sql.FieldNotNull(FieldTimeSlot))
}

// TimeSlotEqualFold applies the EqualFold predicate on the "time_slot" field.
func TimeSlotEqualFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEqualFold(FieldTimeSlot, v))
}

// TimeSlotContainsFold applies the ContainsFold predicate on the "time_slot" field.
func TimeSlotContainsFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContainsFold(FieldTimeSlot, v))
}

// CapacityEQ applies the EQ predicate on the "capacity" field.
func CapacityEQ(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldCapacity, v))
}

// CapacityNEQ applies the NEQ predicate on the "capacity" field.
func CapacityNEQ(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldCapacity, v))
}

// CapacityIn applies the In predicate on the "capacity" field.
func CapacityIn(vs ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldCapacity, vs...))
}

// CapacityNotIn applies the NotIn predicate on the "capacity" field.
func CapacityNotIn(vs ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldCapacity, vs...))
}

// CapacityGT applies the GT predicate on the "capacity" field.
func CapacityGT(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldCapacity, v))
}

// CapacityGTE applies the GTE predicate on the "capacity" field.
func CapacityGTE(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldCapacity, v))
}

// CapacityLT applies the LT predicate on the "capacity" field.
func CapacityLT(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldCapacity, v))
}

// CapacityLTE applies the LTE predicate on the "capacity" field.
func CapacityLTE(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldCapacity, v))
}

// ReservedEQ applies the EQ predicate on the "reserved" field.
func ReservedEQ(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldReserved, v))
}

// ReservedNEQ applies the NEQ predicate on the "reserved" field.
func ReservedNEQ(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldReserved, v))
}

// ReservedIn applies the In predicate on the "reserved" field.
func ReservedIn(vs ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldReserved, vs...))
}

// ReservedNotIn applies the NotIn predicate on the "reserved" field.
func ReservedNotIn(vs ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldReserved, vs...))
}

// ReservedGT applies the GT predicate on the "reserved" field.
func ReservedGT(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldReserved, v))
}

// ReservedGTE applies the GTE predicate on the "reserved" field.
func ReservedGTE(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldReserved, v))
}

// ReservedLT applies the LT predicate on the "reserved" field.
func ReservedLT(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldReserved, v))
}

// ReservedLTE applies the LTE predicate on the "reserved" field.
func ReservedLTE(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldReserved, v))
}

// UnitPriceEQ applies the EQ predicate on the "unit_price" field.
func UnitPriceEQ(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldUnitPrice, v))
}

// UnitPriceNEQ applies the NEQ predicate on the "unit_price" field.
func UnitPriceNEQ(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldUnitPrice, v))
}

// UnitPriceIn applies the In predicate on the "unit_price" field.
func UnitPriceIn(vs ...int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldUnitPrice, vs...))
}

// UnitPriceNotIn applies the NotIn predicate on the "unit_price" field.
func UnitPriceNotIn(vs ...int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldUnitPrice, vs...))
}

// UnitPriceGT applies the GT predicate on the "unit_price" field.
func UnitPriceGT(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldUnitPrice, v))
}

// UnitPriceGTE applies the GTE predicate on the "unit_price" field.
func UnitPriceGTE(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldUnitPrice, v))
}

// UnitPriceLT applies the LT predicate on the "unit_price" field.
func UnitPriceLT(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldUnitPrice, v))
}

// UnitPriceLTE applies the LTE predicate on the "unit_price" field.
func UnitPriceLTE(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldUnitPrice, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContainsFold(FieldCurrency, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContainsFold(FieldStatus, v))
}

// InventoryModeEQ applies the EQ predicate on the "inventory_mode" field.
func InventoryModeEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldInventoryMode, v))
}

// InventoryModeNEQ applies the NEQ predicate on the "inventory_mode" field.
func InventoryModeNEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldInventoryMode, v))
}

// InventoryModeIn applies the In predicate on the "inventory_mode" field.
func InventoryModeIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldInventoryMode, vs...))
}

// InventoryModeNotIn applies the NotIn predicate on the "inventory_mode" field.
func InventoryModeNotIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldInventoryMode, vs...))
}

// InventoryModeGT applies the GT predicate on the "inventory_mode" field.
func InventoryModeGT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldInventoryMode, v))
}

// InventoryModeGTE applies the GTE predicate on the "inventory_mode" field.
func InventoryModeGTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldInventoryMode, v))
}

// InventoryModeLT applies the LT predicate on the "inventory_mode" field.
func InventoryModeLT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldInventoryMode, v))
}

// InventoryModeLTE applies the LTE predicate on the "inventory_mode" field.
func InventoryModeLTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldInventoryMode, v))
}

// InventoryModeContains applies the Contains predicate on the "inventory_mode" field.
func InventoryModeContains(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContains(FieldInventoryMode, v))
}

// InventoryModeHasPrefix applies the HasPrefix predicate on the "inventory_mode" field.
func InventoryModeHasPrefix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasPrefix(FieldInventoryMode, v))
}

// InventoryModeHasSuffix applies the HasSuffix predicate on the "inventory_mode" field.
func InventoryModeHasSuffix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasSuffix(FieldInventoryMode, v))
}

// InventoryModeEqualFold applies the EqualFold predicate on the "inventory_mode" field.
func InventoryModeEqualFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEqualFold(FieldInventoryMode, v))
}

// InventoryModeContainsFold applies the ContainsFold predicate on the "inventory_mode" field.
func InventoryModeContainsFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContainsFold(FieldInventoryMode, v))
}

// TotalCapacityEQ applies the EQ predicate on the "total_capacity" field.
func TotalCapacityEQ(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldTotalCapacity, v))
}

// TotalCapacityNEQ applies the NEQ predicate on the "total_capacity" field.
func TotalCapacityNEQ(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldTotalCapacity, v))
}

// TotalCapacityIn applies the In predicate on the "total_capacity" field.
func TotalCapacityIn(vs ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldTotalCapacity, vs...))
}

// TotalCapacityNotIn applies the NotIn predicate on the "total_capacity" field.
func TotalCapacityNotIn(vs ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldTotalCapacity, vs...))
}

// TotalCapacityGT applies the GT predicate on the "total_capacity" field.
func TotalCapacityGT(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldTotalCapacity, v))
}

// TotalCapacityGTE applies the GTE predicate on the "total_capacity" field.
func TotalCapacityGTE(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldTotalCapacity, v))
}

// TotalCapacityLT applies the LT predicate on the "total_capacity" field.
func TotalCapacityLT(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldTotalCapacity, v))
}

// TotalCapacityLTE applies the LTE predicate on the "total_capacity" field.
func TotalCapacityLTE(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldTotalCapacity, v))
}

// TotalCapacityIsNil applies the IsNil predicate on the "total_capacity" field.
func TotalCapacityIsNil() predicate.Inventory {
	return predicate.Inventory(sql.FieldIsNull(FieldTotalCapacity))
}

// TotalCapacityNotNil applies the NotNil predicate on the "total_capacity" field.
func TotalCapacityNotNil() predicate.Inventory {
	return predicate.Inventory(sql.FieldNotNull(FieldTotalCapacity))
}

// IsOpenEQ applies the EQ predicate on the "is_open" field.
func IsOpenEQ(v bool) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldIsOpen, v))
}

// IsOpenNEQ applies the NEQ predicate on the "is_open" field.
func IsOpenNEQ(v bool) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldIsOpen, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Inventory) predicate.Inventory {
	return predicate.Inventory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Inventory) predicate.Inventory {
	return predicate.Inventory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Inventory) predicate.Inventory {
	return predicate.Inventory(sql.NotPredicates(p))
}
