// Code generated by ent, DO NOT EDIT.

package itinerarystop

import (
	"entgo.io/ent/dialect/sql"
	"gitee.com/meinongyihe/travel-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldTenantID, v))
}

// MerchantID applies equality check predicate on the "merchant_id" field. It's identical to MerchantIDEQ.
func MerchantID(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldMerchantID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldProductID, v))
}

// StopType applies equality check predicate on the "stop_type" field. It's identical to StopTypeEQ.
func StopType(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldStopType, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDescription, v))
}

// Sequence applies equality check predicate on the "sequence" field. It's identical to SequenceEQ.
func Sequence(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldSequence, v))
}

// LocationName applies equality check predicate on the "location_name" field. It's identical to LocationNameEQ.
func LocationName(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldLocationName, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldAddress, v))
}

// Latitude applies equality check predicate on the "latitude" field. It's identical to LatitudeEQ.
func Latitude(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldLatitude, v))
}

// Longitude applies equality check predicate on the "longitude" field. It's identical to LongitudeEQ.
func Longitude(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldLongitude, v))
}

// PoiID applies equality check predicate on the "poi_id" field. It's identical to PoiIDEQ.
func PoiID(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPoiID, v))
}

// PoiName applies equality check predicate on the "poi_name" field. It's identical to PoiNameEQ.
func PoiName(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPoiName, v))
}

// IsEntering applies equality check predicate on the "is_entering" field. It's identical to IsEnteringEQ.
func IsEntering(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldIsEntering, v))
}

// DurationMode applies equality check predicate on the "duration_mode" field. It's identical to DurationModeEQ.
func DurationMode(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDurationMode, v))
}

// DurationHours applies equality check predicate on the "duration_hours" field. It's identical to DurationHoursEQ.
func DurationHours(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDurationHours, v))
}

// DurationMinutes applies equality check predicate on the "duration_minutes" field. It's identical to DurationMinutesEQ.
func DurationMinutes(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDurationMinutes, v))
}

// ActivityFeatures applies equality check predicate on the "activity_features" field. It's identical to ActivityFeaturesEQ.
func ActivityFeatures(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldActivityFeatures, v))
}

// TransportType applies equality check predicate on the "transport_type" field. It's identical to TransportTypeEQ.
func TransportType(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldTransportType, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldEndTime, v))
}

// PickupLocation applies equality check predicate on the "pickup_location" field. It's identical to PickupLocationEQ.
func PickupLocation(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPickupLocation, v))
}

// PickupAddress applies equality check predicate on the "pickup_address" field. It's identical to PickupAddressEQ.
func PickupAddress(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPickupAddress, v))
}

// PickupLatitude applies equality check predicate on the "pickup_latitude" field. It's identical to PickupLatitudeEQ.
func PickupLatitude(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPickupLatitude, v))
}

// PickupLongitude applies equality check predicate on the "pickup_longitude" field. It's identical to PickupLongitudeEQ.
func PickupLongitude(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPickupLongitude, v))
}

// DropoffLocation applies equality check predicate on the "dropoff_location" field. It's identical to DropoffLocationEQ.
func DropoffLocation(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDropoffLocation, v))
}

// DropoffAddress applies equality check predicate on the "dropoff_address" field. It's identical to DropoffAddressEQ.
func DropoffAddress(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDropoffAddress, v))
}

// DropoffLatitude applies equality check predicate on the "dropoff_latitude" field. It's identical to DropoffLatitudeEQ.
func DropoffLatitude(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDropoffLatitude, v))
}

// DropoffLongitude applies equality check predicate on the "dropoff_longitude" field. It's identical to DropoffLongitudeEQ.
func DropoffLongitude(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDropoffLongitude, v))
}

// IsPickup applies equality check predicate on the "is_pickup" field. It's identical to IsPickupEQ.
func IsPickup(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldIsPickup, v))
}

// IsDropoff applies equality check predicate on the "is_dropoff" field. It's identical to IsDropoffEQ.
func IsDropoff(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldIsDropoff, v))
}

// AgreementNoShopping applies equality check predicate on the "agreement_no_shopping" field. It's identical to AgreementNoShoppingEQ.
func AgreementNoShopping(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldAgreementNoShopping, v))
}

// AgreementAdjustable applies equality check predicate on the "agreement_adjustable" field. It's identical to AgreementAdjustableEQ.
func AgreementAdjustable(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldAgreementAdjustable, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldTenantID, v))
}

// MerchantIDEQ applies the EQ predicate on the "merchant_id" field.
func MerchantIDEQ(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldMerchantID, v))
}

// MerchantIDNEQ applies the NEQ predicate on the "merchant_id" field.
func MerchantIDNEQ(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldMerchantID, v))
}

// MerchantIDIn applies the In predicate on the "merchant_id" field.
func MerchantIDIn(vs ...int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldMerchantID, vs...))
}

// MerchantIDNotIn applies the NotIn predicate on the "merchant_id" field.
func MerchantIDNotIn(vs ...int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldMerchantID, vs...))
}

// MerchantIDGT applies the GT predicate on the "merchant_id" field.
func MerchantIDGT(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldMerchantID, v))
}

// MerchantIDGTE applies the GTE predicate on the "merchant_id" field.
func MerchantIDGTE(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldMerchantID, v))
}

// MerchantIDLT applies the LT predicate on the "merchant_id" field.
func MerchantIDLT(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldMerchantID, v))
}

// MerchantIDLTE applies the LTE predicate on the "merchant_id" field.
func MerchantIDLTE(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldMerchantID, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v int64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldProductID, v))
}

// StopTypeEQ applies the EQ predicate on the "stop_type" field.
func StopTypeEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldStopType, v))
}

// StopTypeNEQ applies the NEQ predicate on the "stop_type" field.
func StopTypeNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldStopType, v))
}

// StopTypeIn applies the In predicate on the "stop_type" field.
func StopTypeIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldStopType, vs...))
}

// StopTypeNotIn applies the NotIn predicate on the "stop_type" field.
func StopTypeNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldStopType, vs...))
}

// StopTypeGT applies the GT predicate on the "stop_type" field.
func StopTypeGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldStopType, v))
}

// StopTypeGTE applies the GTE predicate on the "stop_type" field.
func StopTypeGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldStopType, v))
}

// StopTypeLT applies the LT predicate on the "stop_type" field.
func StopTypeLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldStopType, v))
}

// StopTypeLTE applies the LTE predicate on the "stop_type" field.
func StopTypeLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldStopType, v))
}

// StopTypeContains applies the Contains predicate on the "stop_type" field.
func StopTypeContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldStopType, v))
}

// StopTypeHasPrefix applies the HasPrefix predicate on the "stop_type" field.
func StopTypeHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldStopType, v))
}

// StopTypeHasSuffix applies the HasSuffix predicate on the "stop_type" field.
func StopTypeHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldStopType, v))
}

// StopTypeEqualFold applies the EqualFold predicate on the "stop_type" field.
func StopTypeEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldStopType, v))
}

// StopTypeContainsFold applies the ContainsFold predicate on the "stop_type" field.
func StopTypeContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldStopType, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldDescription, v))
}

// SequenceEQ applies the EQ predicate on the "sequence" field.
func SequenceEQ(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldSequence, v))
}

// SequenceNEQ applies the NEQ predicate on the "sequence" field.
func SequenceNEQ(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldSequence, v))
}

// SequenceIn applies the In predicate on the "sequence" field.
func SequenceIn(vs ...int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldSequence, vs...))
}

// SequenceNotIn applies the NotIn predicate on the "sequence" field.
func SequenceNotIn(vs ...int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldSequence, vs...))
}

// SequenceGT applies the GT predicate on the "sequence" field.
func SequenceGT(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldSequence, v))
}

// SequenceGTE applies the GTE predicate on the "sequence" field.
func SequenceGTE(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldSequence, v))
}

// SequenceLT applies the LT predicate on the "sequence" field.
func SequenceLT(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldSequence, v))
}

// SequenceLTE applies the LTE predicate on the "sequence" field.
func SequenceLTE(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldSequence, v))
}

// LocationNameEQ applies the EQ predicate on the "location_name" field.
func LocationNameEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldLocationName, v))
}

// LocationNameNEQ applies the NEQ predicate on the "location_name" field.
func LocationNameNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldLocationName, v))
}

// LocationNameIn applies the In predicate on the "location_name" field.
func LocationNameIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldLocationName, vs...))
}

// LocationNameNotIn applies the NotIn predicate on the "location_name" field.
func LocationNameNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldLocationName, vs...))
}

// LocationNameGT applies the GT predicate on the "location_name" field.
func LocationNameGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldLocationName, v))
}

// LocationNameGTE applies the GTE predicate on the "location_name" field.
func LocationNameGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldLocationName, v))
}

// LocationNameLT applies the LT predicate on the "location_name" field.
func LocationNameLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldLocationName, v))
}

// LocationNameLTE applies the LTE predicate on the "location_name" field.
func LocationNameLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldLocationName, v))
}

// LocationNameContains applies the Contains predicate on the "location_name" field.
func LocationNameContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldLocationName, v))
}

// LocationNameHasPrefix applies the HasPrefix predicate on the "location_name" field.
func LocationNameHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldLocationName, v))
}

// LocationNameHasSuffix applies the HasSuffix predicate on the "location_name" field.
func LocationNameHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldLocationName, v))
}

// LocationNameIsNil applies the IsNil predicate on the "location_name" field.
func LocationNameIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldLocationName))
}

// LocationNameNotNil applies the NotNil predicate on the "location_name" field.
func LocationNameNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldLocationName))
}

// LocationNameEqualFold applies the EqualFold predicate on the "location_name" field.
func LocationNameEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldLocationName, v))
}

// LocationNameContainsFold applies the ContainsFold predicate on the "location_name" field.
func LocationNameContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldLocationName, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressIsNil applies the IsNil predicate on the "address" field.
func AddressIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldAddress))
}

// AddressNotNil applies the NotNil predicate on the "address" field.
func AddressNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldAddress))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldAddress, v))
}

// LatitudeEQ applies the EQ predicate on the "latitude" field.
func LatitudeEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldLatitude, v))
}

// LatitudeNEQ applies the NEQ predicate on the "latitude" field.
func LatitudeNEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldLatitude, v))
}

// LatitudeIn applies the In predicate on the "latitude" field.
func LatitudeIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldLatitude, vs...))
}

// LatitudeNotIn applies the NotIn predicate on the "latitude" field.
func LatitudeNotIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldLatitude, vs...))
}

// LatitudeGT applies the GT predicate on the "latitude" field.
func LatitudeGT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldLatitude, v))
}

// LatitudeGTE applies the GTE predicate on the "latitude" field.
func LatitudeGTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldLatitude, v))
}

// LatitudeLT applies the LT predicate on the "latitude" field.
func LatitudeLT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldLatitude, v))
}

// LatitudeLTE applies the LTE predicate on the "latitude" field.
func LatitudeLTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldLatitude, v))
}

// LatitudeIsNil applies the IsNil predicate on the "latitude" field.
func LatitudeIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldLatitude))
}

// LatitudeNotNil applies the NotNil predicate on the "latitude" field.
func LatitudeNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldLatitude))
}

// LongitudeEQ applies the EQ predicate on the "longitude" field.
func LongitudeEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldLongitude, v))
}

// LongitudeNEQ applies the NEQ predicate on the "longitude" field.
func LongitudeNEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldLongitude, v))
}

// LongitudeIn applies the In predicate on the "longitude" field.
func LongitudeIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldLongitude, vs...))
}

// LongitudeNotIn applies the NotIn predicate on the "longitude" field.
func LongitudeNotIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldLongitude, vs...))
}

// LongitudeGT applies the GT predicate on the "longitude" field.
func LongitudeGT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldLongitude, v))
}

// LongitudeGTE applies the GTE predicate on the "longitude" field.
func LongitudeGTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldLongitude, v))
}

// LongitudeLT applies the LT predicate on the "longitude" field.
func LongitudeLT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldLongitude, v))
}

// LongitudeLTE applies the LTE predicate on the "longitude" field.
func LongitudeLTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldLongitude, v))
}

// LongitudeIsNil applies the IsNil predicate on the "longitude" field.
func LongitudeIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldLongitude))
}

// LongitudeNotNil applies the NotNil predicate on the "longitude" field.
func LongitudeNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldLongitude))
}

// PoiIDEQ applies the EQ predicate on the "poi_id" field.
func PoiIDEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPoiID, v))
}

// PoiIDNEQ applies the NEQ predicate on the "poi_id" field.
func PoiIDNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldPoiID, v))
}

// PoiIDIn applies the In predicate on the "poi_id" field.
func PoiIDIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldPoiID, vs...))
}

// PoiIDNotIn applies the NotIn predicate on the "poi_id" field.
func PoiIDNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldPoiID, vs...))
}

// PoiIDGT applies the GT predicate on the "poi_id" field.
func PoiIDGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldPoiID, v))
}

// PoiIDGTE applies the GTE predicate on the "poi_id" field.
func PoiIDGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldPoiID, v))
}

// PoiIDLT applies the LT predicate on the "poi_id" field.
func PoiIDLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldPoiID, v))
}

// PoiIDLTE applies the LTE predicate on the "poi_id" field.
func PoiIDLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldPoiID, v))
}

// PoiIDContains applies the Contains predicate on the "poi_id" field.
func PoiIDContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldPoiID, v))
}

// PoiIDHasPrefix applies the HasPrefix predicate on the "poi_id" field.
func PoiIDHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldPoiID, v))
}

// PoiIDHasSuffix applies the HasSuffix predicate on the "poi_id" field.
func PoiIDHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldPoiID, v))
}

// PoiIDIsNil applies the IsNil predicate on the "poi_id" field.
func PoiIDIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldPoiID))
}

// PoiIDNotNil applies the NotNil predicate on the "poi_id" field.
func PoiIDNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldPoiID))
}

// PoiIDEqualFold applies the EqualFold predicate on the "poi_id" field.
func PoiIDEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldPoiID, v))
}

// PoiIDContainsFold applies the ContainsFold predicate on the "poi_id" field.
func PoiIDContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldPoiID, v))
}

// PoiNameEQ applies the EQ predicate on the "poi_name" field.
func PoiNameEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPoiName, v))
}

// PoiNameNEQ applies the NEQ predicate on the "poi_name" field.
func PoiNameNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldPoiName, v))
}

// PoiNameIn applies the In predicate on the "poi_name" field.
func PoiNameIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldPoiName, vs...))
}

// PoiNameNotIn applies the NotIn predicate on the "poi_name" field.
func PoiNameNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldPoiName, vs...))
}

// PoiNameGT applies the GT predicate on the "poi_name" field.
func PoiNameGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldPoiName, v))
}

// PoiNameGTE applies the GTE predicate on the "poi_name" field.
func PoiNameGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldPoiName, v))
}

// PoiNameLT applies the LT predicate on the "poi_name" field.
func PoiNameLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldPoiName, v))
}

// PoiNameLTE applies the LTE predicate on the "poi_name" field.
func PoiNameLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldPoiName, v))
}

// PoiNameContains applies the Contains predicate on the "poi_name" field.
func PoiNameContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldPoiName, v))
}

// PoiNameHasPrefix applies the HasPrefix predicate on the "poi_name" field.
func PoiNameHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldPoiName, v))
}

// PoiNameHasSuffix applies the HasSuffix predicate on the "poi_name" field.
func PoiNameHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldPoiName, v))
}

// PoiNameIsNil applies the IsNil predicate on the "poi_name" field.
func PoiNameIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldPoiName))
}

// PoiNameNotNil applies the NotNil predicate on the "poi_name" field.
func PoiNameNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldPoiName))
}

// PoiNameEqualFold applies the EqualFold predicate on the "poi_name" field.
func PoiNameEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldPoiName, v))
}

// PoiNameContainsFold applies the ContainsFold predicate on the "poi_name" field.
func PoiNameContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldPoiName, v))
}

// IsEnteringEQ applies the EQ predicate on the "is_entering" field.
func IsEnteringEQ(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldIsEntering, v))
}

// IsEnteringNEQ applies the NEQ predicate on the "is_entering" field.
func IsEnteringNEQ(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldIsEntering, v))
}

// DurationModeEQ applies the EQ predicate on the "duration_mode" field.
func DurationModeEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDurationMode, v))
}

// DurationModeNEQ applies the NEQ predicate on the "duration_mode" field.
func DurationModeNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldDurationMode, v))
}

// DurationModeIn applies the In predicate on the "duration_mode" field.
func DurationModeIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldDurationMode, vs...))
}

// DurationModeNotIn applies the NotIn predicate on the "duration_mode" field.
func DurationModeNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldDurationMode, vs...))
}

// DurationModeGT applies the GT predicate on the "duration_mode" field.
func DurationModeGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldDurationMode, v))
}

// DurationModeGTE applies the GTE predicate on the "duration_mode" field.
func DurationModeGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldDurationMode, v))
}

// DurationModeLT applies the LT predicate on the "duration_mode" field.
func DurationModeLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldDurationMode, v))
}

// DurationModeLTE applies the LTE predicate on the "duration_mode" field.
func DurationModeLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldDurationMode, v))
}

// DurationModeContains applies the Contains predicate on the "duration_mode" field.
func DurationModeContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldDurationMode, v))
}

// DurationModeHasPrefix applies the HasPrefix predicate on the "duration_mode" field.
func DurationModeHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldDurationMode, v))
}

// DurationModeHasSuffix applies the HasSuffix predicate on the "duration_mode" field.
func DurationModeHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldDurationMode, v))
}

// DurationModeIsNil applies the IsNil predicate on the "duration_mode" field.
func DurationModeIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldDurationMode))
}

// DurationModeNotNil applies the NotNil predicate on the "duration_mode" field.
func DurationModeNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldDurationMode))
}

// DurationModeEqualFold applies the EqualFold predicate on the "duration_mode" field.
func DurationModeEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldDurationMode, v))
}

// DurationModeContainsFold applies the ContainsFold predicate on the "duration_mode" field.
func DurationModeContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldDurationMode, v))
}

// DurationHoursEQ applies the EQ predicate on the "duration_hours" field.
func DurationHoursEQ(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDurationHours, v))
}

// DurationHoursNEQ applies the NEQ predicate on the "duration_hours" field.
func DurationHoursNEQ(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldDurationHours, v))
}

// DurationHoursIn applies the In predicate on the "duration_hours" field.
func DurationHoursIn(vs ...int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldDurationHours, vs...))
}

// DurationHoursNotIn applies the NotIn predicate on the "duration_hours" field.
func DurationHoursNotIn(vs ...int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldDurationHours, vs...))
}

// DurationHoursGT applies the GT predicate on the "duration_hours" field.
func DurationHoursGT(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldDurationHours, v))
}

// DurationHoursGTE applies the GTE predicate on the "duration_hours" field.
func DurationHoursGTE(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldDurationHours, v))
}

// DurationHoursLT applies the LT predicate on the "duration_hours" field.
func DurationHoursLT(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldDurationHours, v))
}

// DurationHoursLTE applies the LTE predicate on the "duration_hours" field.
func DurationHoursLTE(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldDurationHours, v))
}

// DurationHoursIsNil applies the IsNil predicate on the "duration_hours" field.
func DurationHoursIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldDurationHours))
}

// DurationHoursNotNil applies the NotNil predicate on the "duration_hours" field.
func DurationHoursNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldDurationHours))
}

// DurationMinutesEQ applies the EQ predicate on the "duration_minutes" field.
func DurationMinutesEQ(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDurationMinutes, v))
}

// DurationMinutesNEQ applies the NEQ predicate on the "duration_minutes" field.
func DurationMinutesNEQ(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldDurationMinutes, v))
}

// DurationMinutesIn applies the In predicate on the "duration_minutes" field.
func DurationMinutesIn(vs ...int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldDurationMinutes, vs...))
}

// DurationMinutesNotIn applies the NotIn predicate on the "duration_minutes" field.
func DurationMinutesNotIn(vs ...int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldDurationMinutes, vs...))
}

// DurationMinutesGT applies the GT predicate on the "duration_minutes" field.
func DurationMinutesGT(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldDurationMinutes, v))
}

// DurationMinutesGTE applies the GTE predicate on the "duration_minutes" field.
func DurationMinutesGTE(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldDurationMinutes, v))
}

// DurationMinutesLT applies the LT predicate on the "duration_minutes" field.
func DurationMinutesLT(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldDurationMinutes, v))
}

// DurationMinutesLTE applies the LTE predicate on the "duration_minutes" field.
func DurationMinutesLTE(v int) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldDurationMinutes, v))
}

// DurationMinutesIsNil applies the IsNil predicate on the "duration_minutes" field.
func DurationMinutesIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldDurationMinutes))
}

// DurationMinutesNotNil applies the NotNil predicate on the "duration_minutes" field.
func DurationMinutesNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldDurationMinutes))
}

// ActivityFeaturesEQ applies the EQ predicate on the "activity_features" field.
func ActivityFeaturesEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldActivityFeatures, v))
}

// ActivityFeaturesNEQ applies the NEQ predicate on the "activity_features" field.
func ActivityFeaturesNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldActivityFeatures, v))
}

// ActivityFeaturesIn applies the In predicate on the "activity_features" field.
func ActivityFeaturesIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldActivityFeatures, vs...))
}

// ActivityFeaturesNotIn applies the NotIn predicate on the "activity_features" field.
func ActivityFeaturesNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldActivityFeatures, vs...))
}

// ActivityFeaturesGT applies the GT predicate on the "activity_features" field.
func ActivityFeaturesGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldActivityFeatures, v))
}

// ActivityFeaturesGTE applies the GTE predicate on the "activity_features" field.
func ActivityFeaturesGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldActivityFeatures, v))
}

// ActivityFeaturesLT applies the LT predicate on the "activity_features" field.
func ActivityFeaturesLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldActivityFeatures, v))
}

// ActivityFeaturesLTE applies the LTE predicate on the "activity_features" field.
func ActivityFeaturesLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldActivityFeatures, v))
}

// ActivityFeaturesContains applies the Contains predicate on the "activity_features" field.
func ActivityFeaturesContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldActivityFeatures, v))
}

// ActivityFeaturesHasPrefix applies the HasPrefix predicate on the "activity_features" field.
func ActivityFeaturesHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldActivityFeatures, v))
}

// ActivityFeaturesHasSuffix applies the HasSuffix predicate on the "activity_features" field.
func ActivityFeaturesHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldActivityFeatures, v))
}

// ActivityFeaturesIsNil applies the IsNil predicate on the "activity_features" field.
func ActivityFeaturesIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldActivityFeatures))
}

// ActivityFeaturesNotNil applies the NotNil predicate on the "activity_features" field.
func ActivityFeaturesNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldActivityFeatures))
}

// ActivityFeaturesEqualFold applies the EqualFold predicate on the "activity_features" field.
func ActivityFeaturesEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldActivityFeatures, v))
}

// ActivityFeaturesContainsFold applies the ContainsFold predicate on the "activity_features" field.
func ActivityFeaturesContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldActivityFeatures, v))
}

// TransportTypeEQ applies the EQ predicate on the "transport_type" field.
func TransportTypeEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldTransportType, v))
}

// TransportTypeNEQ applies the NEQ predicate on the "transport_type" field.
func TransportTypeNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldTransportType, v))
}

// TransportTypeIn applies the In predicate on the "transport_type" field.
func TransportTypeIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldTransportType, vs...))
}

// TransportTypeNotIn applies the NotIn predicate on the "transport_type" field.
func TransportTypeNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldTransportType, vs...))
}

// TransportTypeGT applies the GT predicate on the "transport_type" field.
func TransportTypeGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldTransportType, v))
}

// TransportTypeGTE applies the GTE predicate on the "transport_type" field.
func TransportTypeGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldTransportType, v))
}

// TransportTypeLT applies the LT predicate on the "transport_type" field.
func TransportTypeLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldTransportType, v))
}

// TransportTypeLTE applies the LTE predicate on the "transport_type" field.
func TransportTypeLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldTransportType, v))
}

// TransportTypeContains applies the Contains predicate on the "transport_type" field.
func TransportTypeContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldTransportType, v))
}

// TransportTypeHasPrefix applies the HasPrefix predicate on the "transport_type" field.
func TransportTypeHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldTransportType, v))
}

// TransportTypeHasSuffix applies the HasSuffix predicate on the "transport_type" field.
func TransportTypeHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldTransportType, v))
}

// TransportTypeIsNil applies the IsNil predicate on the "transport_type" field.
func TransportTypeIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldTransportType))
}

// TransportTypeNotNil applies the NotNil predicate on the "transport_type" field.
func TransportTypeNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldTransportType))
}

// TransportTypeEqualFold applies the EqualFold predicate on the "transport_type" field.
func TransportTypeEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldTransportType, v))
}

// TransportTypeContainsFold applies the ContainsFold predicate on the "transport_type" field.
func TransportTypeContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldTransportType, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldStartTime, v))
}

// StartTimeContains applies the Contains predicate on the "start_time" field.
func StartTimeContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldStartTime, v))
}

// StartTimeHasPrefix applies the HasPrefix predicate on the "start_time" field.
func StartTimeHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldStartTime, v))
}

// StartTimeHasSuffix applies the HasSuffix predicate on the "start_time" field.
func StartTimeHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldStartTime, v))
}

// StartTimeIsNil applies the IsNil predicate on the "start_time" field.
func StartTimeIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldStartTime))
}

// StartTimeNotNil applies the NotNil predicate on the "start_time" field.
func StartTimeNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldStartTime))
}

// StartTimeEqualFold applies the EqualFold predicate on the "start_time" field.
func StartTimeEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldStartTime, v))
}

// StartTimeContainsFold applies the ContainsFold predicate on the "start_time" field.
func StartTimeContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldStartTime, v))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldEndTime, v))
}

// EndTimeContains applies the Contains predicate on the "end_time" field.
func EndTimeContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldEndTime, v))
}

// EndTimeHasPrefix applies the HasPrefix predicate on the "end_time" field.
func EndTimeHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldEndTime, v))
}

// EndTimeHasSuffix applies the HasSuffix predicate on the "end_time" field.
func EndTimeHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldEndTime, v))
}

// EndTimeIsNil applies the IsNil predicate on the "end_time" field.
func EndTimeIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldEndTime))
}

// EndTimeNotNil applies the NotNil predicate on the "end_time" field.
func EndTimeNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldEndTime))
}

// EndTimeEqualFold applies the EqualFold predicate on the "end_time" field.
func EndTimeEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldEndTime, v))
}

// EndTimeContainsFold applies the ContainsFold predicate on the "end_time" field.
func EndTimeContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldEndTime, v))
}

// PickupLocationEQ applies the EQ predicate on the "pickup_location" field.
func PickupLocationEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPickupLocation, v))
}

// PickupLocationNEQ applies the NEQ predicate on the "pickup_location" field.
func PickupLocationNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldPickupLocation, v))
}

// PickupLocationIn applies the In predicate on the "pickup_location" field.
func PickupLocationIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldPickupLocation, vs...))
}

// PickupLocationNotIn applies the NotIn predicate on the "pickup_location" field.
func PickupLocationNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldPickupLocation, vs...))
}

// PickupLocationGT applies the GT predicate on the "pickup_location" field.
func PickupLocationGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldPickupLocation, v))
}

// PickupLocationGTE applies the GTE predicate on the "pickup_location" field.
func PickupLocationGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldPickupLocation, v))
}

// PickupLocationLT applies the LT predicate on the "pickup_location" field.
func PickupLocationLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldPickupLocation, v))
}

// PickupLocationLTE applies the LTE predicate on the "pickup_location" field.
func PickupLocationLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldPickupLocation, v))
}

// PickupLocationContains applies the Contains predicate on the "pickup_location" field.
func PickupLocationContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldPickupLocation, v))
}

// PickupLocationHasPrefix applies the HasPrefix predicate on the "pickup_location" field.
func PickupLocationHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldPickupLocation, v))
}

// PickupLocationHasSuffix applies the HasSuffix predicate on the "pickup_location" field.
func PickupLocationHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldPickupLocation, v))
}

// PickupLocationIsNil applies the IsNil predicate on the "pickup_location" field.
func PickupLocationIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldPickupLocation))
}

// PickupLocationNotNil applies the NotNil predicate on the "pickup_location" field.
func PickupLocationNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldPickupLocation))
}

// PickupLocationEqualFold applies the EqualFold predicate on the "pickup_location" field.
func PickupLocationEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldPickupLocation, v))
}

// PickupLocationContainsFold applies the ContainsFold predicate on the "pickup_location" field.
func PickupLocationContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldPickupLocation, v))
}

// PickupAddressEQ applies the EQ predicate on the "pickup_address" field.
func PickupAddressEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPickupAddress, v))
}

// PickupAddressNEQ applies the NEQ predicate on the "pickup_address" field.
func PickupAddressNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldPickupAddress, v))
}

// PickupAddressIn applies the In predicate on the "pickup_address" field.
func PickupAddressIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldPickupAddress, vs...))
}

// PickupAddressNotIn applies the NotIn predicate on the "pickup_address" field.
func PickupAddressNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldPickupAddress, vs...))
}

// PickupAddressGT applies the GT predicate on the "pickup_address" field.
func PickupAddressGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldPickupAddress, v))
}

// PickupAddressGTE applies the GTE predicate on the "pickup_address" field.
func PickupAddressGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldPickupAddress, v))
}

// PickupAddressLT applies the LT predicate on the "pickup_address" field.
func PickupAddressLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldPickupAddress, v))
}

// PickupAddressLTE applies the LTE predicate on the "pickup_address" field.
func PickupAddressLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldPickupAddress, v))
}

// PickupAddressContains applies the Contains predicate on the "pickup_address" field.
func PickupAddressContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldPickupAddress, v))
}

// PickupAddressHasPrefix applies the HasPrefix predicate on the "pickup_address" field.
func PickupAddressHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldPickupAddress, v))
}

// PickupAddressHasSuffix applies the HasSuffix predicate on the "pickup_address" field.
func PickupAddressHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldPickupAddress, v))
}

// PickupAddressIsNil applies the IsNil predicate on the "pickup_address" field.
func PickupAddressIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldPickupAddress))
}

// PickupAddressNotNil applies the NotNil predicate on the "pickup_address" field.
func PickupAddressNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldPickupAddress))
}

// PickupAddressEqualFold applies the EqualFold predicate on the "pickup_address" field.
func PickupAddressEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldPickupAddress, v))
}

// PickupAddressContainsFold applies the ContainsFold predicate on the "pickup_address" field.
func PickupAddressContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldPickupAddress, v))
}

// PickupLatitudeEQ applies the EQ predicate on the "pickup_latitude" field.
func PickupLatitudeEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPickupLatitude, v))
}

// PickupLatitudeNEQ applies the NEQ predicate on the "pickup_latitude" field.
func PickupLatitudeNEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldPickupLatitude, v))
}

// PickupLatitudeIn applies the In predicate on the "pickup_latitude" field.
func PickupLatitudeIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldPickupLatitude, vs...))
}

// PickupLatitudeNotIn applies the NotIn predicate on the "pickup_latitude" field.
func PickupLatitudeNotIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldPickupLatitude, vs...))
}

// PickupLatitudeGT applies the GT predicate on the "pickup_latitude" field.
func PickupLatitudeGT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldPickupLatitude, v))
}

// PickupLatitudeGTE applies the GTE predicate on the "pickup_latitude" field.
func PickupLatitudeGTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldPickupLatitude, v))
}

// PickupLatitudeLT applies the LT predicate on the "pickup_latitude" field.
func PickupLatitudeLT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldPickupLatitude, v))
}

// PickupLatitudeLTE applies the LTE predicate on the "pickup_latitude" field.
func PickupLatitudeLTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldPickupLatitude, v))
}

// PickupLatitudeIsNil applies the IsNil predicate on the "pickup_latitude" field.
func PickupLatitudeIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldPickupLatitude))
}

// PickupLatitudeNotNil applies the NotNil predicate on the "pickup_latitude" field.
func PickupLatitudeNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldPickupLatitude))
}

// PickupLongitudeEQ applies the EQ predicate on the "pickup_longitude" field.
func PickupLongitudeEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldPickupLongitude, v))
}

// PickupLongitudeNEQ applies the NEQ predicate on the "pickup_longitude" field.
func PickupLongitudeNEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldPickupLongitude, v))
}

// PickupLongitudeIn applies the In predicate on the "pickup_longitude" field.
func PickupLongitudeIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldPickupLongitude, vs...))
}

// PickupLongitudeNotIn applies the NotIn predicate on the "pickup_longitude" field.
func PickupLongitudeNotIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldPickupLongitude, vs...))
}

// PickupLongitudeGT applies the GT predicate on the "pickup_longitude" field.
func PickupLongitudeGT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldPickupLongitude, v))
}

// PickupLongitudeGTE applies the GTE predicate on the "pickup_longitude" field.
func PickupLongitudeGTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldPickupLongitude, v))
}

// PickupLongitudeLT applies the LT predicate on the "pickup_longitude" field.
func PickupLongitudeLT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldPickupLongitude, v))
}

// PickupLongitudeLTE applies the LTE predicate on the "pickup_longitude" field.
func PickupLongitudeLTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldPickupLongitude, v))
}

// PickupLongitudeIsNil applies the IsNil predicate on the "pickup_longitude" field.
func PickupLongitudeIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldPickupLongitude))
}

// PickupLongitudeNotNil applies the NotNil predicate on the "pickup_longitude" field.
func PickupLongitudeNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldPickupLongitude))
}

// DropoffLocationEQ applies the EQ predicate on the "dropoff_location" field.
func DropoffLocationEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDropoffLocation, v))
}

// DropoffLocationNEQ applies the NEQ predicate on the "dropoff_location" field.
func DropoffLocationNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldDropoffLocation, v))
}

// DropoffLocationIn applies the In predicate on the "dropoff_location" field.
func DropoffLocationIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldDropoffLocation, vs...))
}

// DropoffLocationNotIn applies the NotIn predicate on the "dropoff_location" field.
func DropoffLocationNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldDropoffLocation, vs...))
}

// DropoffLocationGT applies the GT predicate on the "dropoff_location" field.
func DropoffLocationGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldDropoffLocation, v))
}

// DropoffLocationGTE applies the GTE predicate on the "dropoff_location" field.
func DropoffLocationGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldDropoffLocation, v))
}

// DropoffLocationLT applies the LT predicate on the "dropoff_location" field.
func DropoffLocationLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldDropoffLocation, v))
}

// DropoffLocationLTE applies the LTE predicate on the "dropoff_location" field.
func DropoffLocationLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldDropoffLocation, v))
}

// DropoffLocationContains applies the Contains predicate on the "dropoff_location" field.
func DropoffLocationContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldDropoffLocation, v))
}

// DropoffLocationHasPrefix applies the HasPrefix predicate on the "dropoff_location" field.
func DropoffLocationHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldDropoffLocation, v))
}

// DropoffLocationHasSuffix applies the HasSuffix predicate on the "dropoff_location" field.
func DropoffLocationHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldDropoffLocation, v))
}

// DropoffLocationIsNil applies the IsNil predicate on the "dropoff_location" field.
func DropoffLocationIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldDropoffLocation))
}

// DropoffLocationNotNil applies the NotNil predicate on the "dropoff_location" field.
func DropoffLocationNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldDropoffLocation))
}

// DropoffLocationEqualFold applies the EqualFold predicate on the "dropoff_location" field.
func DropoffLocationEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldDropoffLocation, v))
}

// DropoffLocationContainsFold applies the ContainsFold predicate on the "dropoff_location" field.
func DropoffLocationContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldDropoffLocation, v))
}

// DropoffAddressEQ applies the EQ predicate on the "dropoff_address" field.
func DropoffAddressEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDropoffAddress, v))
}

// DropoffAddressNEQ applies the NEQ predicate on the "dropoff_address" field.
func DropoffAddressNEQ(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldDropoffAddress, v))
}

// DropoffAddressIn applies the In predicate on the "dropoff_address" field.
func DropoffAddressIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldDropoffAddress, vs...))
}

// DropoffAddressNotIn applies the NotIn predicate on the "dropoff_address" field.
func DropoffAddressNotIn(vs ...string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldDropoffAddress, vs...))
}

// DropoffAddressGT applies the GT predicate on the "dropoff_address" field.
func DropoffAddressGT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldDropoffAddress, v))
}

// DropoffAddressGTE applies the GTE predicate on the "dropoff_address" field.
func DropoffAddressGTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldDropoffAddress, v))
}

// DropoffAddressLT applies the LT predicate on the "dropoff_address" field.
func DropoffAddressLT(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldDropoffAddress, v))
}

// DropoffAddressLTE applies the LTE predicate on the "dropoff_address" field.
func DropoffAddressLTE(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldDropoffAddress, v))
}

// DropoffAddressContains applies the Contains predicate on the "dropoff_address" field.
func DropoffAddressContains(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContains(FieldDropoffAddress, v))
}

// DropoffAddressHasPrefix applies the HasPrefix predicate on the "dropoff_address" field.
func DropoffAddressHasPrefix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasPrefix(FieldDropoffAddress, v))
}

// DropoffAddressHasSuffix applies the HasSuffix predicate on the "dropoff_address" field.
func DropoffAddressHasSuffix(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldHasSuffix(FieldDropoffAddress, v))
}

// DropoffAddressIsNil applies the IsNil predicate on the "dropoff_address" field.
func DropoffAddressIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldDropoffAddress))
}

// DropoffAddressNotNil applies the NotNil predicate on the "dropoff_address" field.
func DropoffAddressNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldDropoffAddress))
}

// DropoffAddressEqualFold applies the EqualFold predicate on the "dropoff_address" field.
func DropoffAddressEqualFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEqualFold(FieldDropoffAddress, v))
}

// DropoffAddressContainsFold applies the ContainsFold predicate on the "dropoff_address" field.
func DropoffAddressContainsFold(v string) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldContainsFold(FieldDropoffAddress, v))
}

// DropoffLatitudeEQ applies the EQ predicate on the "dropoff_latitude" field.
func DropoffLatitudeEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDropoffLatitude, v))
}

// DropoffLatitudeNEQ applies the NEQ predicate on the "dropoff_latitude" field.
func DropoffLatitudeNEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldDropoffLatitude, v))
}

// DropoffLatitudeIn applies the In predicate on the "dropoff_latitude" field.
func DropoffLatitudeIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldDropoffLatitude, vs...))
}

// DropoffLatitudeNotIn applies the NotIn predicate on the "dropoff_latitude" field.
func DropoffLatitudeNotIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldDropoffLatitude, vs...))
}

// DropoffLatitudeGT applies the GT predicate on the "dropoff_latitude" field.
func DropoffLatitudeGT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldDropoffLatitude, v))
}

// DropoffLatitudeGTE applies the GTE predicate on the "dropoff_latitude" field.
func DropoffLatitudeGTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldDropoffLatitude, v))
}

// DropoffLatitudeLT applies the LT predicate on the "dropoff_latitude" field.
func DropoffLatitudeLT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldDropoffLatitude, v))
}

// DropoffLatitudeLTE applies the LTE predicate on the "dropoff_latitude" field.
func DropoffLatitudeLTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldDropoffLatitude, v))
}

// DropoffLatitudeIsNil applies the IsNil predicate on the "dropoff_latitude" field.
func DropoffLatitudeIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldDropoffLatitude))
}

// DropoffLatitudeNotNil applies the NotNil predicate on the "dropoff_latitude" field.
func DropoffLatitudeNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldDropoffLatitude))
}

// DropoffLongitudeEQ applies the EQ predicate on the "dropoff_longitude" field.
func DropoffLongitudeEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldDropoffLongitude, v))
}

// DropoffLongitudeNEQ applies the NEQ predicate on the "dropoff_longitude" field.
func DropoffLongitudeNEQ(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldDropoffLongitude, v))
}

// DropoffLongitudeIn applies the In predicate on the "dropoff_longitude" field.
func DropoffLongitudeIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIn(FieldDropoffLongitude, vs...))
}

// DropoffLongitudeNotIn applies the NotIn predicate on the "dropoff_longitude" field.
func DropoffLongitudeNotIn(vs ...float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotIn(FieldDropoffLongitude, vs...))
}

// DropoffLongitudeGT applies the GT predicate on the "dropoff_longitude" field.
func DropoffLongitudeGT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGT(FieldDropoffLongitude, v))
}

// DropoffLongitudeGTE applies the GTE predicate on the "dropoff_longitude" field.
func DropoffLongitudeGTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldGTE(FieldDropoffLongitude, v))
}

// DropoffLongitudeLT applies the LT predicate on the "dropoff_longitude" field.
func DropoffLongitudeLT(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLT(FieldDropoffLongitude, v))
}

// DropoffLongitudeLTE applies the LTE predicate on the "dropoff_longitude" field.
func DropoffLongitudeLTE(v float64) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldLTE(FieldDropoffLongitude, v))
}

// DropoffLongitudeIsNil applies the IsNil predicate on the "dropoff_longitude" field.
func DropoffLongitudeIsNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldIsNull(FieldDropoffLongitude))
}

// DropoffLongitudeNotNil applies the NotNil predicate on the "dropoff_longitude" field.
func DropoffLongitudeNotNil() predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNotNull(FieldDropoffLongitude))
}

// IsPickupEQ applies the EQ predicate on the "is_pickup" field.
func IsPickupEQ(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldIsPickup, v))
}

// IsPickupNEQ applies the NEQ predicate on the "is_pickup" field.
func IsPickupNEQ(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldIsPickup, v))
}

// IsDropoffEQ applies the EQ predicate on the "is_dropoff" field.
func IsDropoffEQ(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldIsDropoff, v))
}

// IsDropoffNEQ applies the NEQ predicate on the "is_dropoff" field.
func IsDropoffNEQ(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldIsDropoff, v))
}

// AgreementNoShoppingEQ applies the EQ predicate on the "agreement_no_shopping" field.
func AgreementNoShoppingEQ(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldAgreementNoShopping, v))
}

// AgreementNoShoppingNEQ applies the NEQ predicate on the "agreement_no_shopping" field.
func AgreementNoShoppingNEQ(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldAgreementNoShopping, v))
}

// AgreementAdjustableEQ applies the EQ predicate on the "agreement_adjustable" field.
func AgreementAdjustableEQ(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldEQ(FieldAgreementAdjustable, v))
}

// AgreementAdjustableNEQ applies the NEQ predicate on the "agreement_adjustable" field.
func AgreementAdjustableNEQ(v bool) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.FieldNEQ(FieldAgreementAdjustable, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ItineraryStop) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ItineraryStop) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ItineraryStop) predicate.ItineraryStop {
	return predicate.ItineraryStop(sql.NotPredicates(p))
}
