// Code generated by ent, DO NOT EDIT.

package currency

import (
	"entgo.io/ent/dialect/sql"
	"gitee.com/meinongyihe/travel-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldCode, v))
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSymbol, v))
}

// NameKey applies equality check predicate on the "name_key" field. It's identical to NameKeyEQ.
func NameKey(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldNameKey, v))
}

// Decimals applies equality check predicate on the "decimals" field. It's identical to DecimalsEQ.
func Decimals(v int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldDecimals, v))
}

// SymbolPosition applies equality check predicate on the "symbol_position" field. It's identical to SymbolPositionEQ.
func SymbolPosition(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSymbolPosition, v))
}

// IsBase applies equality check predicate on the "is_base" field. It's identical to IsBaseEQ.
func IsBase(v bool) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldIsBase, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldStatus, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSort, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldCode, v))
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSymbol, v))
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldSymbol, v))
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldSymbol, vs...))
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldSymbol, vs...))
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldSymbol, v))
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldSymbol, v))
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldSymbol, v))
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldSymbol, v))
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldSymbol, v))
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldSymbol, v))
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldSymbol, v))
}

// SymbolIsNil applies the IsNil predicate on the "symbol" field.
func SymbolIsNil() predicate.Currency {
	return predicate.Currency(sql.FieldIsNull(FieldSymbol))
}

// SymbolNotNil applies the NotNil predicate on the "symbol" field.
func SymbolNotNil() predicate.Currency {
	return predicate.Currency(sql.FieldNotNull(FieldSymbol))
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldSymbol, v))
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldSymbol, v))
}

// NameKeyEQ applies the EQ predicate on the "name_key" field.
func NameKeyEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldNameKey, v))
}

// NameKeyNEQ applies the NEQ predicate on the "name_key" field.
func NameKeyNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldNameKey, v))
}

// NameKeyIn applies the In predicate on the "name_key" field.
func NameKeyIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldNameKey, vs...))
}

// NameKeyNotIn applies the NotIn predicate on the "name_key" field.
func NameKeyNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldNameKey, vs...))
}

// NameKeyGT applies the GT predicate on the "name_key" field.
func NameKeyGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldNameKey, v))
}

// NameKeyGTE applies the GTE predicate on the "name_key" field.
func NameKeyGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldNameKey, v))
}

// NameKeyLT applies the LT predicate on the "name_key" field.
func NameKeyLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldNameKey, v))
}

// NameKeyLTE applies the LTE predicate on the "name_key" field.
func NameKeyLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldNameKey, v))
}

// NameKeyContains applies the Contains predicate on the "name_key" field.
func NameKeyContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldNameKey, v))
}

// NameKeyHasPrefix applies the HasPrefix predicate on the "name_key" field.
func NameKeyHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldNameKey, v))
}

// NameKeyHasSuffix applies the HasSuffix predicate on the "name_key" field.
func NameKeyHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldNameKey, v))
}

// NameKeyIsNil applies the IsNil predicate on the "name_key" field.
func NameKeyIsNil() predicate.Currency {
	return predicate.Currency(sql.FieldIsNull(FieldNameKey))
}

// NameKeyNotNil applies the NotNil predicate on the "name_key" field.
func NameKeyNotNil() predicate.Currency {
	return predicate.Currency(sql.FieldNotNull(FieldNameKey))
}

// NameKeyEqualFold applies the EqualFold predicate on the "name_key" field.
func NameKeyEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldNameKey, v))
}

// NameKeyContainsFold applies the ContainsFold predicate on the "name_key" field.
func NameKeyContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldNameKey, v))
}

// DecimalsEQ applies the EQ predicate on the "decimals" field.
func DecimalsEQ(v int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldDecimals, v))
}

// DecimalsNEQ applies the NEQ predicate on the "decimals" field.
func DecimalsNEQ(v int) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldDecimals, v))
}

// DecimalsIn applies the In predicate on the "decimals" field.
func DecimalsIn(vs ...int) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldDecimals, vs...))
}

// DecimalsNotIn applies the NotIn predicate on the "decimals" field.
func DecimalsNotIn(vs ...int) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldDecimals, vs...))
}

// DecimalsGT applies the GT predicate on the "decimals" field.
func DecimalsGT(v int) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldDecimals, v))
}

// DecimalsGTE applies the GTE predicate on the "decimals" field.
func DecimalsGTE(v int) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldDecimals, v))
}

// DecimalsLT applies the LT predicate on the "decimals" field.
func DecimalsLT(v int) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldDecimals, v))
}

// DecimalsLTE applies the LTE predicate on the "decimals" field.
func DecimalsLTE(v int) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldDecimals, v))
}

// SymbolPositionEQ applies the EQ predicate on the "symbol_position" field.
func SymbolPositionEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSymbolPosition, v))
}

// SymbolPositionNEQ applies the NEQ predicate on the "symbol_position" field.
func SymbolPositionNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldSymbolPosition, v))
}

// SymbolPositionIn applies the In predicate on the "symbol_position" field.
func SymbolPositionIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldSymbolPosition, vs...))
}

// SymbolPositionNotIn applies the NotIn predicate on the "symbol_position" field.
func SymbolPositionNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldSymbolPosition, vs...))
}

// SymbolPositionGT applies the GT predicate on the "symbol_position" field.
func SymbolPositionGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldSymbolPosition, v))
}

// SymbolPositionGTE applies the GTE predicate on the "symbol_position" field.
func SymbolPositionGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldSymbolPosition, v))
}

// SymbolPositionLT applies the LT predicate on the "symbol_position" field.
func SymbolPositionLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldSymbolPosition, v))
}

// SymbolPositionLTE applies the LTE predicate on the "symbol_position" field.
func SymbolPositionLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldSymbolPosition, v))
}

// SymbolPositionContains applies the Contains predicate on the "symbol_position" field.
func SymbolPositionContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldSymbolPosition, v))
}

// SymbolPositionHasPrefix applies the HasPrefix predicate on the "symbol_position" field.
func SymbolPositionHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldSymbolPosition, v))
}

// SymbolPositionHasSuffix applies the HasSuffix predicate on the "symbol_position" field.
func SymbolPositionHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldSymbolPosition, v))
}

// SymbolPositionEqualFold applies the EqualFold predicate on the "symbol_position" field.
func SymbolPositionEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldSymbolPosition, v))
}

// SymbolPositionContainsFold applies the ContainsFold predicate on the "symbol_position" field.
func SymbolPositionContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldSymbolPosition, v))
}

// IsBaseEQ applies the EQ predicate on the "is_base" field.
func IsBaseEQ(v bool) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldIsBase, v))
}

// IsBaseNEQ applies the NEQ predicate on the "is_base" field.
func IsBaseNEQ(v bool) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldIsBase, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldStatus, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldSort, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Currency) predicate.Currency {
	return predicate.Currency(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Currency) predicate.Currency {
	return predicate.Currency(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Currency) predicate.Currency {
	return predicate.Currency(sql.NotPredicates(p))
}
