// Code generated by ent, DO NOT EDIT.

package merchantconfig

import (
	"entgo.io/ent/dialect/sql"
	"gitee.com/meinongyihe/travel-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldTenantID, v))
}

// MerchantID applies equality check predicate on the "merchant_id" field. It's identical to MerchantIDEQ.
func MerchantID(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldMerchantID, v))
}

// ConfigType applies equality check predicate on the "config_type" field. It's identical to ConfigTypeEQ.
func ConfigType(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldConfigType, v))
}

// ConfigKey applies equality check predicate on the "config_key" field. It's identical to ConfigKeyEQ.
func ConfigKey(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldConfigKey, v))
}

// ConfigValue applies equality check predicate on the "config_value" field. It's identical to ConfigValueEQ.
func ConfigValue(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldConfigValue, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldDescription, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLTE(FieldTenantID, v))
}

// MerchantIDEQ applies the EQ predicate on the "merchant_id" field.
func MerchantIDEQ(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldMerchantID, v))
}

// MerchantIDNEQ applies the NEQ predicate on the "merchant_id" field.
func MerchantIDNEQ(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNEQ(FieldMerchantID, v))
}

// MerchantIDIn applies the In predicate on the "merchant_id" field.
func MerchantIDIn(vs ...int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldIn(FieldMerchantID, vs...))
}

// MerchantIDNotIn applies the NotIn predicate on the "merchant_id" field.
func MerchantIDNotIn(vs ...int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNotIn(FieldMerchantID, vs...))
}

// MerchantIDGT applies the GT predicate on the "merchant_id" field.
func MerchantIDGT(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGT(FieldMerchantID, v))
}

// MerchantIDGTE applies the GTE predicate on the "merchant_id" field.
func MerchantIDGTE(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGTE(FieldMerchantID, v))
}

// MerchantIDLT applies the LT predicate on the "merchant_id" field.
func MerchantIDLT(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLT(FieldMerchantID, v))
}

// MerchantIDLTE applies the LTE predicate on the "merchant_id" field.
func MerchantIDLTE(v int64) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLTE(FieldMerchantID, v))
}

// ConfigTypeEQ applies the EQ predicate on the "config_type" field.
func ConfigTypeEQ(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldConfigType, v))
}

// ConfigTypeNEQ applies the NEQ predicate on the "config_type" field.
func ConfigTypeNEQ(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNEQ(FieldConfigType, v))
}

// ConfigTypeIn applies the In predicate on the "config_type" field.
func ConfigTypeIn(vs ...string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldIn(FieldConfigType, vs...))
}

// ConfigTypeNotIn applies the NotIn predicate on the "config_type" field.
func ConfigTypeNotIn(vs ...string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNotIn(FieldConfigType, vs...))
}

// ConfigTypeGT applies the GT predicate on the "config_type" field.
func ConfigTypeGT(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGT(FieldConfigType, v))
}

// ConfigTypeGTE applies the GTE predicate on the "config_type" field.
func ConfigTypeGTE(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGTE(FieldConfigType, v))
}

// ConfigTypeLT applies the LT predicate on the "config_type" field.
func ConfigTypeLT(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLT(FieldConfigType, v))
}

// ConfigTypeLTE applies the LTE predicate on the "config_type" field.
func ConfigTypeLTE(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLTE(FieldConfigType, v))
}

// ConfigTypeContains applies the Contains predicate on the "config_type" field.
func ConfigTypeContains(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldContains(FieldConfigType, v))
}

// ConfigTypeHasPrefix applies the HasPrefix predicate on the "config_type" field.
func ConfigTypeHasPrefix(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldHasPrefix(FieldConfigType, v))
}

// ConfigTypeHasSuffix applies the HasSuffix predicate on the "config_type" field.
func ConfigTypeHasSuffix(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldHasSuffix(FieldConfigType, v))
}

// ConfigTypeEqualFold applies the EqualFold predicate on the "config_type" field.
func ConfigTypeEqualFold(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEqualFold(FieldConfigType, v))
}

// ConfigTypeContainsFold applies the ContainsFold predicate on the "config_type" field.
func ConfigTypeContainsFold(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldContainsFold(FieldConfigType, v))
}

// ConfigKeyEQ applies the EQ predicate on the "config_key" field.
func ConfigKeyEQ(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldConfigKey, v))
}

// ConfigKeyNEQ applies the NEQ predicate on the "config_key" field.
func ConfigKeyNEQ(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNEQ(FieldConfigKey, v))
}

// ConfigKeyIn applies the In predicate on the "config_key" field.
func ConfigKeyIn(vs ...string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldIn(FieldConfigKey, vs...))
}

// ConfigKeyNotIn applies the NotIn predicate on the "config_key" field.
func ConfigKeyNotIn(vs ...string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNotIn(FieldConfigKey, vs...))
}

// ConfigKeyGT applies the GT predicate on the "config_key" field.
func ConfigKeyGT(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGT(FieldConfigKey, v))
}

// ConfigKeyGTE applies the GTE predicate on the "config_key" field.
func ConfigKeyGTE(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGTE(FieldConfigKey, v))
}

// ConfigKeyLT applies the LT predicate on the "config_key" field.
func ConfigKeyLT(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLT(FieldConfigKey, v))
}

// ConfigKeyLTE applies the LTE predicate on the "config_key" field.
func ConfigKeyLTE(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLTE(FieldConfigKey, v))
}

// ConfigKeyContains applies the Contains predicate on the "config_key" field.
func ConfigKeyContains(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldContains(FieldConfigKey, v))
}

// ConfigKeyHasPrefix applies the HasPrefix predicate on the "config_key" field.
func ConfigKeyHasPrefix(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldHasPrefix(FieldConfigKey, v))
}

// ConfigKeyHasSuffix applies the HasSuffix predicate on the "config_key" field.
func ConfigKeyHasSuffix(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldHasSuffix(FieldConfigKey, v))
}

// ConfigKeyEqualFold applies the EqualFold predicate on the "config_key" field.
func ConfigKeyEqualFold(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEqualFold(FieldConfigKey, v))
}

// ConfigKeyContainsFold applies the ContainsFold predicate on the "config_key" field.
func ConfigKeyContainsFold(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldContainsFold(FieldConfigKey, v))
}

// ConfigValueEQ applies the EQ predicate on the "config_value" field.
func ConfigValueEQ(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldConfigValue, v))
}

// ConfigValueNEQ applies the NEQ predicate on the "config_value" field.
func ConfigValueNEQ(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNEQ(FieldConfigValue, v))
}

// ConfigValueIn applies the In predicate on the "config_value" field.
func ConfigValueIn(vs ...string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldIn(FieldConfigValue, vs...))
}

// ConfigValueNotIn applies the NotIn predicate on the "config_value" field.
func ConfigValueNotIn(vs ...string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNotIn(FieldConfigValue, vs...))
}

// ConfigValueGT applies the GT predicate on the "config_value" field.
func ConfigValueGT(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGT(FieldConfigValue, v))
}

// ConfigValueGTE applies the GTE predicate on the "config_value" field.
func ConfigValueGTE(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGTE(FieldConfigValue, v))
}

// ConfigValueLT applies the LT predicate on the "config_value" field.
func ConfigValueLT(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLT(FieldConfigValue, v))
}

// ConfigValueLTE applies the LTE predicate on the "config_value" field.
func ConfigValueLTE(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLTE(FieldConfigValue, v))
}

// ConfigValueContains applies the Contains predicate on the "config_value" field.
func ConfigValueContains(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldContains(FieldConfigValue, v))
}

// ConfigValueHasPrefix applies the HasPrefix predicate on the "config_value" field.
func ConfigValueHasPrefix(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldHasPrefix(FieldConfigValue, v))
}

// ConfigValueHasSuffix applies the HasSuffix predicate on the "config_value" field.
func ConfigValueHasSuffix(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldHasSuffix(FieldConfigValue, v))
}

// ConfigValueIsNil applies the IsNil predicate on the "config_value" field.
func ConfigValueIsNil() predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldIsNull(FieldConfigValue))
}

// ConfigValueNotNil applies the NotNil predicate on the "config_value" field.
func ConfigValueNotNil() predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNotNull(FieldConfigValue))
}

// ConfigValueEqualFold applies the EqualFold predicate on the "config_value" field.
func ConfigValueEqualFold(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEqualFold(FieldConfigValue, v))
}

// ConfigValueContainsFold applies the ContainsFold predicate on the "config_value" field.
func ConfigValueContainsFold(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldContainsFold(FieldConfigValue, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.FieldContainsFold(FieldDescription, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MerchantConfig) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MerchantConfig) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MerchantConfig) predicate.MerchantConfig {
	return predicate.MerchantConfig(sql.NotPredicates(p))
}
