// Code generated by ent, DO NOT EDIT.

package product

import (
	"entgo.io/ent/dialect/sql"
	"gitee.com/meinongyihe/travel-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldTenantID, v))
}

// MerchantID applies equality check predicate on the "merchant_id" field. It's identical to MerchantIDEQ.
func MerchantID(v int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldMerchantID, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCode, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldTitle, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldSlug, v))
}

// Destination applies equality check predicate on the "destination" field. It's identical to DestinationEQ.
func Destination(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDestination, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDescription, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCurrency, v))
}

// MinPrice applies equality check predicate on the "min_price" field. It's identical to MinPriceEQ.
func MinPrice(v int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldMinPrice, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldStatus, v))
}

// Highlights applies equality check predicate on the "highlights" field. It's identical to HighlightsEQ.
func Highlights(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldHighlights, v))
}

// CoverImage applies equality check predicate on the "cover_image" field. It's identical to CoverImageEQ.
func CoverImage(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCoverImage, v))
}

// Images applies equality check predicate on the "images" field. It's identical to ImagesEQ.
func Images(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldImages, v))
}

// VideoURL applies equality check predicate on the "video_url" field. It's identical to VideoURLEQ.
func VideoURL(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldVideoURL, v))
}

// RichContent applies equality check predicate on the "rich_content" field. It's identical to RichContentEQ.
func RichContent(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldRichContent, v))
}

// BookingNotice applies equality check predicate on the "booking_notice" field. It's identical to BookingNoticeEQ.
func BookingNotice(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldBookingNotice, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldTenantID, v))
}

// MerchantIDEQ applies the EQ predicate on the "merchant_id" field.
func MerchantIDEQ(v int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldMerchantID, v))
}

// MerchantIDNEQ applies the NEQ predicate on the "merchant_id" field.
func MerchantIDNEQ(v int64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldMerchantID, v))
}

// MerchantIDIn applies the In predicate on the "merchant_id" field.
func MerchantIDIn(vs ...int64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldMerchantID, vs...))
}

// MerchantIDNotIn applies the NotIn predicate on the "merchant_id" field.
func MerchantIDNotIn(vs ...int64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldMerchantID, vs...))
}

// MerchantIDGT applies the GT predicate on the "merchant_id" field.
func MerchantIDGT(v int64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldMerchantID, v))
}

// MerchantIDGTE applies the GTE predicate on the "merchant_id" field.
func MerchantIDGTE(v int64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldMerchantID, v))
}

// MerchantIDLT applies the LT predicate on the "merchant_id" field.
func MerchantIDLT(v int64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldMerchantID, v))
}

// MerchantIDLTE applies the LTE predicate on the "merchant_id" field.
func MerchantIDLTE(v int64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldMerchantID, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldCode, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldTitle, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugIsNil applies the IsNil predicate on the "slug" field.
func SlugIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldSlug))
}

// SlugNotNil applies the NotNil predicate on the "slug" field.
func SlugNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldSlug))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldSlug, v))
}

// DestinationEQ applies the EQ predicate on the "destination" field.
func DestinationEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDestination, v))
}

// DestinationNEQ applies the NEQ predicate on the "destination" field.
func DestinationNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldDestination, v))
}

// DestinationIn applies the In predicate on the "destination" field.
func DestinationIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldDestination, vs...))
}

// DestinationNotIn applies the NotIn predicate on the "destination" field.
func DestinationNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldDestination, vs...))
}

// DestinationGT applies the GT predicate on the "destination" field.
func DestinationGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldDestination, v))
}

// DestinationGTE applies the GTE predicate on the "destination" field.
func DestinationGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldDestination, v))
}

// DestinationLT applies the LT predicate on the "destination" field.
func DestinationLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldDestination, v))
}

// DestinationLTE applies the LTE predicate on the "destination" field.
func DestinationLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldDestination, v))
}

// DestinationContains applies the Contains predicate on the "destination" field.
func DestinationContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldDestination, v))
}

// DestinationHasPrefix applies the HasPrefix predicate on the "destination" field.
func DestinationHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldDestination, v))
}

// DestinationHasSuffix applies the HasSuffix predicate on the "destination" field.
func DestinationHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldDestination, v))
}

// DestinationIsNil applies the IsNil predicate on the "destination" field.
func DestinationIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldDestination))
}

// DestinationNotNil applies the NotNil predicate on the "destination" field.
func DestinationNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldDestination))
}

// DestinationEqualFold applies the EqualFold predicate on the "destination" field.
func DestinationEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldDestination, v))
}

// DestinationContainsFold applies the ContainsFold predicate on the "destination" field.
func DestinationContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldDestination, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldDescription, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldCurrency, v))
}

// MinPriceEQ applies the EQ predicate on the "min_price" field.
func MinPriceEQ(v int64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldMinPrice, v))
}

// MinPriceNEQ applies the NEQ predicate on the "min_price" field.
func MinPriceNEQ(v int64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldMinPrice, v))
}

// MinPriceIn applies the In predicate on the "min_price" field.
func MinPriceIn(vs ...int64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldMinPrice, vs...))
}

// MinPriceNotIn applies the NotIn predicate on the "min_price" field.
func MinPriceNotIn(vs ...int64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldMinPrice, vs...))
}

// MinPriceGT applies the GT predicate on the "min_price" field.
func MinPriceGT(v int64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldMinPrice, v))
}

// MinPriceGTE applies the GTE predicate on the "min_price" field.
func MinPriceGTE(v int64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldMinPrice, v))
}

// MinPriceLT applies the LT predicate on the "min_price" field.
func MinPriceLT(v int64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldMinPrice, v))
}

// MinPriceLTE applies the LTE predicate on the "min_price" field.
func MinPriceLTE(v int64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldMinPrice, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldStatus, v))
}

// HighlightsEQ applies the EQ predicate on the "highlights" field.
func HighlightsEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldHighlights, v))
}

// HighlightsNEQ applies the NEQ predicate on the "highlights" field.
func HighlightsNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldHighlights, v))
}

// HighlightsIn applies the In predicate on the "highlights" field.
func HighlightsIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldHighlights, vs...))
}

// HighlightsNotIn applies the NotIn predicate on the "highlights" field.
func HighlightsNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldHighlights, vs...))
}

// HighlightsGT applies the GT predicate on the "highlights" field.
func HighlightsGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldHighlights, v))
}

// HighlightsGTE applies the GTE predicate on the "highlights" field.
func HighlightsGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldHighlights, v))
}

// HighlightsLT applies the LT predicate on the "highlights" field.
func HighlightsLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldHighlights, v))
}

// HighlightsLTE applies the LTE predicate on the "highlights" field.
func HighlightsLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldHighlights, v))
}

// HighlightsContains applies the Contains predicate on the "highlights" field.
func HighlightsContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldHighlights, v))
}

// HighlightsHasPrefix applies the HasPrefix predicate on the "highlights" field.
func HighlightsHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldHighlights, v))
}

// HighlightsHasSuffix applies the HasSuffix predicate on the "highlights" field.
func HighlightsHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldHighlights, v))
}

// HighlightsIsNil applies the IsNil predicate on the "highlights" field.
func HighlightsIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldHighlights))
}

// HighlightsNotNil applies the NotNil predicate on the "highlights" field.
func HighlightsNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldHighlights))
}

// HighlightsEqualFold applies the EqualFold predicate on the "highlights" field.
func HighlightsEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldHighlights, v))
}

// HighlightsContainsFold applies the ContainsFold predicate on the "highlights" field.
func HighlightsContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldHighlights, v))
}

// CoverImageEQ applies the EQ predicate on the "cover_image" field.
func CoverImageEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCoverImage, v))
}

// CoverImageNEQ applies the NEQ predicate on the "cover_image" field.
func CoverImageNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldCoverImage, v))
}

// CoverImageIn applies the In predicate on the "cover_image" field.
func CoverImageIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldCoverImage, vs...))
}

// CoverImageNotIn applies the NotIn predicate on the "cover_image" field.
func CoverImageNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldCoverImage, vs...))
}

// CoverImageGT applies the GT predicate on the "cover_image" field.
func CoverImageGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldCoverImage, v))
}

// CoverImageGTE applies the GTE predicate on the "cover_image" field.
func CoverImageGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldCoverImage, v))
}

// CoverImageLT applies the LT predicate on the "cover_image" field.
func CoverImageLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldCoverImage, v))
}

// CoverImageLTE applies the LTE predicate on the "cover_image" field.
func CoverImageLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldCoverImage, v))
}

// CoverImageContains applies the Contains predicate on the "cover_image" field.
func CoverImageContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldCoverImage, v))
}

// CoverImageHasPrefix applies the HasPrefix predicate on the "cover_image" field.
func CoverImageHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldCoverImage, v))
}

// CoverImageHasSuffix applies the HasSuffix predicate on the "cover_image" field.
func CoverImageHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldCoverImage, v))
}

// CoverImageIsNil applies the IsNil predicate on the "cover_image" field.
func CoverImageIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldCoverImage))
}

// CoverImageNotNil applies the NotNil predicate on the "cover_image" field.
func CoverImageNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldCoverImage))
}

// CoverImageEqualFold applies the EqualFold predicate on the "cover_image" field.
func CoverImageEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldCoverImage, v))
}

// CoverImageContainsFold applies the ContainsFold predicate on the "cover_image" field.
func CoverImageContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldCoverImage, v))
}

// ImagesEQ applies the EQ predicate on the "images" field.
func ImagesEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldImages, v))
}

// ImagesNEQ applies the NEQ predicate on the "images" field.
func ImagesNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldImages, v))
}

// ImagesIn applies the In predicate on the "images" field.
func ImagesIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldImages, vs...))
}

// ImagesNotIn applies the NotIn predicate on the "images" field.
func ImagesNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldImages, vs...))
}

// ImagesGT applies the GT predicate on the "images" field.
func ImagesGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldImages, v))
}

// ImagesGTE applies the GTE predicate on the "images" field.
func ImagesGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldImages, v))
}

// ImagesLT applies the LT predicate on the "images" field.
func ImagesLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldImages, v))
}

// ImagesLTE applies the LTE predicate on the "images" field.
func ImagesLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldImages, v))
}

// ImagesContains applies the Contains predicate on the "images" field.
func ImagesContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldImages, v))
}

// ImagesHasPrefix applies the HasPrefix predicate on the "images" field.
func ImagesHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldImages, v))
}

// ImagesHasSuffix applies the HasSuffix predicate on the "images" field.
func ImagesHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldImages, v))
}

// ImagesIsNil applies the IsNil predicate on the "images" field.
func ImagesIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldImages))
}

// ImagesNotNil applies the NotNil predicate on the "images" field.
func ImagesNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldImages))
}

// ImagesEqualFold applies the EqualFold predicate on the "images" field.
func ImagesEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldImages, v))
}

// ImagesContainsFold applies the ContainsFold predicate on the "images" field.
func ImagesContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldImages, v))
}

// VideoURLEQ applies the EQ predicate on the "video_url" field.
func VideoURLEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldVideoURL, v))
}

// VideoURLNEQ applies the NEQ predicate on the "video_url" field.
func VideoURLNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldVideoURL, v))
}

// VideoURLIn applies the In predicate on the "video_url" field.
func VideoURLIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldVideoURL, vs...))
}

// VideoURLNotIn applies the NotIn predicate on the "video_url" field.
func VideoURLNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldVideoURL, vs...))
}

// VideoURLGT applies the GT predicate on the "video_url" field.
func VideoURLGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldVideoURL, v))
}

// VideoURLGTE applies the GTE predicate on the "video_url" field.
func VideoURLGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldVideoURL, v))
}

// VideoURLLT applies the LT predicate on the "video_url" field.
func VideoURLLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldVideoURL, v))
}

// VideoURLLTE applies the LTE predicate on the "video_url" field.
func VideoURLLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldVideoURL, v))
}

// VideoURLContains applies the Contains predicate on the "video_url" field.
func VideoURLContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldVideoURL, v))
}

// VideoURLHasPrefix applies the HasPrefix predicate on the "video_url" field.
func VideoURLHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldVideoURL, v))
}

// VideoURLHasSuffix applies the HasSuffix predicate on the "video_url" field.
func VideoURLHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldVideoURL, v))
}

// VideoURLIsNil applies the IsNil predicate on the "video_url" field.
func VideoURLIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldVideoURL))
}

// VideoURLNotNil applies the NotNil predicate on the "video_url" field.
func VideoURLNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldVideoURL))
}

// VideoURLEqualFold applies the EqualFold predicate on the "video_url" field.
func VideoURLEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldVideoURL, v))
}

// VideoURLContainsFold applies the ContainsFold predicate on the "video_url" field.
func VideoURLContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldVideoURL, v))
}

// RichContentEQ applies the EQ predicate on the "rich_content" field.
func RichContentEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldRichContent, v))
}

// RichContentNEQ applies the NEQ predicate on the "rich_content" field.
func RichContentNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldRichContent, v))
}

// RichContentIn applies the In predicate on the "rich_content" field.
func RichContentIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldRichContent, vs...))
}

// RichContentNotIn applies the NotIn predicate on the "rich_content" field.
func RichContentNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldRichContent, vs...))
}

// RichContentGT applies the GT predicate on the "rich_content" field.
func RichContentGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldRichContent, v))
}

// RichContentGTE applies the GTE predicate on the "rich_content" field.
func RichContentGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldRichContent, v))
}

// RichContentLT applies the LT predicate on the "rich_content" field.
func RichContentLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldRichContent, v))
}

// RichContentLTE applies the LTE predicate on the "rich_content" field.
func RichContentLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldRichContent, v))
}

// RichContentContains applies the Contains predicate on the "rich_content" field.
func RichContentContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldRichContent, v))
}

// RichContentHasPrefix applies the HasPrefix predicate on the "rich_content" field.
func RichContentHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldRichContent, v))
}

// RichContentHasSuffix applies the HasSuffix predicate on the "rich_content" field.
func RichContentHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldRichContent, v))
}

// RichContentIsNil applies the IsNil predicate on the "rich_content" field.
func RichContentIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldRichContent))
}

// RichContentNotNil applies the NotNil predicate on the "rich_content" field.
func RichContentNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldRichContent))
}

// RichContentEqualFold applies the EqualFold predicate on the "rich_content" field.
func RichContentEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldRichContent, v))
}

// RichContentContainsFold applies the ContainsFold predicate on the "rich_content" field.
func RichContentContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldRichContent, v))
}

// BookingNoticeEQ applies the EQ predicate on the "booking_notice" field.
func BookingNoticeEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldBookingNotice, v))
}

// BookingNoticeNEQ applies the NEQ predicate on the "booking_notice" field.
func BookingNoticeNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldBookingNotice, v))
}

// BookingNoticeIn applies the In predicate on the "booking_notice" field.
func BookingNoticeIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldBookingNotice, vs...))
}

// BookingNoticeNotIn applies the NotIn predicate on the "booking_notice" field.
func BookingNoticeNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldBookingNotice, vs...))
}

// BookingNoticeGT applies the GT predicate on the "booking_notice" field.
func BookingNoticeGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldBookingNotice, v))
}

// BookingNoticeGTE applies the GTE predicate on the "booking_notice" field.
func BookingNoticeGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldBookingNotice, v))
}

// BookingNoticeLT applies the LT predicate on the "booking_notice" field.
func BookingNoticeLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldBookingNotice, v))
}

// BookingNoticeLTE applies the LTE predicate on the "booking_notice" field.
func BookingNoticeLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldBookingNotice, v))
}

// BookingNoticeContains applies the Contains predicate on the "booking_notice" field.
func BookingNoticeContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldBookingNotice, v))
}

// BookingNoticeHasPrefix applies the HasPrefix predicate on the "booking_notice" field.
func BookingNoticeHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldBookingNotice, v))
}

// BookingNoticeHasSuffix applies the HasSuffix predicate on the "booking_notice" field.
func BookingNoticeHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldBookingNotice, v))
}

// BookingNoticeIsNil applies the IsNil predicate on the "booking_notice" field.
func BookingNoticeIsNil() predicate.Product {
	return predicate.Product(sql.FieldIsNull(FieldBookingNotice))
}

// BookingNoticeNotNil applies the NotNil predicate on the "booking_notice" field.
func BookingNoticeNotNil() predicate.Product {
	return predicate.Product(sql.FieldNotNull(FieldBookingNotice))
}

// BookingNoticeEqualFold applies the EqualFold predicate on the "booking_notice" field.
func BookingNoticeEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldBookingNotice, v))
}

// BookingNoticeContainsFold applies the ContainsFold predicate on the "booking_notice" field.
func BookingNoticeContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldBookingNotice, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Product) predicate.Product {
	return predicate.Product(sql.NotPredicates(p))
}
