// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/meinongyihe/travel-rpc/ent/exchangerate"
)

// ExchangeRateCreate is the builder for creating a ExchangeRate entity.
type ExchangeRateCreate struct {
	config
	mutation *ExchangeRateMutation
	hooks    []Hook
}

// SetBaseCurrency sets the "base_currency" field.
func (_c *ExchangeRateCreate) SetBaseCurrency(v string) *ExchangeRateCreate {
	_c.mutation.SetBaseCurrency(v)
	return _c
}

// SetNillableBaseCurrency sets the "base_currency" field if the given value is not nil.
func (_c *ExchangeRateCreate) SetNillableBaseCurrency(v *string) *ExchangeRateCreate {
	if v != nil {
		_c.SetBaseCurrency(*v)
	}
	return _c
}

// SetTargetCurrency sets the "target_currency" field.
func (_c *ExchangeRateCreate) SetTargetCurrency(v string) *ExchangeRateCreate {
	_c.mutation.SetTargetCurrency(v)
	return _c
}

// SetRateMicro sets the "rate_micro" field.
func (_c *ExchangeRateCreate) SetRateMicro(v int64) *ExchangeRateCreate {
	_c.mutation.SetRateMicro(v)
	return _c
}

// SetNillableRateMicro sets the "rate_micro" field if the given value is not nil.
func (_c *ExchangeRateCreate) SetNillableRateMicro(v *int64) *ExchangeRateCreate {
	if v != nil {
		_c.SetRateMicro(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *ExchangeRateCreate) SetSource(v string) *ExchangeRateCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *ExchangeRateCreate) SetNillableSource(v *string) *ExchangeRateCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetEffectiveAt sets the "effective_at" field.
func (_c *ExchangeRateCreate) SetEffectiveAt(v int64) *ExchangeRateCreate {
	_c.mutation.SetEffectiveAt(v)
	return _c
}

// SetNillableEffectiveAt sets the "effective_at" field if the given value is not nil.
func (_c *ExchangeRateCreate) SetNillableEffectiveAt(v *int64) *ExchangeRateCreate {
	if v != nil {
		_c.SetEffectiveAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ExchangeRateCreate) SetStatus(v string) *ExchangeRateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ExchangeRateCreate) SetNillableStatus(v *string) *ExchangeRateCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// Mutation returns the ExchangeRateMutation object of the builder.
func (_c *ExchangeRateCreate) Mutation() *ExchangeRateMutation {
	return _c.mutation
}

// Save creates the ExchangeRate in the database.
func (_c *ExchangeRateCreate) Save(ctx context.Context) (*ExchangeRate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExchangeRateCreate) SaveX(ctx context.Context) *ExchangeRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeRateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeRateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExchangeRateCreate) defaults() {
	if _, ok := _c.mutation.BaseCurrency(); !ok {
		v := exchangerate.DefaultBaseCurrency
		_c.mutation.SetBaseCurrency(v)
	}
	if _, ok := _c.mutation.RateMicro(); !ok {
		v := exchangerate.DefaultRateMicro
		_c.mutation.SetRateMicro(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := exchangerate.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.EffectiveAt(); !ok {
		v := exchangerate.DefaultEffectiveAt
		_c.mutation.SetEffectiveAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := exchangerate.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExchangeRateCreate) check() error {
	if _, ok := _c.mutation.BaseCurrency(); !ok {
		return &ValidationError{Name: "base_currency", err: errors.New(`ent: missing required field "ExchangeRate.base_currency"`)}
	}
	if v, ok := _c.mutation.BaseCurrency(); ok {
		if err := exchangerate.BaseCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "base_currency", err: fmt.Errorf(`ent: validator failed for field "ExchangeRate.base_currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetCurrency(); !ok {
		return &ValidationError{Name: "target_currency", err: errors.New(`ent: missing required field "ExchangeRate.target_currency"`)}
	}
	if v, ok := _c.mutation.TargetCurrency(); ok {
		if err := exchangerate.TargetCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "target_currency", err: fmt.Errorf(`ent: validator failed for field "ExchangeRate.target_currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateMicro(); !ok {
		return &ValidationError{Name: "rate_micro", err: errors.New(`ent: missing required field "ExchangeRate.rate_micro"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "ExchangeRate.source"`)}
	}
	if _, ok := _c.mutation.EffectiveAt(); !ok {
		return &ValidationError{Name: "effective_at", err: errors.New(`ent: missing required field "ExchangeRate.effective_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ExchangeRate.status"`)}
	}
	return nil
}

func (_c *ExchangeRateCreate) sqlSave(ctx context.Context) (*ExchangeRate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExchangeRateCreate) createSpec() (*ExchangeRate, *sqlgraph.CreateSpec) {
	var (
		_node = &ExchangeRate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exchangerate.Table, sqlgraph.NewFieldSpec(exchangerate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.BaseCurrency(); ok {
		_spec.SetField(exchangerate.FieldBaseCurrency, field.TypeString, value)
		_node.BaseCurrency = value
	}
	if value, ok := _c.mutation.TargetCurrency(); ok {
		_spec.SetField(exchangerate.FieldTargetCurrency, field.TypeString, value)
		_node.TargetCurrency = value
	}
	if value, ok := _c.mutation.RateMicro(); ok {
		_spec.SetField(exchangerate.FieldRateMicro, field.TypeInt64, value)
		_node.RateMicro = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(exchangerate.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.EffectiveAt(); ok {
		_spec.SetField(exchangerate.FieldEffectiveAt, field.TypeInt64, value)
		_node.EffectiveAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(exchangerate.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	return _node, _spec
}

// ExchangeRateCreateBulk is the builder for creating many ExchangeRate entities in bulk.
type ExchangeRateCreateBulk struct {
	config
	err      error
	builders []*ExchangeRateCreate
}

// Save creates the ExchangeRate entities in the database.
func (_c *ExchangeRateCreateBulk) Save(ctx context.Context) ([]*ExchangeRate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExchangeRate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExchangeRateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExchangeRateCreateBulk) SaveX(ctx context.Context) []*ExchangeRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeRateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeRateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
