// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/meinongyihe/travel-rpc/ent/inventory"
)

// InventoryCreate is the builder for creating a Inventory entity.
type InventoryCreate struct {
	config
	mutation *InventoryMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *InventoryCreate) SetTenantID(v int64) *InventoryCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetMerchantID sets the "merchant_id" field.
func (_c *InventoryCreate) SetMerchantID(v int64) *InventoryCreate {
	_c.mutation.SetMerchantID(v)
	return _c
}

// SetPackageID sets the "package_id" field.
func (_c *InventoryCreate) SetPackageID(v int64) *InventoryCreate {
	_c.mutation.SetPackageID(v)
	return _c
}

// SetServiceDate sets the "service_date" field.
func (_c *InventoryCreate) SetServiceDate(v string) *InventoryCreate {
	_c.mutation.SetServiceDate(v)
	return _c
}

// SetTimeSlot sets the "time_slot" field.
func (_c *InventoryCreate) SetTimeSlot(v string) *InventoryCreate {
	_c.mutation.SetTimeSlot(v)
	return _c
}

// SetNillableTimeSlot sets the "time_slot" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableTimeSlot(v *string) *InventoryCreate {
	if v != nil {
		_c.SetTimeSlot(*v)
	}
	return _c
}

// SetCapacity sets the "capacity" field.
func (_c *InventoryCreate) SetCapacity(v int) *InventoryCreate {
	_c.mutation.SetCapacity(v)
	return _c
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableCapacity(v *int) *InventoryCreate {
	if v != nil {
		_c.SetCapacity(*v)
	}
	return _c
}

// SetReserved sets the "reserved" field.
func (_c *InventoryCreate) SetReserved(v int) *InventoryCreate {
	_c.mutation.SetReserved(v)
	return _c
}

// SetNillableReserved sets the "reserved" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableReserved(v *int) *InventoryCreate {
	if v != nil {
		_c.SetReserved(*v)
	}
	return _c
}

// SetUnitPrice sets the "unit_price" field.
func (_c *InventoryCreate) SetUnitPrice(v int64) *InventoryCreate {
	_c.mutation.SetUnitPrice(v)
	return _c
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableUnitPrice(v *int64) *InventoryCreate {
	if v != nil {
		_c.SetUnitPrice(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *InventoryCreate) SetCurrency(v string) *InventoryCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableCurrency(v *string) *InventoryCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InventoryCreate) SetStatus(v string) *InventoryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableStatus(v *string) *InventoryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetInventoryMode sets the "inventory_mode" field.
func (_c *InventoryCreate) SetInventoryMode(v string) *InventoryCreate {
	_c.mutation.SetInventoryMode(v)
	return _c
}

// SetNillableInventoryMode sets the "inventory_mode" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableInventoryMode(v *string) *InventoryCreate {
	if v != nil {
		_c.SetInventoryMode(*v)
	}
	return _c
}

// SetTotalCapacity sets the "total_capacity" field.
func (_c *InventoryCreate) SetTotalCapacity(v int) *InventoryCreate {
	_c.mutation.SetTotalCapacity(v)
	return _c
}

// SetNillableTotalCapacity sets the "total_capacity" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableTotalCapacity(v *int) *InventoryCreate {
	if v != nil {
		_c.SetTotalCapacity(*v)
	}
	return _c
}

// SetIsOpen sets the "is_open" field.
func (_c *InventoryCreate) SetIsOpen(v bool) *InventoryCreate {
	_c.mutation.SetIsOpen(v)
	return _c
}

// SetNillableIsOpen sets the "is_open" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableIsOpen(v *bool) *InventoryCreate {
	if v != nil {
		_c.SetIsOpen(*v)
	}
	return _c
}

// Mutation returns the InventoryMutation object of the builder.
func (_c *InventoryCreate) Mutation() *InventoryMutation {
	return _c.mutation
}

// Save creates the Inventory in the database.
func (_c *InventoryCreate) Save(ctx context.Context) (*Inventory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InventoryCreate) SaveX(ctx context.Context) *Inventory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InventoryCreate) defaults() {
	if _, ok := _c.mutation.Capacity(); !ok {
		v := inventory.DefaultCapacity
		_c.mutation.SetCapacity(v)
	}
	if _, ok := _c.mutation.Reserved(); !ok {
		v := inventory.DefaultReserved
		_c.mutation.SetReserved(v)
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		v := inventory.DefaultUnitPrice
		_c.mutation.SetUnitPrice(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := inventory.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := inventory.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.InventoryMode(); !ok {
		v := inventory.DefaultInventoryMode
		_c.mutation.SetInventoryMode(v)
	}
	if _, ok := _c.mutation.IsOpen(); !ok {
		v := inventory.DefaultIsOpen
		_c.mutation.SetIsOpen(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InventoryCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Inventory.tenant_id"`)}
	}
	if _, ok := _c.mutation.MerchantID(); !ok {
		return &ValidationError{Name: "merchant_id", err: errors.New(`ent: missing required field "Inventory.merchant_id"`)}
	}
	if _, ok := _c.mutation.PackageID(); !ok {
		return &ValidationError{Name: "package_id", err: errors.New(`ent: missing required field "Inventory.package_id"`)}
	}
	if _, ok := _c.mutation.ServiceDate(); !ok {
		return &ValidationError{Name: "service_date", err: errors.New(`ent: missing required field "Inventory.service_date"`)}
	}
	if _, ok := _c.mutation.Capacity(); !ok {
		return &ValidationError{Name: "capacity", err: errors.New(`ent: missing required field "Inventory.capacity"`)}
	}
	if _, ok := _c.mutation.Reserved(); !ok {
		return &ValidationError{Name: "reserved", err: errors.New(`ent: missing required field "Inventory.reserved"`)}
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		return &ValidationError{Name: "unit_price", err: errors.New(`ent: missing required field "Inventory.unit_price"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Inventory.currency"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Inventory.status"`)}
	}
	if _, ok := _c.mutation.InventoryMode(); !ok {
		return &ValidationError{Name: "inventory_mode", err: errors.New(`ent: missing required field "Inventory.inventory_mode"`)}
	}
	if _, ok := _c.mutation.IsOpen(); !ok {
		return &ValidationError{Name: "is_open", err: errors.New(`ent: missing required field "Inventory.is_open"`)}
	}
	return nil
}

func (_c *InventoryCreate) sqlSave(ctx context.Context) (*Inventory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InventoryCreate) createSpec() (*Inventory, *sqlgraph.CreateSpec) {
	var (
		_node = &Inventory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inventory.Table, sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(inventory.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.MerchantID(); ok {
		_spec.SetField(inventory.FieldMerchantID, field.TypeInt64, value)
		_node.MerchantID = value
	}
	if value, ok := _c.mutation.PackageID(); ok {
		_spec.SetField(inventory.FieldPackageID, field.TypeInt64, value)
		_node.PackageID = value
	}
	if value, ok := _c.mutation.ServiceDate(); ok {
		_spec.SetField(inventory.FieldServiceDate, field.TypeString, value)
		_node.ServiceDate = value
	}
	if value, ok := _c.mutation.TimeSlot(); ok {
		_spec.SetField(inventory.FieldTimeSlot, field.TypeString, value)
		_node.TimeSlot = value
	}
	if value, ok := _c.mutation.Capacity(); ok {
		_spec.SetField(inventory.FieldCapacity, field.TypeInt, value)
		_node.Capacity = value
	}
	if value, ok := _c.mutation.Reserved(); ok {
		_spec.SetField(inventory.FieldReserved, field.TypeInt, value)
		_node.Reserved = value
	}
	if value, ok := _c.mutation.UnitPrice(); ok {
		_spec.SetField(inventory.FieldUnitPrice, field.TypeInt64, value)
		_node.UnitPrice = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(inventory.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(inventory.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.InventoryMode(); ok {
		_spec.SetField(inventory.FieldInventoryMode, field.TypeString, value)
		_node.InventoryMode = value
	}
	if value, ok := _c.mutation.TotalCapacity(); ok {
		_spec.SetField(inventory.FieldTotalCapacity, field.TypeInt, value)
		_node.TotalCapacity = value
	}
	if value, ok := _c.mutation.IsOpen(); ok {
		_spec.SetField(inventory.FieldIsOpen, field.TypeBool, value)
		_node.IsOpen = value
	}
	return _node, _spec
}

// InventoryCreateBulk is the builder for creating many Inventory entities in bulk.
type InventoryCreateBulk struct {
	config
	err      error
	builders []*InventoryCreate
}

// Save creates the Inventory entities in the database.
func (_c *InventoryCreateBulk) Save(ctx context.Context) ([]*Inventory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Inventory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InventoryCreateBulk) SaveX(ctx context.Context) []*Inventory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
