// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/meinongyihe/travel-rpc/ent/inventoryreservation"
)

// InventoryReservationCreate is the builder for creating a InventoryReservation entity.
type InventoryReservationCreate struct {
	config
	mutation *InventoryReservationMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *InventoryReservationCreate) SetTenantID(v int64) *InventoryReservationCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetMerchantID sets the "merchant_id" field.
func (_c *InventoryReservationCreate) SetMerchantID(v int64) *InventoryReservationCreate {
	_c.mutation.SetMerchantID(v)
	return _c
}

// SetInventoryID sets the "inventory_id" field.
func (_c *InventoryReservationCreate) SetInventoryID(v int64) *InventoryReservationCreate {
	_c.mutation.SetInventoryID(v)
	return _c
}

// SetReservationKey sets the "reservation_key" field.
func (_c *InventoryReservationCreate) SetReservationKey(v string) *InventoryReservationCreate {
	_c.mutation.SetReservationKey(v)
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *InventoryReservationCreate) SetQuantity(v int) *InventoryReservationCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *InventoryReservationCreate) SetOrderID(v int64) *InventoryReservationCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_c *InventoryReservationCreate) SetNillableOrderID(v *int64) *InventoryReservationCreate {
	if v != nil {
		_c.SetOrderID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InventoryReservationCreate) SetStatus(v string) *InventoryReservationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InventoryReservationCreate) SetNillableStatus(v *string) *InventoryReservationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *InventoryReservationCreate) SetExpiresAt(v time.Time) *InventoryReservationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *InventoryReservationCreate) SetNillableExpiresAt(v *time.Time) *InventoryReservationCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InventoryReservationCreate) SetCreatedAt(v time.Time) *InventoryReservationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InventoryReservationCreate) SetNillableCreatedAt(v *time.Time) *InventoryReservationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InventoryReservationCreate) SetUpdatedAt(v time.Time) *InventoryReservationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InventoryReservationCreate) SetNillableUpdatedAt(v *time.Time) *InventoryReservationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the InventoryReservationMutation object of the builder.
func (_c *InventoryReservationCreate) Mutation() *InventoryReservationMutation {
	return _c.mutation
}

// Save creates the InventoryReservation in the database.
func (_c *InventoryReservationCreate) Save(ctx context.Context) (*InventoryReservation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InventoryReservationCreate) SaveX(ctx context.Context) *InventoryReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryReservationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryReservationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InventoryReservationCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := inventoryreservation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		v := inventoryreservation.DefaultExpiresAt()
		_c.mutation.SetExpiresAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := inventoryreservation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := inventoryreservation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InventoryReservationCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "InventoryReservation.tenant_id"`)}
	}
	if _, ok := _c.mutation.MerchantID(); !ok {
		return &ValidationError{Name: "merchant_id", err: errors.New(`ent: missing required field "InventoryReservation.merchant_id"`)}
	}
	if _, ok := _c.mutation.InventoryID(); !ok {
		return &ValidationError{Name: "inventory_id", err: errors.New(`ent: missing required field "InventoryReservation.inventory_id"`)}
	}
	if _, ok := _c.mutation.ReservationKey(); !ok {
		return &ValidationError{Name: "reservation_key", err: errors.New(`ent: missing required field "InventoryReservation.reservation_key"`)}
	}
	if v, ok := _c.mutation.ReservationKey(); ok {
		if err := inventoryreservation.ReservationKeyValidator(v); err != nil {
			return &ValidationError{Name: "reservation_key", err: fmt.Errorf(`ent: validator failed for field "InventoryReservation.reservation_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "InventoryReservation.quantity"`)}
	}
	if v, ok := _c.mutation.Quantity(); ok {
		if err := inventoryreservation.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "InventoryReservation.quantity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InventoryReservation.status"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "InventoryReservation.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InventoryReservation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InventoryReservation.updated_at"`)}
	}
	return nil
}

func (_c *InventoryReservationCreate) sqlSave(ctx context.Context) (*InventoryReservation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InventoryReservationCreate) createSpec() (*InventoryReservation, *sqlgraph.CreateSpec) {
	var (
		_node = &InventoryReservation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inventoryreservation.Table, sqlgraph.NewFieldSpec(inventoryreservation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(inventoryreservation.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.MerchantID(); ok {
		_spec.SetField(inventoryreservation.FieldMerchantID, field.TypeInt64, value)
		_node.MerchantID = value
	}
	if value, ok := _c.mutation.InventoryID(); ok {
		_spec.SetField(inventoryreservation.FieldInventoryID, field.TypeInt64, value)
		_node.InventoryID = value
	}
	if value, ok := _c.mutation.ReservationKey(); ok {
		_spec.SetField(inventoryreservation.FieldReservationKey, field.TypeString, value)
		_node.ReservationKey = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(inventoryreservation.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(inventoryreservation.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(inventoryreservation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(inventoryreservation.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(inventoryreservation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(inventoryreservation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// InventoryReservationCreateBulk is the builder for creating many InventoryReservation entities in bulk.
type InventoryReservationCreateBulk struct {
	config
	err      error
	builders []*InventoryReservationCreate
}

// Save creates the InventoryReservation entities in the database.
func (_c *InventoryReservationCreateBulk) Save(ctx context.Context) ([]*InventoryReservation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InventoryReservation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventoryReservationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InventoryReservationCreateBulk) SaveX(ctx context.Context) []*InventoryReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryReservationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryReservationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
