// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/meinongyihe/travel-rpc/ent/merchantconfig"
)

// MerchantConfigCreate is the builder for creating a MerchantConfig entity.
type MerchantConfigCreate struct {
	config
	mutation *MerchantConfigMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *MerchantConfigCreate) SetTenantID(v int64) *MerchantConfigCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *MerchantConfigCreate) SetNillableTenantID(v *int64) *MerchantConfigCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetMerchantID sets the "merchant_id" field.
func (_c *MerchantConfigCreate) SetMerchantID(v int64) *MerchantConfigCreate {
	_c.mutation.SetMerchantID(v)
	return _c
}

// SetNillableMerchantID sets the "merchant_id" field if the given value is not nil.
func (_c *MerchantConfigCreate) SetNillableMerchantID(v *int64) *MerchantConfigCreate {
	if v != nil {
		_c.SetMerchantID(*v)
	}
	return _c
}

// SetConfigType sets the "config_type" field.
func (_c *MerchantConfigCreate) SetConfigType(v string) *MerchantConfigCreate {
	_c.mutation.SetConfigType(v)
	return _c
}

// SetConfigKey sets the "config_key" field.
func (_c *MerchantConfigCreate) SetConfigKey(v string) *MerchantConfigCreate {
	_c.mutation.SetConfigKey(v)
	return _c
}

// SetConfigValue sets the "config_value" field.
func (_c *MerchantConfigCreate) SetConfigValue(v string) *MerchantConfigCreate {
	_c.mutation.SetConfigValue(v)
	return _c
}

// SetNillableConfigValue sets the "config_value" field if the given value is not nil.
func (_c *MerchantConfigCreate) SetNillableConfigValue(v *string) *MerchantConfigCreate {
	if v != nil {
		_c.SetConfigValue(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *MerchantConfigCreate) SetDescription(v string) *MerchantConfigCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MerchantConfigCreate) SetNillableDescription(v *string) *MerchantConfigCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// Mutation returns the MerchantConfigMutation object of the builder.
func (_c *MerchantConfigCreate) Mutation() *MerchantConfigMutation {
	return _c.mutation
}

// Save creates the MerchantConfig in the database.
func (_c *MerchantConfigCreate) Save(ctx context.Context) (*MerchantConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MerchantConfigCreate) SaveX(ctx context.Context) *MerchantConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MerchantConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MerchantConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MerchantConfigCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := merchantconfig.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.MerchantID(); !ok {
		v := merchantconfig.DefaultMerchantID
		_c.mutation.SetMerchantID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MerchantConfigCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "MerchantConfig.tenant_id"`)}
	}
	if _, ok := _c.mutation.MerchantID(); !ok {
		return &ValidationError{Name: "merchant_id", err: errors.New(`ent: missing required field "MerchantConfig.merchant_id"`)}
	}
	if _, ok := _c.mutation.ConfigType(); !ok {
		return &ValidationError{Name: "config_type", err: errors.New(`ent: missing required field "MerchantConfig.config_type"`)}
	}
	if v, ok := _c.mutation.ConfigType(); ok {
		if err := merchantconfig.ConfigTypeValidator(v); err != nil {
			return &ValidationError{Name: "config_type", err: fmt.Errorf(`ent: validator failed for field "MerchantConfig.config_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConfigKey(); !ok {
		return &ValidationError{Name: "config_key", err: errors.New(`ent: missing required field "MerchantConfig.config_key"`)}
	}
	if v, ok := _c.mutation.ConfigKey(); ok {
		if err := merchantconfig.ConfigKeyValidator(v); err != nil {
			return &ValidationError{Name: "config_key", err: fmt.Errorf(`ent: validator failed for field "MerchantConfig.config_key": %w`, err)}
		}
	}
	return nil
}

func (_c *MerchantConfigCreate) sqlSave(ctx context.Context) (*MerchantConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MerchantConfigCreate) createSpec() (*MerchantConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &MerchantConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(merchantconfig.Table, sqlgraph.NewFieldSpec(merchantconfig.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(merchantconfig.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.MerchantID(); ok {
		_spec.SetField(merchantconfig.FieldMerchantID, field.TypeInt64, value)
		_node.MerchantID = value
	}
	if value, ok := _c.mutation.ConfigType(); ok {
		_spec.SetField(merchantconfig.FieldConfigType, field.TypeString, value)
		_node.ConfigType = value
	}
	if value, ok := _c.mutation.ConfigKey(); ok {
		_spec.SetField(merchantconfig.FieldConfigKey, field.TypeString, value)
		_node.ConfigKey = value
	}
	if value, ok := _c.mutation.ConfigValue(); ok {
		_spec.SetField(merchantconfig.FieldConfigValue, field.TypeString, value)
		_node.ConfigValue = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(merchantconfig.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	return _node, _spec
}

// MerchantConfigCreateBulk is the builder for creating many MerchantConfig entities in bulk.
type MerchantConfigCreateBulk struct {
	config
	err      error
	builders []*MerchantConfigCreate
}

// Save creates the MerchantConfig entities in the database.
func (_c *MerchantConfigCreateBulk) Save(ctx context.Context) ([]*MerchantConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MerchantConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MerchantConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MerchantConfigCreateBulk) SaveX(ctx context.Context) []*MerchantConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MerchantConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MerchantConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
