// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitee.com/meinongyihe/travel-rpc/ent/merchantconfig"
)

// MerchantConfig is the model entity for the MerchantConfig schema.
type MerchantConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// MerchantID holds the value of the "merchant_id" field.
	MerchantID int64 `json:"merchant_id,omitempty"`
	// ConfigType holds the value of the "config_type" field.
	ConfigType string `json:"config_type,omitempty"`
	// ConfigKey holds the value of the "config_key" field.
	ConfigKey string `json:"config_key,omitempty"`
	// ConfigValue holds the value of the "config_value" field.
	ConfigValue string `json:"config_value,omitempty"`
	// Description holds the value of the "description" field.
	Description  string `json:"description,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MerchantConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case merchantconfig.FieldID, merchantconfig.FieldTenantID, merchantconfig.FieldMerchantID:
			values[i] = new(sql.NullInt64)
		case merchantconfig.FieldConfigType, merchantconfig.FieldConfigKey, merchantconfig.FieldConfigValue, merchantconfig.FieldDescription:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MerchantConfig fields.
func (_m *MerchantConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case merchantconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case merchantconfig.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.Int64
			}
		case merchantconfig.FieldMerchantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field merchant_id", values[i])
			} else if value.Valid {
				_m.MerchantID = value.Int64
			}
		case merchantconfig.FieldConfigType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_type", values[i])
			} else if value.Valid {
				_m.ConfigType = value.String
			}
		case merchantconfig.FieldConfigKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_key", values[i])
			} else if value.Valid {
				_m.ConfigKey = value.String
			}
		case merchantconfig.FieldConfigValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_value", values[i])
			} else if value.Valid {
				_m.ConfigValue = value.String
			}
		case merchantconfig.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MerchantConfig.
// This includes values selected through modifiers, order, etc.
func (_m *MerchantConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MerchantConfig.
// Note that you need to call MerchantConfig.Unwrap() before calling this method if this MerchantConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MerchantConfig) Update() *MerchantConfigUpdateOne {
	return NewMerchantConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MerchantConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MerchantConfig) Unwrap() *MerchantConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MerchantConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MerchantConfig) String() string {
	var builder strings.Builder
	builder.WriteString("MerchantConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("merchant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MerchantID))
	builder.WriteString(", ")
	builder.WriteString("config_type=")
	builder.WriteString(_m.ConfigType)
	builder.WriteString(", ")
	builder.WriteString("config_key=")
	builder.WriteString(_m.ConfigKey)
	builder.WriteString(", ")
	builder.WriteString("config_value=")
	builder.WriteString(_m.ConfigValue)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// MerchantConfigs is a parsable slice of MerchantConfig.
type MerchantConfigs []*MerchantConfig
