// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/meinongyihe/travel-rpc/ent/product"
)

// ProductCreate is the builder for creating a Product entity.
type ProductCreate struct {
	config
	mutation *ProductMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *ProductCreate) SetTenantID(v int64) *ProductCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetMerchantID sets the "merchant_id" field.
func (_c *ProductCreate) SetMerchantID(v int64) *ProductCreate {
	_c.mutation.SetMerchantID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *ProductCreate) SetCode(v string) *ProductCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ProductCreate) SetTitle(v string) *ProductCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *ProductCreate) SetSlug(v string) *ProductCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_c *ProductCreate) SetNillableSlug(v *string) *ProductCreate {
	if v != nil {
		_c.SetSlug(*v)
	}
	return _c
}

// SetDestination sets the "destination" field.
func (_c *ProductCreate) SetDestination(v string) *ProductCreate {
	_c.mutation.SetDestination(v)
	return _c
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_c *ProductCreate) SetNillableDestination(v *string) *ProductCreate {
	if v != nil {
		_c.SetDestination(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProductCreate) SetDescription(v string) *ProductCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ProductCreate) SetNillableDescription(v *string) *ProductCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ProductCreate) SetCurrency(v string) *ProductCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *ProductCreate) SetNillableCurrency(v *string) *ProductCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetMinPrice sets the "min_price" field.
func (_c *ProductCreate) SetMinPrice(v int64) *ProductCreate {
	_c.mutation.SetMinPrice(v)
	return _c
}

// SetNillableMinPrice sets the "min_price" field if the given value is not nil.
func (_c *ProductCreate) SetNillableMinPrice(v *int64) *ProductCreate {
	if v != nil {
		_c.SetMinPrice(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProductCreate) SetStatus(v string) *ProductCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProductCreate) SetNillableStatus(v *string) *ProductCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetHighlights sets the "highlights" field.
func (_c *ProductCreate) SetHighlights(v string) *ProductCreate {
	_c.mutation.SetHighlights(v)
	return _c
}

// SetNillableHighlights sets the "highlights" field if the given value is not nil.
func (_c *ProductCreate) SetNillableHighlights(v *string) *ProductCreate {
	if v != nil {
		_c.SetHighlights(*v)
	}
	return _c
}

// SetCoverImage sets the "cover_image" field.
func (_c *ProductCreate) SetCoverImage(v string) *ProductCreate {
	_c.mutation.SetCoverImage(v)
	return _c
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_c *ProductCreate) SetNillableCoverImage(v *string) *ProductCreate {
	if v != nil {
		_c.SetCoverImage(*v)
	}
	return _c
}

// SetImages sets the "images" field.
func (_c *ProductCreate) SetImages(v string) *ProductCreate {
	_c.mutation.SetImages(v)
	return _c
}

// SetNillableImages sets the "images" field if the given value is not nil.
func (_c *ProductCreate) SetNillableImages(v *string) *ProductCreate {
	if v != nil {
		_c.SetImages(*v)
	}
	return _c
}

// SetVideoURL sets the "video_url" field.
func (_c *ProductCreate) SetVideoURL(v string) *ProductCreate {
	_c.mutation.SetVideoURL(v)
	return _c
}

// SetNillableVideoURL sets the "video_url" field if the given value is not nil.
func (_c *ProductCreate) SetNillableVideoURL(v *string) *ProductCreate {
	if v != nil {
		_c.SetVideoURL(*v)
	}
	return _c
}

// SetRichContent sets the "rich_content" field.
func (_c *ProductCreate) SetRichContent(v string) *ProductCreate {
	_c.mutation.SetRichContent(v)
	return _c
}

// SetNillableRichContent sets the "rich_content" field if the given value is not nil.
func (_c *ProductCreate) SetNillableRichContent(v *string) *ProductCreate {
	if v != nil {
		_c.SetRichContent(*v)
	}
	return _c
}

// SetBookingNotice sets the "booking_notice" field.
func (_c *ProductCreate) SetBookingNotice(v string) *ProductCreate {
	_c.mutation.SetBookingNotice(v)
	return _c
}

// SetNillableBookingNotice sets the "booking_notice" field if the given value is not nil.
func (_c *ProductCreate) SetNillableBookingNotice(v *string) *ProductCreate {
	if v != nil {
		_c.SetBookingNotice(*v)
	}
	return _c
}

// Mutation returns the ProductMutation object of the builder.
func (_c *ProductCreate) Mutation() *ProductMutation {
	return _c.mutation
}

// Save creates the Product in the database.
func (_c *ProductCreate) Save(ctx context.Context) (*Product, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProductCreate) SaveX(ctx context.Context) *Product {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProductCreate) defaults() {
	if _, ok := _c.mutation.Currency(); !ok {
		v := product.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.MinPrice(); !ok {
		v := product.DefaultMinPrice
		_c.mutation.SetMinPrice(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := product.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProductCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Product.tenant_id"`)}
	}
	if _, ok := _c.mutation.MerchantID(); !ok {
		return &ValidationError{Name: "merchant_id", err: errors.New(`ent: missing required field "Product.merchant_id"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Product.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := product.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Product.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Product.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := product.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Product.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Product.currency"`)}
	}
	if _, ok := _c.mutation.MinPrice(); !ok {
		return &ValidationError{Name: "min_price", err: errors.New(`ent: missing required field "Product.min_price"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Product.status"`)}
	}
	return nil
}

func (_c *ProductCreate) sqlSave(ctx context.Context) (*Product, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProductCreate) createSpec() (*Product, *sqlgraph.CreateSpec) {
	var (
		_node = &Product{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(product.Table, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(product.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.MerchantID(); ok {
		_spec.SetField(product.FieldMerchantID, field.TypeInt64, value)
		_node.MerchantID = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(product.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(product.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Destination(); ok {
		_spec.SetField(product.FieldDestination, field.TypeString, value)
		_node.Destination = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(product.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.MinPrice(); ok {
		_spec.SetField(product.FieldMinPrice, field.TypeInt64, value)
		_node.MinPrice = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(product.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Highlights(); ok {
		_spec.SetField(product.FieldHighlights, field.TypeString, value)
		_node.Highlights = value
	}
	if value, ok := _c.mutation.CoverImage(); ok {
		_spec.SetField(product.FieldCoverImage, field.TypeString, value)
		_node.CoverImage = value
	}
	if value, ok := _c.mutation.Images(); ok {
		_spec.SetField(product.FieldImages, field.TypeString, value)
		_node.Images = value
	}
	if value, ok := _c.mutation.VideoURL(); ok {
		_spec.SetField(product.FieldVideoURL, field.TypeString, value)
		_node.VideoURL = value
	}
	if value, ok := _c.mutation.RichContent(); ok {
		_spec.SetField(product.FieldRichContent, field.TypeString, value)
		_node.RichContent = value
	}
	if value, ok := _c.mutation.BookingNotice(); ok {
		_spec.SetField(product.FieldBookingNotice, field.TypeString, value)
		_node.BookingNotice = value
	}
	return _node, _spec
}

// ProductCreateBulk is the builder for creating many Product entities in bulk.
type ProductCreateBulk struct {
	config
	err      error
	builders []*ProductCreate
}

// Save creates the Product entities in the database.
func (_c *ProductCreateBulk) Save(ctx context.Context) ([]*Product, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Product, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProductCreateBulk) SaveX(ctx context.Context) []*Product {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
