// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/meinongyihe/travel-rpc/ent/predicate"
	"gitee.com/meinongyihe/travel-rpc/ent/productpackage"
)

// ProductPackageUpdate is the builder for updating ProductPackage entities.
type ProductPackageUpdate struct {
	config
	hooks    []Hook
	mutation *ProductPackageMutation
}

// Where appends a list predicates to the ProductPackageUpdate builder.
func (_u *ProductPackageUpdate) Where(ps ...predicate.ProductPackage) *ProductPackageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ProductPackageUpdate) SetTenantID(v int64) *ProductPackageUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableTenantID(v *int64) *ProductPackageUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *ProductPackageUpdate) AddTenantID(v int64) *ProductPackageUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetMerchantID sets the "merchant_id" field.
func (_u *ProductPackageUpdate) SetMerchantID(v int64) *ProductPackageUpdate {
	_u.mutation.ResetMerchantID()
	_u.mutation.SetMerchantID(v)
	return _u
}

// SetNillableMerchantID sets the "merchant_id" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableMerchantID(v *int64) *ProductPackageUpdate {
	if v != nil {
		_u.SetMerchantID(*v)
	}
	return _u
}

// AddMerchantID adds value to the "merchant_id" field.
func (_u *ProductPackageUpdate) AddMerchantID(v int64) *ProductPackageUpdate {
	_u.mutation.AddMerchantID(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ProductPackageUpdate) SetProductID(v int64) *ProductPackageUpdate {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableProductID(v *int64) *ProductPackageUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *ProductPackageUpdate) AddProductID(v int64) *ProductPackageUpdate {
	_u.mutation.AddProductID(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *ProductPackageUpdate) SetCode(v string) *ProductPackageUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableCode(v *string) *ProductPackageUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProductPackageUpdate) SetName(v string) *ProductPackageUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableName(v *string) *ProductPackageUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProductPackageUpdate) SetStatus(v string) *ProductPackageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableStatus(v *string) *ProductPackageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPricingMode sets the "pricing_mode" field.
func (_u *ProductPackageUpdate) SetPricingMode(v string) *ProductPackageUpdate {
	_u.mutation.SetPricingMode(v)
	return _u
}

// SetNillablePricingMode sets the "pricing_mode" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillablePricingMode(v *string) *ProductPackageUpdate {
	if v != nil {
		_u.SetPricingMode(*v)
	}
	return _u
}

// SetInventoryMode sets the "inventory_mode" field.
func (_u *ProductPackageUpdate) SetInventoryMode(v string) *ProductPackageUpdate {
	_u.mutation.SetInventoryMode(v)
	return _u
}

// SetNillableInventoryMode sets the "inventory_mode" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableInventoryMode(v *string) *ProductPackageUpdate {
	if v != nil {
		_u.SetInventoryMode(*v)
	}
	return _u
}

// SetMinOrderQty sets the "min_order_qty" field.
func (_u *ProductPackageUpdate) SetMinOrderQty(v int) *ProductPackageUpdate {
	_u.mutation.ResetMinOrderQty()
	_u.mutation.SetMinOrderQty(v)
	return _u
}

// SetNillableMinOrderQty sets the "min_order_qty" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableMinOrderQty(v *int) *ProductPackageUpdate {
	if v != nil {
		_u.SetMinOrderQty(*v)
	}
	return _u
}

// AddMinOrderQty adds value to the "min_order_qty" field.
func (_u *ProductPackageUpdate) AddMinOrderQty(v int) *ProductPackageUpdate {
	_u.mutation.AddMinOrderQty(v)
	return _u
}

// SetSellCurrency sets the "sell_currency" field.
func (_u *ProductPackageUpdate) SetSellCurrency(v string) *ProductPackageUpdate {
	_u.mutation.SetSellCurrency(v)
	return _u
}

// SetNillableSellCurrency sets the "sell_currency" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableSellCurrency(v *string) *ProductPackageUpdate {
	if v != nil {
		_u.SetSellCurrency(*v)
	}
	return _u
}

// SetCostCurrency sets the "cost_currency" field.
func (_u *ProductPackageUpdate) SetCostCurrency(v string) *ProductPackageUpdate {
	_u.mutation.SetCostCurrency(v)
	return _u
}

// SetNillableCostCurrency sets the "cost_currency" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableCostCurrency(v *string) *ProductPackageUpdate {
	if v != nil {
		_u.SetCostCurrency(*v)
	}
	return _u
}

// SetGroupPrices sets the "group_prices" field.
func (_u *ProductPackageUpdate) SetGroupPrices(v string) *ProductPackageUpdate {
	_u.mutation.SetGroupPrices(v)
	return _u
}

// SetNillableGroupPrices sets the "group_prices" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableGroupPrices(v *string) *ProductPackageUpdate {
	if v != nil {
		_u.SetGroupPrices(*v)
	}
	return _u
}

// ClearGroupPrices clears the value of the "group_prices" field.
func (_u *ProductPackageUpdate) ClearGroupPrices() *ProductPackageUpdate {
	_u.mutation.ClearGroupPrices()
	return _u
}

// SetTierPrices sets the "tier_prices" field.
func (_u *ProductPackageUpdate) SetTierPrices(v string) *ProductPackageUpdate {
	_u.mutation.SetTierPrices(v)
	return _u
}

// SetNillableTierPrices sets the "tier_prices" field if the given value is not nil.
func (_u *ProductPackageUpdate) SetNillableTierPrices(v *string) *ProductPackageUpdate {
	if v != nil {
		_u.SetTierPrices(*v)
	}
	return _u
}

// ClearTierPrices clears the value of the "tier_prices" field.
func (_u *ProductPackageUpdate) ClearTierPrices() *ProductPackageUpdate {
	_u.mutation.ClearTierPrices()
	return _u
}

// Mutation returns the ProductPackageMutation object of the builder.
func (_u *ProductPackageUpdate) Mutation() *ProductPackageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductPackageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductPackageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductPackageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductPackageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductPackageUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := productpackage.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ProductPackage.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := productpackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProductPackage.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductPackageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productpackage.Table, productpackage.Columns, sqlgraph.NewFieldSpec(productpackage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(productpackage.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(productpackage.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MerchantID(); ok {
		_spec.SetField(productpackage.FieldMerchantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMerchantID(); ok {
		_spec.AddField(productpackage.FieldMerchantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(productpackage.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(productpackage.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(productpackage.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(productpackage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(productpackage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PricingMode(); ok {
		_spec.SetField(productpackage.FieldPricingMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InventoryMode(); ok {
		_spec.SetField(productpackage.FieldInventoryMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.MinOrderQty(); ok {
		_spec.SetField(productpackage.FieldMinOrderQty, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinOrderQty(); ok {
		_spec.AddField(productpackage.FieldMinOrderQty, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SellCurrency(); ok {
		_spec.SetField(productpackage.FieldSellCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostCurrency(); ok {
		_spec.SetField(productpackage.FieldCostCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupPrices(); ok {
		_spec.SetField(productpackage.FieldGroupPrices, field.TypeString, value)
	}
	if _u.mutation.GroupPricesCleared() {
		_spec.ClearField(productpackage.FieldGroupPrices, field.TypeString)
	}
	if value, ok := _u.mutation.TierPrices(); ok {
		_spec.SetField(productpackage.FieldTierPrices, field.TypeString, value)
	}
	if _u.mutation.TierPricesCleared() {
		_spec.ClearField(productpackage.FieldTierPrices, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productpackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductPackageUpdateOne is the builder for updating a single ProductPackage entity.
type ProductPackageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductPackageMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *ProductPackageUpdateOne) SetTenantID(v int64) *ProductPackageUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableTenantID(v *int64) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *ProductPackageUpdateOne) AddTenantID(v int64) *ProductPackageUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetMerchantID sets the "merchant_id" field.
func (_u *ProductPackageUpdateOne) SetMerchantID(v int64) *ProductPackageUpdateOne {
	_u.mutation.ResetMerchantID()
	_u.mutation.SetMerchantID(v)
	return _u
}

// SetNillableMerchantID sets the "merchant_id" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableMerchantID(v *int64) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetMerchantID(*v)
	}
	return _u
}

// AddMerchantID adds value to the "merchant_id" field.
func (_u *ProductPackageUpdateOne) AddMerchantID(v int64) *ProductPackageUpdateOne {
	_u.mutation.AddMerchantID(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ProductPackageUpdateOne) SetProductID(v int64) *ProductPackageUpdateOne {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableProductID(v *int64) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *ProductPackageUpdateOne) AddProductID(v int64) *ProductPackageUpdateOne {
	_u.mutation.AddProductID(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *ProductPackageUpdateOne) SetCode(v string) *ProductPackageUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableCode(v *string) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProductPackageUpdateOne) SetName(v string) *ProductPackageUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableName(v *string) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProductPackageUpdateOne) SetStatus(v string) *ProductPackageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableStatus(v *string) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPricingMode sets the "pricing_mode" field.
func (_u *ProductPackageUpdateOne) SetPricingMode(v string) *ProductPackageUpdateOne {
	_u.mutation.SetPricingMode(v)
	return _u
}

// SetNillablePricingMode sets the "pricing_mode" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillablePricingMode(v *string) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetPricingMode(*v)
	}
	return _u
}

// SetInventoryMode sets the "inventory_mode" field.
func (_u *ProductPackageUpdateOne) SetInventoryMode(v string) *ProductPackageUpdateOne {
	_u.mutation.SetInventoryMode(v)
	return _u
}

// SetNillableInventoryMode sets the "inventory_mode" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableInventoryMode(v *string) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetInventoryMode(*v)
	}
	return _u
}

// SetMinOrderQty sets the "min_order_qty" field.
func (_u *ProductPackageUpdateOne) SetMinOrderQty(v int) *ProductPackageUpdateOne {
	_u.mutation.ResetMinOrderQty()
	_u.mutation.SetMinOrderQty(v)
	return _u
}

// SetNillableMinOrderQty sets the "min_order_qty" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableMinOrderQty(v *int) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetMinOrderQty(*v)
	}
	return _u
}

// AddMinOrderQty adds value to the "min_order_qty" field.
func (_u *ProductPackageUpdateOne) AddMinOrderQty(v int) *ProductPackageUpdateOne {
	_u.mutation.AddMinOrderQty(v)
	return _u
}

// SetSellCurrency sets the "sell_currency" field.
func (_u *ProductPackageUpdateOne) SetSellCurrency(v string) *ProductPackageUpdateOne {
	_u.mutation.SetSellCurrency(v)
	return _u
}

// SetNillableSellCurrency sets the "sell_currency" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableSellCurrency(v *string) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetSellCurrency(*v)
	}
	return _u
}

// SetCostCurrency sets the "cost_currency" field.
func (_u *ProductPackageUpdateOne) SetCostCurrency(v string) *ProductPackageUpdateOne {
	_u.mutation.SetCostCurrency(v)
	return _u
}

// SetNillableCostCurrency sets the "cost_currency" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableCostCurrency(v *string) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetCostCurrency(*v)
	}
	return _u
}

// SetGroupPrices sets the "group_prices" field.
func (_u *ProductPackageUpdateOne) SetGroupPrices(v string) *ProductPackageUpdateOne {
	_u.mutation.SetGroupPrices(v)
	return _u
}

// SetNillableGroupPrices sets the "group_prices" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableGroupPrices(v *string) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetGroupPrices(*v)
	}
	return _u
}

// ClearGroupPrices clears the value of the "group_prices" field.
func (_u *ProductPackageUpdateOne) ClearGroupPrices() *ProductPackageUpdateOne {
	_u.mutation.ClearGroupPrices()
	return _u
}

// SetTierPrices sets the "tier_prices" field.
func (_u *ProductPackageUpdateOne) SetTierPrices(v string) *ProductPackageUpdateOne {
	_u.mutation.SetTierPrices(v)
	return _u
}

// SetNillableTierPrices sets the "tier_prices" field if the given value is not nil.
func (_u *ProductPackageUpdateOne) SetNillableTierPrices(v *string) *ProductPackageUpdateOne {
	if v != nil {
		_u.SetTierPrices(*v)
	}
	return _u
}

// ClearTierPrices clears the value of the "tier_prices" field.
func (_u *ProductPackageUpdateOne) ClearTierPrices() *ProductPackageUpdateOne {
	_u.mutation.ClearTierPrices()
	return _u
}

// Mutation returns the ProductPackageMutation object of the builder.
func (_u *ProductPackageUpdateOne) Mutation() *ProductPackageMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProductPackageUpdate builder.
func (_u *ProductPackageUpdateOne) Where(ps ...predicate.ProductPackage) *ProductPackageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductPackageUpdateOne) Select(field string, fields ...string) *ProductPackageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProductPackage entity.
func (_u *ProductPackageUpdateOne) Save(ctx context.Context) (*ProductPackage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductPackageUpdateOne) SaveX(ctx context.Context) *ProductPackage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductPackageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductPackageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductPackageUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := productpackage.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ProductPackage.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := productpackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProductPackage.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductPackageUpdateOne) sqlSave(ctx context.Context) (_node *ProductPackage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productpackage.Table, productpackage.Columns, sqlgraph.NewFieldSpec(productpackage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductPackage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productpackage.FieldID)
		for _, f := range fields {
			if !productpackage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productpackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(productpackage.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(productpackage.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MerchantID(); ok {
		_spec.SetField(productpackage.FieldMerchantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMerchantID(); ok {
		_spec.AddField(productpackage.FieldMerchantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(productpackage.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(productpackage.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(productpackage.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(productpackage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(productpackage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PricingMode(); ok {
		_spec.SetField(productpackage.FieldPricingMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InventoryMode(); ok {
		_spec.SetField(productpackage.FieldInventoryMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.MinOrderQty(); ok {
		_spec.SetField(productpackage.FieldMinOrderQty, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinOrderQty(); ok {
		_spec.AddField(productpackage.FieldMinOrderQty, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SellCurrency(); ok {
		_spec.SetField(productpackage.FieldSellCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostCurrency(); ok {
		_spec.SetField(productpackage.FieldCostCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupPrices(); ok {
		_spec.SetField(productpackage.FieldGroupPrices, field.TypeString, value)
	}
	if _u.mutation.GroupPricesCleared() {
		_spec.ClearField(productpackage.FieldGroupPrices, field.TypeString)
	}
	if value, ok := _u.mutation.TierPrices(); ok {
		_spec.SetField(productpackage.FieldTierPrices, field.TypeString, value)
	}
	if _u.mutation.TierPricesCleared() {
		_spec.ClearField(productpackage.FieldTierPrices, field.TypeString)
	}
	_node = &ProductPackage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productpackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
