// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/meinongyihe/travel-rpc/ent/review"
)

// ReviewCreate is the builder for creating a Review entity.
type ReviewCreate struct {
	config
	mutation *ReviewMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *ReviewCreate) SetTenantID(v int64) *ReviewCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetMerchantID sets the "merchant_id" field.
func (_c *ReviewCreate) SetMerchantID(v int64) *ReviewCreate {
	_c.mutation.SetMerchantID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *ReviewCreate) SetOrderID(v int64) *ReviewCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *ReviewCreate) SetOrderNo(v string) *ReviewCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *ReviewCreate) SetProductID(v int64) *ReviewCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ReviewCreate) SetUserID(v int64) *ReviewCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableUserID(v *int64) *ReviewCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetRating sets the "rating" field.
func (_c *ReviewCreate) SetRating(v int) *ReviewCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableRating(v *int) *ReviewCreate {
	if v != nil {
		_c.SetRating(*v)
	}
	return _c
}

// SetServiceRating sets the "service_rating" field.
func (_c *ReviewCreate) SetServiceRating(v int) *ReviewCreate {
	_c.mutation.SetServiceRating(v)
	return _c
}

// SetNillableServiceRating sets the "service_rating" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableServiceRating(v *int) *ReviewCreate {
	if v != nil {
		_c.SetServiceRating(*v)
	}
	return _c
}

// SetValueRating sets the "value_rating" field.
func (_c *ReviewCreate) SetValueRating(v int) *ReviewCreate {
	_c.mutation.SetValueRating(v)
	return _c
}

// SetNillableValueRating sets the "value_rating" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableValueRating(v *int) *ReviewCreate {
	if v != nil {
		_c.SetValueRating(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *ReviewCreate) SetContent(v string) *ReviewCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableContent(v *string) *ReviewCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetImages sets the "images" field.
func (_c *ReviewCreate) SetImages(v string) *ReviewCreate {
	_c.mutation.SetImages(v)
	return _c
}

// SetNillableImages sets the "images" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableImages(v *string) *ReviewCreate {
	if v != nil {
		_c.SetImages(*v)
	}
	return _c
}

// SetReplyContent sets the "reply_content" field.
func (_c *ReviewCreate) SetReplyContent(v string) *ReviewCreate {
	_c.mutation.SetReplyContent(v)
	return _c
}

// SetNillableReplyContent sets the "reply_content" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableReplyContent(v *string) *ReviewCreate {
	if v != nil {
		_c.SetReplyContent(*v)
	}
	return _c
}

// SetReplyTime sets the "reply_time" field.
func (_c *ReviewCreate) SetReplyTime(v int64) *ReviewCreate {
	_c.mutation.SetReplyTime(v)
	return _c
}

// SetNillableReplyTime sets the "reply_time" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableReplyTime(v *int64) *ReviewCreate {
	if v != nil {
		_c.SetReplyTime(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReviewCreate) SetStatus(v string) *ReviewCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableStatus(v *string) *ReviewCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// Mutation returns the ReviewMutation object of the builder.
func (_c *ReviewCreate) Mutation() *ReviewMutation {
	return _c.mutation
}

// Save creates the Review in the database.
func (_c *ReviewCreate) Save(ctx context.Context) (*Review, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReviewCreate) SaveX(ctx context.Context) *Review {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReviewCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReviewCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReviewCreate) defaults() {
	if _, ok := _c.mutation.Rating(); !ok {
		v := review.DefaultRating
		_c.mutation.SetRating(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := review.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReviewCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Review.tenant_id"`)}
	}
	if _, ok := _c.mutation.MerchantID(); !ok {
		return &ValidationError{Name: "merchant_id", err: errors.New(`ent: missing required field "Review.merchant_id"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "Review.order_id"`)}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "Review.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := review.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Review.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "Review.product_id"`)}
	}
	if _, ok := _c.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`ent: missing required field "Review.rating"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Review.status"`)}
	}
	return nil
}

func (_c *ReviewCreate) sqlSave(ctx context.Context) (*Review, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReviewCreate) createSpec() (*Review, *sqlgraph.CreateSpec) {
	var (
		_node = &Review{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(review.Table, sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(review.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.MerchantID(); ok {
		_spec.SetField(review.FieldMerchantID, field.TypeInt64, value)
		_node.MerchantID = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(review.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(review.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.ProductID(); ok {
		_spec.SetField(review.FieldProductID, field.TypeInt64, value)
		_node.ProductID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(review.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt, value)
		_node.Rating = value
	}
	if value, ok := _c.mutation.ServiceRating(); ok {
		_spec.SetField(review.FieldServiceRating, field.TypeInt, value)
		_node.ServiceRating = value
	}
	if value, ok := _c.mutation.ValueRating(); ok {
		_spec.SetField(review.FieldValueRating, field.TypeInt, value)
		_node.ValueRating = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(review.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Images(); ok {
		_spec.SetField(review.FieldImages, field.TypeString, value)
		_node.Images = value
	}
	if value, ok := _c.mutation.ReplyContent(); ok {
		_spec.SetField(review.FieldReplyContent, field.TypeString, value)
		_node.ReplyContent = value
	}
	if value, ok := _c.mutation.ReplyTime(); ok {
		_spec.SetField(review.FieldReplyTime, field.TypeInt64, value)
		_node.ReplyTime = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(review.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	return _node, _spec
}

// ReviewCreateBulk is the builder for creating many Review entities in bulk.
type ReviewCreateBulk struct {
	config
	err      error
	builders []*ReviewCreate
}

// Save creates the Review entities in the database.
func (_c *ReviewCreateBulk) Save(ctx context.Context) ([]*Review, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Review, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReviewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReviewCreateBulk) SaveX(ctx context.Context) []*Review {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReviewCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReviewCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
