// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"gitee.com/meinongyihe/travel-rpc/ent/currency"
	"gitee.com/meinongyihe/travel-rpc/ent/exchangerate"
	"gitee.com/meinongyihe/travel-rpc/ent/inventory"
	"gitee.com/meinongyihe/travel-rpc/ent/inventoryreservation"
	"gitee.com/meinongyihe/travel-rpc/ent/itinerarystop"
	"gitee.com/meinongyihe/travel-rpc/ent/merchant"
	"gitee.com/meinongyihe/travel-rpc/ent/merchantconfig"
	"gitee.com/meinongyihe/travel-rpc/ent/order"
	"gitee.com/meinongyihe/travel-rpc/ent/packagetranslation"
	"gitee.com/meinongyihe/travel-rpc/ent/payment"
	"gitee.com/meinongyihe/travel-rpc/ent/product"
	"gitee.com/meinongyihe/travel-rpc/ent/productpackage"
	"gitee.com/meinongyihe/travel-rpc/ent/producttranslation"
	"gitee.com/meinongyihe/travel-rpc/ent/review"
	"gitee.com/meinongyihe/travel-rpc/ent/schema"
	"gitee.com/meinongyihe/travel-rpc/ent/tenant"
	"gitee.com/meinongyihe/travel-rpc/ent/traveler"
	"gitee.com/meinongyihe/travel-rpc/ent/user"
	"gitee.com/meinongyihe/travel-rpc/ent/voucher"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	currencyFields := schema.Currency{}.Fields()
	_ = currencyFields
	// currencyDescCode is the schema descriptor for code field.
	currencyDescCode := currencyFields[0].Descriptor()
	// currency.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	currency.CodeValidator = currencyDescCode.Validators[0].(func(string) error)
	// currencyDescDecimals is the schema descriptor for decimals field.
	currencyDescDecimals := currencyFields[3].Descriptor()
	// currency.DefaultDecimals holds the default value on creation for the decimals field.
	currency.DefaultDecimals = currencyDescDecimals.Default.(int)
	// currencyDescSymbolPosition is the schema descriptor for symbol_position field.
	currencyDescSymbolPosition := currencyFields[4].Descriptor()
	// currency.DefaultSymbolPosition holds the default value on creation for the symbol_position field.
	currency.DefaultSymbolPosition = currencyDescSymbolPosition.Default.(string)
	// currencyDescIsBase is the schema descriptor for is_base field.
	currencyDescIsBase := currencyFields[5].Descriptor()
	// currency.DefaultIsBase holds the default value on creation for the is_base field.
	currency.DefaultIsBase = currencyDescIsBase.Default.(bool)
	// currencyDescStatus is the schema descriptor for status field.
	currencyDescStatus := currencyFields[6].Descriptor()
	// currency.DefaultStatus holds the default value on creation for the status field.
	currency.DefaultStatus = currencyDescStatus.Default.(string)
	// currencyDescSort is the schema descriptor for sort field.
	currencyDescSort := currencyFields[7].Descriptor()
	// currency.DefaultSort holds the default value on creation for the sort field.
	currency.DefaultSort = currencyDescSort.Default.(int)
	exchangerateFields := schema.ExchangeRate{}.Fields()
	_ = exchangerateFields
	// exchangerateDescBaseCurrency is the schema descriptor for base_currency field.
	exchangerateDescBaseCurrency := exchangerateFields[0].Descriptor()
	// exchangerate.DefaultBaseCurrency holds the default value on creation for the base_currency field.
	exchangerate.DefaultBaseCurrency = exchangerateDescBaseCurrency.Default.(string)
	// exchangerate.BaseCurrencyValidator is a validator for the "base_currency" field. It is called by the builders before save.
	exchangerate.BaseCurrencyValidator = exchangerateDescBaseCurrency.Validators[0].(func(string) error)
	// exchangerateDescTargetCurrency is the schema descriptor for target_currency field.
	exchangerateDescTargetCurrency := exchangerateFields[1].Descriptor()
	// exchangerate.TargetCurrencyValidator is a validator for the "target_currency" field. It is called by the builders before save.
	exchangerate.TargetCurrencyValidator = exchangerateDescTargetCurrency.Validators[0].(func(string) error)
	// exchangerateDescRateMicro is the schema descriptor for rate_micro field.
	exchangerateDescRateMicro := exchangerateFields[2].Descriptor()
	// exchangerate.DefaultRateMicro holds the default value on creation for the rate_micro field.
	exchangerate.DefaultRateMicro = exchangerateDescRateMicro.Default.(int64)
	// exchangerateDescSource is the schema descriptor for source field.
	exchangerateDescSource := exchangerateFields[3].Descriptor()
	// exchangerate.DefaultSource holds the default value on creation for the source field.
	exchangerate.DefaultSource = exchangerateDescSource.Default.(string)
	// exchangerateDescEffectiveAt is the schema descriptor for effective_at field.
	exchangerateDescEffectiveAt := exchangerateFields[4].Descriptor()
	// exchangerate.DefaultEffectiveAt holds the default value on creation for the effective_at field.
	exchangerate.DefaultEffectiveAt = exchangerateDescEffectiveAt.Default.(int64)
	// exchangerateDescStatus is the schema descriptor for status field.
	exchangerateDescStatus := exchangerateFields[5].Descriptor()
	// exchangerate.DefaultStatus holds the default value on creation for the status field.
	exchangerate.DefaultStatus = exchangerateDescStatus.Default.(string)
	inventoryFields := schema.Inventory{}.Fields()
	_ = inventoryFields
	// inventoryDescCapacity is the schema descriptor for capacity field.
	inventoryDescCapacity := inventoryFields[5].Descriptor()
	// inventory.DefaultCapacity holds the default value on creation for the capacity field.
	inventory.DefaultCapacity = inventoryDescCapacity.Default.(int)
	// inventoryDescReserved is the schema descriptor for reserved field.
	inventoryDescReserved := inventoryFields[6].Descriptor()
	// inventory.DefaultReserved holds the default value on creation for the reserved field.
	inventory.DefaultReserved = inventoryDescReserved.Default.(int)
	// inventoryDescUnitPrice is the schema descriptor for unit_price field.
	inventoryDescUnitPrice := inventoryFields[7].Descriptor()
	// inventory.DefaultUnitPrice holds the default value on creation for the unit_price field.
	inventory.DefaultUnitPrice = inventoryDescUnitPrice.Default.(int64)
	// inventoryDescCurrency is the schema descriptor for currency field.
	inventoryDescCurrency := inventoryFields[8].Descriptor()
	// inventory.DefaultCurrency holds the default value on creation for the currency field.
	inventory.DefaultCurrency = inventoryDescCurrency.Default.(string)
	// inventoryDescStatus is the schema descriptor for status field.
	inventoryDescStatus := inventoryFields[9].Descriptor()
	// inventory.DefaultStatus holds the default value on creation for the status field.
	inventory.DefaultStatus = inventoryDescStatus.Default.(string)
	// inventoryDescInventoryMode is the schema descriptor for inventory_mode field.
	inventoryDescInventoryMode := inventoryFields[10].Descriptor()
	// inventory.DefaultInventoryMode holds the default value on creation for the inventory_mode field.
	inventory.DefaultInventoryMode = inventoryDescInventoryMode.Default.(string)
	// inventoryDescIsOpen is the schema descriptor for is_open field.
	inventoryDescIsOpen := inventoryFields[12].Descriptor()
	// inventory.DefaultIsOpen holds the default value on creation for the is_open field.
	inventory.DefaultIsOpen = inventoryDescIsOpen.Default.(bool)
	inventoryreservationFields := schema.InventoryReservation{}.Fields()
	_ = inventoryreservationFields
	// inventoryreservationDescReservationKey is the schema descriptor for reservation_key field.
	inventoryreservationDescReservationKey := inventoryreservationFields[3].Descriptor()
	// inventoryreservation.ReservationKeyValidator is a validator for the "reservation_key" field. It is called by the builders before save.
	inventoryreservation.ReservationKeyValidator = inventoryreservationDescReservationKey.Validators[0].(func(string) error)
	// inventoryreservationDescQuantity is the schema descriptor for quantity field.
	inventoryreservationDescQuantity := inventoryreservationFields[4].Descriptor()
	// inventoryreservation.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	inventoryreservation.QuantityValidator = inventoryreservationDescQuantity.Validators[0].(func(int) error)
	// inventoryreservationDescStatus is the schema descriptor for status field.
	inventoryreservationDescStatus := inventoryreservationFields[6].Descriptor()
	// inventoryreservation.DefaultStatus holds the default value on creation for the status field.
	inventoryreservation.DefaultStatus = inventoryreservationDescStatus.Default.(string)
	// inventoryreservationDescExpiresAt is the schema descriptor for expires_at field.
	inventoryreservationDescExpiresAt := inventoryreservationFields[7].Descriptor()
	// inventoryreservation.DefaultExpiresAt holds the default value on creation for the expires_at field.
	inventoryreservation.DefaultExpiresAt = inventoryreservationDescExpiresAt.Default.(func() time.Time)
	// inventoryreservationDescCreatedAt is the schema descriptor for created_at field.
	inventoryreservationDescCreatedAt := inventoryreservationFields[8].Descriptor()
	// inventoryreservation.DefaultCreatedAt holds the default value on creation for the created_at field.
	inventoryreservation.DefaultCreatedAt = inventoryreservationDescCreatedAt.Default.(func() time.Time)
	// inventoryreservationDescUpdatedAt is the schema descriptor for updated_at field.
	inventoryreservationDescUpdatedAt := inventoryreservationFields[9].Descriptor()
	// inventoryreservation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	inventoryreservation.DefaultUpdatedAt = inventoryreservationDescUpdatedAt.Default.(func() time.Time)
	// inventoryreservation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	inventoryreservation.UpdateDefaultUpdatedAt = inventoryreservationDescUpdatedAt.UpdateDefault.(func() time.Time)
	itinerarystopFields := schema.ItineraryStop{}.Fields()
	_ = itinerarystopFields
	// itinerarystopDescTitle is the schema descriptor for title field.
	itinerarystopDescTitle := itinerarystopFields[4].Descriptor()
	// itinerarystop.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	itinerarystop.TitleValidator = itinerarystopDescTitle.Validators[0].(func(string) error)
	// itinerarystopDescSequence is the schema descriptor for sequence field.
	itinerarystopDescSequence := itinerarystopFields[6].Descriptor()
	// itinerarystop.DefaultSequence holds the default value on creation for the sequence field.
	itinerarystop.DefaultSequence = itinerarystopDescSequence.Default.(int)
	// itinerarystopDescIsEntering is the schema descriptor for is_entering field.
	itinerarystopDescIsEntering := itinerarystopFields[13].Descriptor()
	// itinerarystop.DefaultIsEntering holds the default value on creation for the is_entering field.
	itinerarystop.DefaultIsEntering = itinerarystopDescIsEntering.Default.(bool)
	// itinerarystopDescIsPickup is the schema descriptor for is_pickup field.
	itinerarystopDescIsPickup := itinerarystopFields[36].Descriptor()
	// itinerarystop.DefaultIsPickup holds the default value on creation for the is_pickup field.
	itinerarystop.DefaultIsPickup = itinerarystopDescIsPickup.Default.(bool)
	// itinerarystopDescIsDropoff is the schema descriptor for is_dropoff field.
	itinerarystopDescIsDropoff := itinerarystopFields[37].Descriptor()
	// itinerarystop.DefaultIsDropoff holds the default value on creation for the is_dropoff field.
	itinerarystop.DefaultIsDropoff = itinerarystopDescIsDropoff.Default.(bool)
	// itinerarystopDescAgreementNoShopping is the schema descriptor for agreement_no_shopping field.
	itinerarystopDescAgreementNoShopping := itinerarystopFields[38].Descriptor()
	// itinerarystop.DefaultAgreementNoShopping holds the default value on creation for the agreement_no_shopping field.
	itinerarystop.DefaultAgreementNoShopping = itinerarystopDescAgreementNoShopping.Default.(bool)
	// itinerarystopDescAgreementAdjustable is the schema descriptor for agreement_adjustable field.
	itinerarystopDescAgreementAdjustable := itinerarystopFields[39].Descriptor()
	// itinerarystop.DefaultAgreementAdjustable holds the default value on creation for the agreement_adjustable field.
	itinerarystop.DefaultAgreementAdjustable = itinerarystopDescAgreementAdjustable.Default.(bool)
	merchantFields := schema.Merchant{}.Fields()
	_ = merchantFields
	// merchantDescName is the schema descriptor for name field.
	merchantDescName := merchantFields[1].Descriptor()
	// merchant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	merchant.NameValidator = merchantDescName.Validators[0].(func(string) error)
	// merchantDescCode is the schema descriptor for code field.
	merchantDescCode := merchantFields[2].Descriptor()
	// merchant.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	merchant.CodeValidator = merchantDescCode.Validators[0].(func(string) error)
	// merchantDescStatus is the schema descriptor for status field.
	merchantDescStatus := merchantFields[3].Descriptor()
	// merchant.DefaultStatus holds the default value on creation for the status field.
	merchant.DefaultStatus = merchantDescStatus.Default.(string)
	merchantconfigFields := schema.MerchantConfig{}.Fields()
	_ = merchantconfigFields
	// merchantconfigDescTenantID is the schema descriptor for tenant_id field.
	merchantconfigDescTenantID := merchantconfigFields[0].Descriptor()
	// merchantconfig.DefaultTenantID holds the default value on creation for the tenant_id field.
	merchantconfig.DefaultTenantID = merchantconfigDescTenantID.Default.(int64)
	// merchantconfigDescMerchantID is the schema descriptor for merchant_id field.
	merchantconfigDescMerchantID := merchantconfigFields[1].Descriptor()
	// merchantconfig.DefaultMerchantID holds the default value on creation for the merchant_id field.
	merchantconfig.DefaultMerchantID = merchantconfigDescMerchantID.Default.(int64)
	// merchantconfigDescConfigType is the schema descriptor for config_type field.
	merchantconfigDescConfigType := merchantconfigFields[2].Descriptor()
	// merchantconfig.ConfigTypeValidator is a validator for the "config_type" field. It is called by the builders before save.
	merchantconfig.ConfigTypeValidator = merchantconfigDescConfigType.Validators[0].(func(string) error)
	// merchantconfigDescConfigKey is the schema descriptor for config_key field.
	merchantconfigDescConfigKey := merchantconfigFields[3].Descriptor()
	// merchantconfig.ConfigKeyValidator is a validator for the "config_key" field. It is called by the builders before save.
	merchantconfig.ConfigKeyValidator = merchantconfigDescConfigKey.Validators[0].(func(string) error)
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescOrderNo is the schema descriptor for order_no field.
	orderDescOrderNo := orderFields[2].Descriptor()
	// order.OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	order.OrderNoValidator = orderDescOrderNo.Validators[0].(func(string) error)
	// orderDescCurrency is the schema descriptor for currency field.
	orderDescCurrency := orderFields[9].Descriptor()
	// order.DefaultCurrency holds the default value on creation for the currency field.
	order.DefaultCurrency = orderDescCurrency.Default.(string)
	// orderDescDisplayCurrency is the schema descriptor for display_currency field.
	orderDescDisplayCurrency := orderFields[10].Descriptor()
	// order.DefaultDisplayCurrency holds the default value on creation for the display_currency field.
	order.DefaultDisplayCurrency = orderDescDisplayCurrency.Default.(string)
	// orderDescExchangeRateMicro is the schema descriptor for exchange_rate_micro field.
	orderDescExchangeRateMicro := orderFields[11].Descriptor()
	// order.DefaultExchangeRateMicro holds the default value on creation for the exchange_rate_micro field.
	order.DefaultExchangeRateMicro = orderDescExchangeRateMicro.Default.(int64)
	// orderDescDisplayAmountMinor is the schema descriptor for display_amount_minor field.
	orderDescDisplayAmountMinor := orderFields[12].Descriptor()
	// order.DefaultDisplayAmountMinor holds the default value on creation for the display_amount_minor field.
	order.DefaultDisplayAmountMinor = orderDescDisplayAmountMinor.Default.(int64)
	// orderDescStatus is the schema descriptor for status field.
	orderDescStatus := orderFields[13].Descriptor()
	// order.DefaultStatus holds the default value on creation for the status field.
	order.DefaultStatus = orderDescStatus.Default.(string)
	// orderDescPaymentStatus is the schema descriptor for payment_status field.
	orderDescPaymentStatus := orderFields[14].Descriptor()
	// order.DefaultPaymentStatus holds the default value on creation for the payment_status field.
	order.DefaultPaymentStatus = orderDescPaymentStatus.Default.(string)
	packagetranslationFields := schema.PackageTranslation{}.Fields()
	_ = packagetranslationFields
	// packagetranslationDescLocale is the schema descriptor for locale field.
	packagetranslationDescLocale := packagetranslationFields[1].Descriptor()
	// packagetranslation.LocaleValidator is a validator for the "locale" field. It is called by the builders before save.
	packagetranslation.LocaleValidator = packagetranslationDescLocale.Validators[0].(func(string) error)
	// packagetranslationDescSource is the schema descriptor for source field.
	packagetranslationDescSource := packagetranslationFields[3].Descriptor()
	// packagetranslation.DefaultSource holds the default value on creation for the source field.
	packagetranslation.DefaultSource = packagetranslationDescSource.Default.(string)
	// packagetranslationDescStatus is the schema descriptor for status field.
	packagetranslationDescStatus := packagetranslationFields[4].Descriptor()
	// packagetranslation.DefaultStatus holds the default value on creation for the status field.
	packagetranslation.DefaultStatus = packagetranslationDescStatus.Default.(string)
	// packagetranslationDescUpdatedAt is the schema descriptor for updated_at field.
	packagetranslationDescUpdatedAt := packagetranslationFields[5].Descriptor()
	// packagetranslation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	packagetranslation.DefaultUpdatedAt = packagetranslationDescUpdatedAt.Default.(int64)
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescPaymentNo is the schema descriptor for payment_no field.
	paymentDescPaymentNo := paymentFields[3].Descriptor()
	// payment.PaymentNoValidator is a validator for the "payment_no" field. It is called by the builders before save.
	payment.PaymentNoValidator = paymentDescPaymentNo.Validators[0].(func(string) error)
	// paymentDescProvider is the schema descriptor for provider field.
	paymentDescProvider := paymentFields[4].Descriptor()
	// payment.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	payment.ProviderValidator = paymentDescProvider.Validators[0].(func(string) error)
	// paymentDescCurrency is the schema descriptor for currency field.
	paymentDescCurrency := paymentFields[7].Descriptor()
	// payment.DefaultCurrency holds the default value on creation for the currency field.
	payment.DefaultCurrency = paymentDescCurrency.Default.(string)
	// paymentDescStatus is the schema descriptor for status field.
	paymentDescStatus := paymentFields[8].Descriptor()
	// payment.DefaultStatus holds the default value on creation for the status field.
	payment.DefaultStatus = paymentDescStatus.Default.(string)
	// paymentDescIdempotencyKey is the schema descriptor for idempotency_key field.
	paymentDescIdempotencyKey := paymentFields[9].Descriptor()
	// payment.IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	payment.IdempotencyKeyValidator = paymentDescIdempotencyKey.Validators[0].(func(string) error)
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescCode is the schema descriptor for code field.
	productDescCode := productFields[2].Descriptor()
	// product.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	product.CodeValidator = productDescCode.Validators[0].(func(string) error)
	// productDescTitle is the schema descriptor for title field.
	productDescTitle := productFields[3].Descriptor()
	// product.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	product.TitleValidator = productDescTitle.Validators[0].(func(string) error)
	// productDescCurrency is the schema descriptor for currency field.
	productDescCurrency := productFields[7].Descriptor()
	// product.DefaultCurrency holds the default value on creation for the currency field.
	product.DefaultCurrency = productDescCurrency.Default.(string)
	// productDescMinPrice is the schema descriptor for min_price field.
	productDescMinPrice := productFields[8].Descriptor()
	// product.DefaultMinPrice holds the default value on creation for the min_price field.
	product.DefaultMinPrice = productDescMinPrice.Default.(int64)
	// productDescStatus is the schema descriptor for status field.
	productDescStatus := productFields[9].Descriptor()
	// product.DefaultStatus holds the default value on creation for the status field.
	product.DefaultStatus = productDescStatus.Default.(string)
	productpackageFields := schema.ProductPackage{}.Fields()
	_ = productpackageFields
	// productpackageDescCode is the schema descriptor for code field.
	productpackageDescCode := productpackageFields[3].Descriptor()
	// productpackage.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	productpackage.CodeValidator = productpackageDescCode.Validators[0].(func(string) error)
	// productpackageDescName is the schema descriptor for name field.
	productpackageDescName := productpackageFields[4].Descriptor()
	// productpackage.NameValidator is a validator for the "name" field. It is called by the builders before save.
	productpackage.NameValidator = productpackageDescName.Validators[0].(func(string) error)
	// productpackageDescStatus is the schema descriptor for status field.
	productpackageDescStatus := productpackageFields[5].Descriptor()
	// productpackage.DefaultStatus holds the default value on creation for the status field.
	productpackage.DefaultStatus = productpackageDescStatus.Default.(string)
	// productpackageDescPricingMode is the schema descriptor for pricing_mode field.
	productpackageDescPricingMode := productpackageFields[6].Descriptor()
	// productpackage.DefaultPricingMode holds the default value on creation for the pricing_mode field.
	productpackage.DefaultPricingMode = productpackageDescPricingMode.Default.(string)
	// productpackageDescInventoryMode is the schema descriptor for inventory_mode field.
	productpackageDescInventoryMode := productpackageFields[7].Descriptor()
	// productpackage.DefaultInventoryMode holds the default value on creation for the inventory_mode field.
	productpackage.DefaultInventoryMode = productpackageDescInventoryMode.Default.(string)
	// productpackageDescMinOrderQty is the schema descriptor for min_order_qty field.
	productpackageDescMinOrderQty := productpackageFields[8].Descriptor()
	// productpackage.DefaultMinOrderQty holds the default value on creation for the min_order_qty field.
	productpackage.DefaultMinOrderQty = productpackageDescMinOrderQty.Default.(int)
	// productpackageDescSellCurrency is the schema descriptor for sell_currency field.
	productpackageDescSellCurrency := productpackageFields[9].Descriptor()
	// productpackage.DefaultSellCurrency holds the default value on creation for the sell_currency field.
	productpackage.DefaultSellCurrency = productpackageDescSellCurrency.Default.(string)
	// productpackageDescCostCurrency is the schema descriptor for cost_currency field.
	productpackageDescCostCurrency := productpackageFields[10].Descriptor()
	// productpackage.DefaultCostCurrency holds the default value on creation for the cost_currency field.
	productpackage.DefaultCostCurrency = productpackageDescCostCurrency.Default.(string)
	producttranslationFields := schema.ProductTranslation{}.Fields()
	_ = producttranslationFields
	// producttranslationDescLocale is the schema descriptor for locale field.
	producttranslationDescLocale := producttranslationFields[1].Descriptor()
	// producttranslation.LocaleValidator is a validator for the "locale" field. It is called by the builders before save.
	producttranslation.LocaleValidator = producttranslationDescLocale.Validators[0].(func(string) error)
	// producttranslationDescSource is the schema descriptor for source field.
	producttranslationDescSource := producttranslationFields[7].Descriptor()
	// producttranslation.DefaultSource holds the default value on creation for the source field.
	producttranslation.DefaultSource = producttranslationDescSource.Default.(string)
	// producttranslationDescStatus is the schema descriptor for status field.
	producttranslationDescStatus := producttranslationFields[8].Descriptor()
	// producttranslation.DefaultStatus holds the default value on creation for the status field.
	producttranslation.DefaultStatus = producttranslationDescStatus.Default.(string)
	// producttranslationDescUpdatedAt is the schema descriptor for updated_at field.
	producttranslationDescUpdatedAt := producttranslationFields[9].Descriptor()
	// producttranslation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	producttranslation.DefaultUpdatedAt = producttranslationDescUpdatedAt.Default.(int64)
	reviewFields := schema.Review{}.Fields()
	_ = reviewFields
	// reviewDescOrderNo is the schema descriptor for order_no field.
	reviewDescOrderNo := reviewFields[3].Descriptor()
	// review.OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	review.OrderNoValidator = reviewDescOrderNo.Validators[0].(func(string) error)
	// reviewDescRating is the schema descriptor for rating field.
	reviewDescRating := reviewFields[6].Descriptor()
	// review.DefaultRating holds the default value on creation for the rating field.
	review.DefaultRating = reviewDescRating.Default.(int)
	// reviewDescStatus is the schema descriptor for status field.
	reviewDescStatus := reviewFields[13].Descriptor()
	// review.DefaultStatus holds the default value on creation for the status field.
	review.DefaultStatus = reviewDescStatus.Default.(string)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescCode is the schema descriptor for code field.
	tenantDescCode := tenantFields[0].Descriptor()
	// tenant.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	tenant.CodeValidator = tenantDescCode.Validators[0].(func(string) error)
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescStatus is the schema descriptor for status field.
	tenantDescStatus := tenantFields[2].Descriptor()
	// tenant.DefaultStatus holds the default value on creation for the status field.
	tenant.DefaultStatus = tenantDescStatus.Default.(string)
	travelerFields := schema.Traveler{}.Fields()
	_ = travelerFields
	// travelerDescName is the schema descriptor for name field.
	travelerDescName := travelerFields[2].Descriptor()
	// traveler.NameValidator is a validator for the "name" field. It is called by the builders before save.
	traveler.NameValidator = travelerDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.DefaultUsername holds the default value on creation for the username field.
	user.DefaultUsername = userDescUsername.Default.(string)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[1].Descriptor()
	// user.DefaultNickname holds the default value on creation for the nickname field.
	user.DefaultNickname = userDescNickname.Default.(string)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.DefaultPassword holds the default value on creation for the password field.
	user.DefaultPassword = userDescPassword.Default.(string)
	// userDescSalt is the schema descriptor for salt field.
	userDescSalt := userFields[3].Descriptor()
	// user.DefaultSalt holds the default value on creation for the salt field.
	user.DefaultSalt = userDescSalt.Default.(string)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// userDescMobile is the schema descriptor for mobile field.
	userDescMobile := userFields[5].Descriptor()
	// user.DefaultMobile holds the default value on creation for the mobile field.
	user.DefaultMobile = userDescMobile.Default.(string)
	// userDescAvatar is the schema descriptor for avatar field.
	userDescAvatar := userFields[6].Descriptor()
	// user.DefaultAvatar holds the default value on creation for the avatar field.
	user.DefaultAvatar = userDescAvatar.Default.(string)
	// userDescLevel is the schema descriptor for level field.
	userDescLevel := userFields[7].Descriptor()
	// user.DefaultLevel holds the default value on creation for the level field.
	user.DefaultLevel = userDescLevel.Default.(uint8)
	// userDescGender is the schema descriptor for gender field.
	userDescGender := userFields[8].Descriptor()
	// user.DefaultGender holds the default value on creation for the gender field.
	user.DefaultGender = userDescGender.Default.(int8)
	// userDescBio is the schema descriptor for bio field.
	userDescBio := userFields[10].Descriptor()
	// user.DefaultBio holds the default value on creation for the bio field.
	user.DefaultBio = userDescBio.Default.(string)
	// userDescMoney is the schema descriptor for money field.
	userDescMoney := userFields[11].Descriptor()
	// user.DefaultMoney holds the default value on creation for the money field.
	user.DefaultMoney = userDescMoney.Default.(float64)
	// userDescScore is the schema descriptor for score field.
	userDescScore := userFields[12].Descriptor()
	// user.DefaultScore holds the default value on creation for the score field.
	user.DefaultScore = userDescScore.Default.(int)
	// userDescSuccessions is the schema descriptor for successions field.
	userDescSuccessions := userFields[13].Descriptor()
	// user.DefaultSuccessions holds the default value on creation for the successions field.
	user.DefaultSuccessions = userDescSuccessions.Default.(uint32)
	// userDescMaxsuccessions is the schema descriptor for maxsuccessions field.
	userDescMaxsuccessions := userFields[14].Descriptor()
	// user.DefaultMaxsuccessions holds the default value on creation for the maxsuccessions field.
	user.DefaultMaxsuccessions = userDescMaxsuccessions.Default.(uint32)
	// userDescPrevtime is the schema descriptor for prevtime field.
	userDescPrevtime := userFields[15].Descriptor()
	// user.DefaultPrevtime holds the default value on creation for the prevtime field.
	user.DefaultPrevtime = userDescPrevtime.Default.(int64)
	// userDescLogintime is the schema descriptor for logintime field.
	userDescLogintime := userFields[16].Descriptor()
	// user.DefaultLogintime holds the default value on creation for the logintime field.
	user.DefaultLogintime = userDescLogintime.Default.(int64)
	// userDescLoginip is the schema descriptor for loginip field.
	userDescLoginip := userFields[17].Descriptor()
	// user.DefaultLoginip holds the default value on creation for the loginip field.
	user.DefaultLoginip = userDescLoginip.Default.(string)
	// userDescLoginfailure is the schema descriptor for loginfailure field.
	userDescLoginfailure := userFields[18].Descriptor()
	// user.DefaultLoginfailure holds the default value on creation for the loginfailure field.
	user.DefaultLoginfailure = userDescLoginfailure.Default.(uint8)
	// userDescJoinip is the schema descriptor for joinip field.
	userDescJoinip := userFields[20].Descriptor()
	// user.DefaultJoinip holds the default value on creation for the joinip field.
	user.DefaultJoinip = userDescJoinip.Default.(string)
	// userDescToken is the schema descriptor for token field.
	userDescToken := userFields[24].Descriptor()
	// user.DefaultToken holds the default value on creation for the token field.
	user.DefaultToken = userDescToken.Default.(string)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[25].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescVerification is the schema descriptor for verification field.
	userDescVerification := userFields[26].Descriptor()
	// user.DefaultVerification holds the default value on creation for the verification field.
	user.DefaultVerification = userDescVerification.Default.(string)
	voucherFields := schema.Voucher{}.Fields()
	_ = voucherFields
	// voucherDescVoucherNo is the schema descriptor for voucher_no field.
	voucherDescVoucherNo := voucherFields[2].Descriptor()
	// voucher.VoucherNoValidator is a validator for the "voucher_no" field. It is called by the builders before save.
	voucher.VoucherNoValidator = voucherDescVoucherNo.Validators[0].(func(string) error)
	// voucherDescStatus is the schema descriptor for status field.
	voucherDescStatus := voucherFields[3].Descriptor()
	// voucher.DefaultStatus holds the default value on creation for the status field.
	voucher.DefaultStatus = voucherDescStatus.Default.(string)
}
