// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitee.com/meinongyihe/travel-rpc/ent/voucher"
)

// VoucherCreate is the builder for creating a Voucher entity.
type VoucherCreate struct {
	config
	mutation *VoucherMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *VoucherCreate) SetTenantID(v int64) *VoucherCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *VoucherCreate) SetOrderID(v int64) *VoucherCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetVoucherNo sets the "voucher_no" field.
func (_c *VoucherCreate) SetVoucherNo(v string) *VoucherCreate {
	_c.mutation.SetVoucherNo(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *VoucherCreate) SetStatus(v string) *VoucherCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VoucherCreate) SetNillableStatus(v *string) *VoucherCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRedeemedAt sets the "redeemed_at" field.
func (_c *VoucherCreate) SetRedeemedAt(v string) *VoucherCreate {
	_c.mutation.SetRedeemedAt(v)
	return _c
}

// SetNillableRedeemedAt sets the "redeemed_at" field if the given value is not nil.
func (_c *VoucherCreate) SetNillableRedeemedAt(v *string) *VoucherCreate {
	if v != nil {
		_c.SetRedeemedAt(*v)
	}
	return _c
}

// Mutation returns the VoucherMutation object of the builder.
func (_c *VoucherCreate) Mutation() *VoucherMutation {
	return _c.mutation
}

// Save creates the Voucher in the database.
func (_c *VoucherCreate) Save(ctx context.Context) (*Voucher, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VoucherCreate) SaveX(ctx context.Context) *Voucher {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VoucherCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VoucherCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VoucherCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := voucher.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VoucherCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Voucher.tenant_id"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "Voucher.order_id"`)}
	}
	if _, ok := _c.mutation.VoucherNo(); !ok {
		return &ValidationError{Name: "voucher_no", err: errors.New(`ent: missing required field "Voucher.voucher_no"`)}
	}
	if v, ok := _c.mutation.VoucherNo(); ok {
		if err := voucher.VoucherNoValidator(v); err != nil {
			return &ValidationError{Name: "voucher_no", err: fmt.Errorf(`ent: validator failed for field "Voucher.voucher_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Voucher.status"`)}
	}
	return nil
}

func (_c *VoucherCreate) sqlSave(ctx context.Context) (*Voucher, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VoucherCreate) createSpec() (*Voucher, *sqlgraph.CreateSpec) {
	var (
		_node = &Voucher{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(voucher.Table, sqlgraph.NewFieldSpec(voucher.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(voucher.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(voucher.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.VoucherNo(); ok {
		_spec.SetField(voucher.FieldVoucherNo, field.TypeString, value)
		_node.VoucherNo = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(voucher.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RedeemedAt(); ok {
		_spec.SetField(voucher.FieldRedeemedAt, field.TypeString, value)
		_node.RedeemedAt = value
	}
	return _node, _spec
}

// VoucherCreateBulk is the builder for creating many Voucher entities in bulk.
type VoucherCreateBulk struct {
	config
	err      error
	builders []*VoucherCreate
}

// Save creates the Voucher entities in the database.
func (_c *VoucherCreateBulk) Save(ctx context.Context) ([]*Voucher, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Voucher, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VoucherMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VoucherCreateBulk) SaveX(ctx context.Context) []*Voucher {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VoucherCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VoucherCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
