// Code generated by ent, DO NOT EDIT.

package producttranslation

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the producttranslation type in the database.
	Label = "product_translation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldLocale holds the string denoting the locale field in the database.
	FieldLocale = "locale"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldHighlights holds the string denoting the highlights field in the database.
	FieldHighlights = "highlights"
	// FieldRichContent holds the string denoting the rich_content field in the database.
	FieldRichContent = "rich_content"
	// FieldBookingNotice holds the string denoting the booking_notice field in the database.
	FieldBookingNotice = "booking_notice"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the producttranslation in the database.
	Table = "product_translations"
)

// Columns holds all SQL columns for producttranslation fields.
var Columns = []string{
	FieldID,
	FieldProductID,
	FieldLocale,
	FieldTitle,
	FieldDescription,
	FieldHighlights,
	FieldRichContent,
	FieldBookingNotice,
	FieldSource,
	FieldStatus,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LocaleValidator is a validator for the "locale" field. It is called by the builders before save.
	LocaleValidator func(string) error
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt int64
)

// OrderOption defines the ordering options for the ProductTranslation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByLocale orders the results by the locale field.
func ByLocale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocale, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByHighlights orders the results by the highlights field.
func ByHighlights(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHighlights, opts...).ToFunc()
}

// ByRichContent orders the results by the rich_content field.
func ByRichContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRichContent, opts...).ToFunc()
}

// ByBookingNotice orders the results by the booking_notice field.
func ByBookingNotice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBookingNotice, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
