// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldSalt holds the string denoting the salt field in the database.
	FieldSalt = "salt"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldMobile holds the string denoting the mobile field in the database.
	FieldMobile = "mobile"
	// FieldAvatar holds the string denoting the avatar field in the database.
	FieldAvatar = "avatar"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldBirthday holds the string denoting the birthday field in the database.
	FieldBirthday = "birthday"
	// FieldBio holds the string denoting the bio field in the database.
	FieldBio = "bio"
	// FieldMoney holds the string denoting the money field in the database.
	FieldMoney = "money"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldSuccessions holds the string denoting the successions field in the database.
	FieldSuccessions = "successions"
	// FieldMaxsuccessions holds the string denoting the maxsuccessions field in the database.
	FieldMaxsuccessions = "maxsuccessions"
	// FieldPrevtime holds the string denoting the prevtime field in the database.
	FieldPrevtime = "prevtime"
	// FieldLogintime holds the string denoting the logintime field in the database.
	FieldLogintime = "logintime"
	// FieldLoginip holds the string denoting the loginip field in the database.
	FieldLoginip = "loginip"
	// FieldLoginfailure holds the string denoting the loginfailure field in the database.
	FieldLoginfailure = "loginfailure"
	// FieldLoginfailuretime holds the string denoting the loginfailuretime field in the database.
	FieldLoginfailuretime = "loginfailuretime"
	// FieldJoinip holds the string denoting the joinip field in the database.
	FieldJoinip = "joinip"
	// FieldJointime holds the string denoting the jointime field in the database.
	FieldJointime = "jointime"
	// FieldCreatetime holds the string denoting the createtime field in the database.
	FieldCreatetime = "createtime"
	// FieldUpdatetime holds the string denoting the updatetime field in the database.
	FieldUpdatetime = "updatetime"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldVerification holds the string denoting the verification field in the database.
	FieldVerification = "verification"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldNickname,
	FieldPassword,
	FieldSalt,
	FieldEmail,
	FieldMobile,
	FieldAvatar,
	FieldLevel,
	FieldGender,
	FieldBirthday,
	FieldBio,
	FieldMoney,
	FieldScore,
	FieldSuccessions,
	FieldMaxsuccessions,
	FieldPrevtime,
	FieldLogintime,
	FieldLoginip,
	FieldLoginfailure,
	FieldLoginfailuretime,
	FieldJoinip,
	FieldJointime,
	FieldCreatetime,
	FieldUpdatetime,
	FieldToken,
	FieldStatus,
	FieldVerification,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// DefaultNickname holds the default value on creation for the "nickname" field.
	DefaultNickname string
	// DefaultPassword holds the default value on creation for the "password" field.
	DefaultPassword string
	// DefaultSalt holds the default value on creation for the "salt" field.
	DefaultSalt string
	// DefaultEmail holds the default value on creation for the "email" field.
	DefaultEmail string
	// DefaultMobile holds the default value on creation for the "mobile" field.
	DefaultMobile string
	// DefaultAvatar holds the default value on creation for the "avatar" field.
	DefaultAvatar string
	// DefaultLevel holds the default value on creation for the "level" field.
	DefaultLevel uint8
	// DefaultGender holds the default value on creation for the "gender" field.
	DefaultGender int8
	// DefaultBio holds the default value on creation for the "bio" field.
	DefaultBio string
	// DefaultMoney holds the default value on creation for the "money" field.
	DefaultMoney float64
	// DefaultScore holds the default value on creation for the "score" field.
	DefaultScore int
	// DefaultSuccessions holds the default value on creation for the "successions" field.
	DefaultSuccessions uint32
	// DefaultMaxsuccessions holds the default value on creation for the "maxsuccessions" field.
	DefaultMaxsuccessions uint32
	// DefaultPrevtime holds the default value on creation for the "prevtime" field.
	DefaultPrevtime int64
	// DefaultLogintime holds the default value on creation for the "logintime" field.
	DefaultLogintime int64
	// DefaultLoginip holds the default value on creation for the "loginip" field.
	DefaultLoginip string
	// DefaultLoginfailure holds the default value on creation for the "loginfailure" field.
	DefaultLoginfailure uint8
	// DefaultJoinip holds the default value on creation for the "joinip" field.
	DefaultJoinip string
	// DefaultToken holds the default value on creation for the "token" field.
	DefaultToken string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultVerification holds the default value on creation for the "verification" field.
	DefaultVerification string
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// BySalt orders the results by the salt field.
func BySalt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSalt, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByMobile orders the results by the mobile field.
func ByMobile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMobile, opts...).ToFunc()
}

// ByAvatar orders the results by the avatar field.
func ByAvatar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatar, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByGender orders the results by the gender field.
func ByGender(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGender, opts...).ToFunc()
}

// ByBirthday orders the results by the birthday field.
func ByBirthday(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBirthday, opts...).ToFunc()
}

// ByBio orders the results by the bio field.
func ByBio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBio, opts...).ToFunc()
}

// ByMoney orders the results by the money field.
func ByMoney(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMoney, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// BySuccessions orders the results by the successions field.
func BySuccessions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessions, opts...).ToFunc()
}

// ByMaxsuccessions orders the results by the maxsuccessions field.
func ByMaxsuccessions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxsuccessions, opts...).ToFunc()
}

// ByPrevtime orders the results by the prevtime field.
func ByPrevtime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrevtime, opts...).ToFunc()
}

// ByLogintime orders the results by the logintime field.
func ByLogintime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogintime, opts...).ToFunc()
}

// ByLoginip orders the results by the loginip field.
func ByLoginip(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginip, opts...).ToFunc()
}

// ByLoginfailure orders the results by the loginfailure field.
func ByLoginfailure(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginfailure, opts...).ToFunc()
}

// ByLoginfailuretime orders the results by the loginfailuretime field.
func ByLoginfailuretime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginfailuretime, opts...).ToFunc()
}

// ByJoinip orders the results by the joinip field.
func ByJoinip(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinip, opts...).ToFunc()
}

// ByJointime orders the results by the jointime field.
func ByJointime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJointime, opts...).ToFunc()
}

// ByCreatetime orders the results by the createtime field.
func ByCreatetime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatetime, opts...).ToFunc()
}

// ByUpdatetime orders the results by the updatetime field.
func ByUpdatetime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatetime, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByVerification orders the results by the verification field.
func ByVerification(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerification, opts...).ToFunc()
}
