// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"gitee.com/meinongyihe/travel-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// Nickname applies equality check predicate on the "nickname" field. It's identical to NicknameEQ.
func Nickname(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldNickname, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPassword, v))
}

// Salt applies equality check predicate on the "salt" field. It's identical to SaltEQ.
func Salt(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSalt, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// Mobile applies equality check predicate on the "mobile" field. It's identical to MobileEQ.
func Mobile(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMobile, v))
}

// Avatar applies equality check predicate on the "avatar" field. It's identical to AvatarEQ.
func Avatar(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatar, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v uint8) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLevel, v))
}

// Gender applies equality check predicate on the "gender" field. It's identical to GenderEQ.
func Gender(v int8) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGender, v))
}

// Birthday applies equality check predicate on the "birthday" field. It's identical to BirthdayEQ.
func Birthday(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBirthday, v))
}

// Bio applies equality check predicate on the "bio" field. It's identical to BioEQ.
func Bio(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBio, v))
}

// Money applies equality check predicate on the "money" field. It's identical to MoneyEQ.
func Money(v float64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMoney, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldScore, v))
}

// Successions applies equality check predicate on the "successions" field. It's identical to SuccessionsEQ.
func Successions(v uint32) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSuccessions, v))
}

// Maxsuccessions applies equality check predicate on the "maxsuccessions" field. It's identical to MaxsuccessionsEQ.
func Maxsuccessions(v uint32) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMaxsuccessions, v))
}

// Prevtime applies equality check predicate on the "prevtime" field. It's identical to PrevtimeEQ.
func Prevtime(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPrevtime, v))
}

// Logintime applies equality check predicate on the "logintime" field. It's identical to LogintimeEQ.
func Logintime(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLogintime, v))
}

// Loginip applies equality check predicate on the "loginip" field. It's identical to LoginipEQ.
func Loginip(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLoginip, v))
}

// Loginfailure applies equality check predicate on the "loginfailure" field. It's identical to LoginfailureEQ.
func Loginfailure(v uint8) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLoginfailure, v))
}

// Loginfailuretime applies equality check predicate on the "loginfailuretime" field. It's identical to LoginfailuretimeEQ.
func Loginfailuretime(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLoginfailuretime, v))
}

// Joinip applies equality check predicate on the "joinip" field. It's identical to JoinipEQ.
func Joinip(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldJoinip, v))
}

// Jointime applies equality check predicate on the "jointime" field. It's identical to JointimeEQ.
func Jointime(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldJointime, v))
}

// Createtime applies equality check predicate on the "createtime" field. It's identical to CreatetimeEQ.
func Createtime(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatetime, v))
}

// Updatetime applies equality check predicate on the "updatetime" field. It's identical to UpdatetimeEQ.
func Updatetime(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatetime, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldToken, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldStatus, v))
}

// Verification applies equality check predicate on the "verification" field. It's identical to VerificationEQ.
func Verification(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldVerification, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUsername, v))
}

// NicknameEQ applies the EQ predicate on the "nickname" field.
func NicknameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldNickname, v))
}

// NicknameNEQ applies the NEQ predicate on the "nickname" field.
func NicknameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldNickname, v))
}

// NicknameIn applies the In predicate on the "nickname" field.
func NicknameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldNickname, vs...))
}

// NicknameNotIn applies the NotIn predicate on the "nickname" field.
func NicknameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldNickname, vs...))
}

// NicknameGT applies the GT predicate on the "nickname" field.
func NicknameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldNickname, v))
}

// NicknameGTE applies the GTE predicate on the "nickname" field.
func NicknameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldNickname, v))
}

// NicknameLT applies the LT predicate on the "nickname" field.
func NicknameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldNickname, v))
}

// NicknameLTE applies the LTE predicate on the "nickname" field.
func NicknameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldNickname, v))
}

// NicknameContains applies the Contains predicate on the "nickname" field.
func NicknameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldNickname, v))
}

// NicknameHasPrefix applies the HasPrefix predicate on the "nickname" field.
func NicknameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldNickname, v))
}

// NicknameHasSuffix applies the HasSuffix predicate on the "nickname" field.
func NicknameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldNickname, v))
}

// NicknameEqualFold applies the EqualFold predicate on the "nickname" field.
func NicknameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldNickname, v))
}

// NicknameContainsFold applies the ContainsFold predicate on the "nickname" field.
func NicknameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldNickname, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPassword, v))
}

// SaltEQ applies the EQ predicate on the "salt" field.
func SaltEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSalt, v))
}

// SaltNEQ applies the NEQ predicate on the "salt" field.
func SaltNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSalt, v))
}

// SaltIn applies the In predicate on the "salt" field.
func SaltIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldSalt, vs...))
}

// SaltNotIn applies the NotIn predicate on the "salt" field.
func SaltNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSalt, vs...))
}

// SaltGT applies the GT predicate on the "salt" field.
func SaltGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldSalt, v))
}

// SaltGTE applies the GTE predicate on the "salt" field.
func SaltGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSalt, v))
}

// SaltLT applies the LT predicate on the "salt" field.
func SaltLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldSalt, v))
}

// SaltLTE applies the LTE predicate on the "salt" field.
func SaltLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSalt, v))
}

// SaltContains applies the Contains predicate on the "salt" field.
func SaltContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldSalt, v))
}

// SaltHasPrefix applies the HasPrefix predicate on the "salt" field.
func SaltHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldSalt, v))
}

// SaltHasSuffix applies the HasSuffix predicate on the "salt" field.
func SaltHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldSalt, v))
}

// SaltEqualFold applies the EqualFold predicate on the "salt" field.
func SaltEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldSalt, v))
}

// SaltContainsFold applies the ContainsFold predicate on the "salt" field.
func SaltContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldSalt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// MobileEQ applies the EQ predicate on the "mobile" field.
func MobileEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMobile, v))
}

// MobileNEQ applies the NEQ predicate on the "mobile" field.
func MobileNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldMobile, v))
}

// MobileIn applies the In predicate on the "mobile" field.
func MobileIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldMobile, vs...))
}

// MobileNotIn applies the NotIn predicate on the "mobile" field.
func MobileNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldMobile, vs...))
}

// MobileGT applies the GT predicate on the "mobile" field.
func MobileGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldMobile, v))
}

// MobileGTE applies the GTE predicate on the "mobile" field.
func MobileGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldMobile, v))
}

// MobileLT applies the LT predicate on the "mobile" field.
func MobileLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldMobile, v))
}

// MobileLTE applies the LTE predicate on the "mobile" field.
func MobileLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldMobile, v))
}

// MobileContains applies the Contains predicate on the "mobile" field.
func MobileContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldMobile, v))
}

// MobileHasPrefix applies the HasPrefix predicate on the "mobile" field.
func MobileHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldMobile, v))
}

// MobileHasSuffix applies the HasSuffix predicate on the "mobile" field.
func MobileHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldMobile, v))
}

// MobileEqualFold applies the EqualFold predicate on the "mobile" field.
func MobileEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldMobile, v))
}

// MobileContainsFold applies the ContainsFold predicate on the "mobile" field.
func MobileContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldMobile, v))
}

// AvatarEQ applies the EQ predicate on the "avatar" field.
func AvatarEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatar, v))
}

// AvatarNEQ applies the NEQ predicate on the "avatar" field.
func AvatarNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatar, v))
}

// AvatarIn applies the In predicate on the "avatar" field.
func AvatarIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatar, vs...))
}

// AvatarNotIn applies the NotIn predicate on the "avatar" field.
func AvatarNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatar, vs...))
}

// AvatarGT applies the GT predicate on the "avatar" field.
func AvatarGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatar, v))
}

// AvatarGTE applies the GTE predicate on the "avatar" field.
func AvatarGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatar, v))
}

// AvatarLT applies the LT predicate on the "avatar" field.
func AvatarLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatar, v))
}

// AvatarLTE applies the LTE predicate on the "avatar" field.
func AvatarLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatar, v))
}

// AvatarContains applies the Contains predicate on the "avatar" field.
func AvatarContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatar, v))
}

// AvatarHasPrefix applies the HasPrefix predicate on the "avatar" field.
func AvatarHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatar, v))
}

// AvatarHasSuffix applies the HasSuffix predicate on the "avatar" field.
func AvatarHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatar, v))
}

// AvatarEqualFold applies the EqualFold predicate on the "avatar" field.
func AvatarEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatar, v))
}

// AvatarContainsFold applies the ContainsFold predicate on the "avatar" field.
func AvatarContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatar, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v uint8) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v uint8) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...uint8) predicate.User {
	return predicate.User(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...uint8) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v uint8) predicate.User {
	return predicate.User(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v uint8) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v uint8) predicate.User {
	return predicate.User(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v uint8) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLevel, v))
}

// GenderEQ applies the EQ predicate on the "gender" field.
func GenderEQ(v int8) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGender, v))
}

// GenderNEQ applies the NEQ predicate on the "gender" field.
func GenderNEQ(v int8) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldGender, v))
}

// GenderIn applies the In predicate on the "gender" field.
func GenderIn(vs ...int8) predicate.User {
	return predicate.User(sql.FieldIn(FieldGender, vs...))
}

// GenderNotIn applies the NotIn predicate on the "gender" field.
func GenderNotIn(vs ...int8) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldGender, vs...))
}

// GenderGT applies the GT predicate on the "gender" field.
func GenderGT(v int8) predicate.User {
	return predicate.User(sql.FieldGT(FieldGender, v))
}

// GenderGTE applies the GTE predicate on the "gender" field.
func GenderGTE(v int8) predicate.User {
	return predicate.User(sql.FieldGTE(FieldGender, v))
}

// GenderLT applies the LT predicate on the "gender" field.
func GenderLT(v int8) predicate.User {
	return predicate.User(sql.FieldLT(FieldGender, v))
}

// GenderLTE applies the LTE predicate on the "gender" field.
func GenderLTE(v int8) predicate.User {
	return predicate.User(sql.FieldLTE(FieldGender, v))
}

// BirthdayEQ applies the EQ predicate on the "birthday" field.
func BirthdayEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBirthday, v))
}

// BirthdayNEQ applies the NEQ predicate on the "birthday" field.
func BirthdayNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldBirthday, v))
}

// BirthdayIn applies the In predicate on the "birthday" field.
func BirthdayIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldBirthday, vs...))
}

// BirthdayNotIn applies the NotIn predicate on the "birthday" field.
func BirthdayNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldBirthday, vs...))
}

// BirthdayGT applies the GT predicate on the "birthday" field.
func BirthdayGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldBirthday, v))
}

// BirthdayGTE applies the GTE predicate on the "birthday" field.
func BirthdayGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldBirthday, v))
}

// BirthdayLT applies the LT predicate on the "birthday" field.
func BirthdayLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldBirthday, v))
}

// BirthdayLTE applies the LTE predicate on the "birthday" field.
func BirthdayLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldBirthday, v))
}

// BirthdayContains applies the Contains predicate on the "birthday" field.
func BirthdayContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldBirthday, v))
}

// BirthdayHasPrefix applies the HasPrefix predicate on the "birthday" field.
func BirthdayHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldBirthday, v))
}

// BirthdayHasSuffix applies the HasSuffix predicate on the "birthday" field.
func BirthdayHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldBirthday, v))
}

// BirthdayIsNil applies the IsNil predicate on the "birthday" field.
func BirthdayIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldBirthday))
}

// BirthdayNotNil applies the NotNil predicate on the "birthday" field.
func BirthdayNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldBirthday))
}

// BirthdayEqualFold applies the EqualFold predicate on the "birthday" field.
func BirthdayEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldBirthday, v))
}

// BirthdayContainsFold applies the ContainsFold predicate on the "birthday" field.
func BirthdayContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldBirthday, v))
}

// BioEQ applies the EQ predicate on the "bio" field.
func BioEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBio, v))
}

// BioNEQ applies the NEQ predicate on the "bio" field.
func BioNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldBio, v))
}

// BioIn applies the In predicate on the "bio" field.
func BioIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldBio, vs...))
}

// BioNotIn applies the NotIn predicate on the "bio" field.
func BioNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldBio, vs...))
}

// BioGT applies the GT predicate on the "bio" field.
func BioGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldBio, v))
}

// BioGTE applies the GTE predicate on the "bio" field.
func BioGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldBio, v))
}

// BioLT applies the LT predicate on the "bio" field.
func BioLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldBio, v))
}

// BioLTE applies the LTE predicate on the "bio" field.
func BioLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldBio, v))
}

// BioContains applies the Contains predicate on the "bio" field.
func BioContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldBio, v))
}

// BioHasPrefix applies the HasPrefix predicate on the "bio" field.
func BioHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldBio, v))
}

// BioHasSuffix applies the HasSuffix predicate on the "bio" field.
func BioHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldBio, v))
}

// BioEqualFold applies the EqualFold predicate on the "bio" field.
func BioEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldBio, v))
}

// BioContainsFold applies the ContainsFold predicate on the "bio" field.
func BioContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldBio, v))
}

// MoneyEQ applies the EQ predicate on the "money" field.
func MoneyEQ(v float64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMoney, v))
}

// MoneyNEQ applies the NEQ predicate on the "money" field.
func MoneyNEQ(v float64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldMoney, v))
}

// MoneyIn applies the In predicate on the "money" field.
func MoneyIn(vs ...float64) predicate.User {
	return predicate.User(sql.FieldIn(FieldMoney, vs...))
}

// MoneyNotIn applies the NotIn predicate on the "money" field.
func MoneyNotIn(vs ...float64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldMoney, vs...))
}

// MoneyGT applies the GT predicate on the "money" field.
func MoneyGT(v float64) predicate.User {
	return predicate.User(sql.FieldGT(FieldMoney, v))
}

// MoneyGTE applies the GTE predicate on the "money" field.
func MoneyGTE(v float64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldMoney, v))
}

// MoneyLT applies the LT predicate on the "money" field.
func MoneyLT(v float64) predicate.User {
	return predicate.User(sql.FieldLT(FieldMoney, v))
}

// MoneyLTE applies the LTE predicate on the "money" field.
func MoneyLTE(v float64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldMoney, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldScore, v))
}

// SuccessionsEQ applies the EQ predicate on the "successions" field.
func SuccessionsEQ(v uint32) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSuccessions, v))
}

// SuccessionsNEQ applies the NEQ predicate on the "successions" field.
func SuccessionsNEQ(v uint32) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSuccessions, v))
}

// SuccessionsIn applies the In predicate on the "successions" field.
func SuccessionsIn(vs ...uint32) predicate.User {
	return predicate.User(sql.FieldIn(FieldSuccessions, vs...))
}

// SuccessionsNotIn applies the NotIn predicate on the "successions" field.
func SuccessionsNotIn(vs ...uint32) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSuccessions, vs...))
}

// SuccessionsGT applies the GT predicate on the "successions" field.
func SuccessionsGT(v uint32) predicate.User {
	return predicate.User(sql.FieldGT(FieldSuccessions, v))
}

// SuccessionsGTE applies the GTE predicate on the "successions" field.
func SuccessionsGTE(v uint32) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSuccessions, v))
}

// SuccessionsLT applies the LT predicate on the "successions" field.
func SuccessionsLT(v uint32) predicate.User {
	return predicate.User(sql.FieldLT(FieldSuccessions, v))
}

// SuccessionsLTE applies the LTE predicate on the "successions" field.
func SuccessionsLTE(v uint32) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSuccessions, v))
}

// MaxsuccessionsEQ applies the EQ predicate on the "maxsuccessions" field.
func MaxsuccessionsEQ(v uint32) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMaxsuccessions, v))
}

// MaxsuccessionsNEQ applies the NEQ predicate on the "maxsuccessions" field.
func MaxsuccessionsNEQ(v uint32) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldMaxsuccessions, v))
}

// MaxsuccessionsIn applies the In predicate on the "maxsuccessions" field.
func MaxsuccessionsIn(vs ...uint32) predicate.User {
	return predicate.User(sql.FieldIn(FieldMaxsuccessions, vs...))
}

// MaxsuccessionsNotIn applies the NotIn predicate on the "maxsuccessions" field.
func MaxsuccessionsNotIn(vs ...uint32) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldMaxsuccessions, vs...))
}

// MaxsuccessionsGT applies the GT predicate on the "maxsuccessions" field.
func MaxsuccessionsGT(v uint32) predicate.User {
	return predicate.User(sql.FieldGT(FieldMaxsuccessions, v))
}

// MaxsuccessionsGTE applies the GTE predicate on the "maxsuccessions" field.
func MaxsuccessionsGTE(v uint32) predicate.User {
	return predicate.User(sql.FieldGTE(FieldMaxsuccessions, v))
}

// MaxsuccessionsLT applies the LT predicate on the "maxsuccessions" field.
func MaxsuccessionsLT(v uint32) predicate.User {
	return predicate.User(sql.FieldLT(FieldMaxsuccessions, v))
}

// MaxsuccessionsLTE applies the LTE predicate on the "maxsuccessions" field.
func MaxsuccessionsLTE(v uint32) predicate.User {
	return predicate.User(sql.FieldLTE(FieldMaxsuccessions, v))
}

// PrevtimeEQ applies the EQ predicate on the "prevtime" field.
func PrevtimeEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPrevtime, v))
}

// PrevtimeNEQ applies the NEQ predicate on the "prevtime" field.
func PrevtimeNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPrevtime, v))
}

// PrevtimeIn applies the In predicate on the "prevtime" field.
func PrevtimeIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldPrevtime, vs...))
}

// PrevtimeNotIn applies the NotIn predicate on the "prevtime" field.
func PrevtimeNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPrevtime, vs...))
}

// PrevtimeGT applies the GT predicate on the "prevtime" field.
func PrevtimeGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldPrevtime, v))
}

// PrevtimeGTE applies the GTE predicate on the "prevtime" field.
func PrevtimeGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPrevtime, v))
}

// PrevtimeLT applies the LT predicate on the "prevtime" field.
func PrevtimeLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldPrevtime, v))
}

// PrevtimeLTE applies the LTE predicate on the "prevtime" field.
func PrevtimeLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPrevtime, v))
}

// LogintimeEQ applies the EQ predicate on the "logintime" field.
func LogintimeEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLogintime, v))
}

// LogintimeNEQ applies the NEQ predicate on the "logintime" field.
func LogintimeNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLogintime, v))
}

// LogintimeIn applies the In predicate on the "logintime" field.
func LogintimeIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldLogintime, vs...))
}

// LogintimeNotIn applies the NotIn predicate on the "logintime" field.
func LogintimeNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLogintime, vs...))
}

// LogintimeGT applies the GT predicate on the "logintime" field.
func LogintimeGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldLogintime, v))
}

// LogintimeGTE applies the GTE predicate on the "logintime" field.
func LogintimeGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLogintime, v))
}

// LogintimeLT applies the LT predicate on the "logintime" field.
func LogintimeLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldLogintime, v))
}

// LogintimeLTE applies the LTE predicate on the "logintime" field.
func LogintimeLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLogintime, v))
}

// LoginipEQ applies the EQ predicate on the "loginip" field.
func LoginipEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLoginip, v))
}

// LoginipNEQ applies the NEQ predicate on the "loginip" field.
func LoginipNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLoginip, v))
}

// LoginipIn applies the In predicate on the "loginip" field.
func LoginipIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldLoginip, vs...))
}

// LoginipNotIn applies the NotIn predicate on the "loginip" field.
func LoginipNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLoginip, vs...))
}

// LoginipGT applies the GT predicate on the "loginip" field.
func LoginipGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldLoginip, v))
}

// LoginipGTE applies the GTE predicate on the "loginip" field.
func LoginipGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLoginip, v))
}

// LoginipLT applies the LT predicate on the "loginip" field.
func LoginipLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldLoginip, v))
}

// LoginipLTE applies the LTE predicate on the "loginip" field.
func LoginipLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLoginip, v))
}

// LoginipContains applies the Contains predicate on the "loginip" field.
func LoginipContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldLoginip, v))
}

// LoginipHasPrefix applies the HasPrefix predicate on the "loginip" field.
func LoginipHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldLoginip, v))
}

// LoginipHasSuffix applies the HasSuffix predicate on the "loginip" field.
func LoginipHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldLoginip, v))
}

// LoginipEqualFold applies the EqualFold predicate on the "loginip" field.
func LoginipEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldLoginip, v))
}

// LoginipContainsFold applies the ContainsFold predicate on the "loginip" field.
func LoginipContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldLoginip, v))
}

// LoginfailureEQ applies the EQ predicate on the "loginfailure" field.
func LoginfailureEQ(v uint8) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLoginfailure, v))
}

// LoginfailureNEQ applies the NEQ predicate on the "loginfailure" field.
func LoginfailureNEQ(v uint8) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLoginfailure, v))
}

// LoginfailureIn applies the In predicate on the "loginfailure" field.
func LoginfailureIn(vs ...uint8) predicate.User {
	return predicate.User(sql.FieldIn(FieldLoginfailure, vs...))
}

// LoginfailureNotIn applies the NotIn predicate on the "loginfailure" field.
func LoginfailureNotIn(vs ...uint8) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLoginfailure, vs...))
}

// LoginfailureGT applies the GT predicate on the "loginfailure" field.
func LoginfailureGT(v uint8) predicate.User {
	return predicate.User(sql.FieldGT(FieldLoginfailure, v))
}

// LoginfailureGTE applies the GTE predicate on the "loginfailure" field.
func LoginfailureGTE(v uint8) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLoginfailure, v))
}

// LoginfailureLT applies the LT predicate on the "loginfailure" field.
func LoginfailureLT(v uint8) predicate.User {
	return predicate.User(sql.FieldLT(FieldLoginfailure, v))
}

// LoginfailureLTE applies the LTE predicate on the "loginfailure" field.
func LoginfailureLTE(v uint8) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLoginfailure, v))
}

// LoginfailuretimeEQ applies the EQ predicate on the "loginfailuretime" field.
func LoginfailuretimeEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLoginfailuretime, v))
}

// LoginfailuretimeNEQ applies the NEQ predicate on the "loginfailuretime" field.
func LoginfailuretimeNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLoginfailuretime, v))
}

// LoginfailuretimeIn applies the In predicate on the "loginfailuretime" field.
func LoginfailuretimeIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldLoginfailuretime, vs...))
}

// LoginfailuretimeNotIn applies the NotIn predicate on the "loginfailuretime" field.
func LoginfailuretimeNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLoginfailuretime, vs...))
}

// LoginfailuretimeGT applies the GT predicate on the "loginfailuretime" field.
func LoginfailuretimeGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldLoginfailuretime, v))
}

// LoginfailuretimeGTE applies the GTE predicate on the "loginfailuretime" field.
func LoginfailuretimeGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLoginfailuretime, v))
}

// LoginfailuretimeLT applies the LT predicate on the "loginfailuretime" field.
func LoginfailuretimeLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldLoginfailuretime, v))
}

// LoginfailuretimeLTE applies the LTE predicate on the "loginfailuretime" field.
func LoginfailuretimeLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLoginfailuretime, v))
}

// LoginfailuretimeIsNil applies the IsNil predicate on the "loginfailuretime" field.
func LoginfailuretimeIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldLoginfailuretime))
}

// LoginfailuretimeNotNil applies the NotNil predicate on the "loginfailuretime" field.
func LoginfailuretimeNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldLoginfailuretime))
}

// JoinipEQ applies the EQ predicate on the "joinip" field.
func JoinipEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldJoinip, v))
}

// JoinipNEQ applies the NEQ predicate on the "joinip" field.
func JoinipNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldJoinip, v))
}

// JoinipIn applies the In predicate on the "joinip" field.
func JoinipIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldJoinip, vs...))
}

// JoinipNotIn applies the NotIn predicate on the "joinip" field.
func JoinipNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldJoinip, vs...))
}

// JoinipGT applies the GT predicate on the "joinip" field.
func JoinipGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldJoinip, v))
}

// JoinipGTE applies the GTE predicate on the "joinip" field.
func JoinipGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldJoinip, v))
}

// JoinipLT applies the LT predicate on the "joinip" field.
func JoinipLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldJoinip, v))
}

// JoinipLTE applies the LTE predicate on the "joinip" field.
func JoinipLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldJoinip, v))
}

// JoinipContains applies the Contains predicate on the "joinip" field.
func JoinipContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldJoinip, v))
}

// JoinipHasPrefix applies the HasPrefix predicate on the "joinip" field.
func JoinipHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldJoinip, v))
}

// JoinipHasSuffix applies the HasSuffix predicate on the "joinip" field.
func JoinipHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldJoinip, v))
}

// JoinipEqualFold applies the EqualFold predicate on the "joinip" field.
func JoinipEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldJoinip, v))
}

// JoinipContainsFold applies the ContainsFold predicate on the "joinip" field.
func JoinipContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldJoinip, v))
}

// JointimeEQ applies the EQ predicate on the "jointime" field.
func JointimeEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldJointime, v))
}

// JointimeNEQ applies the NEQ predicate on the "jointime" field.
func JointimeNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldJointime, v))
}

// JointimeIn applies the In predicate on the "jointime" field.
func JointimeIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldJointime, vs...))
}

// JointimeNotIn applies the NotIn predicate on the "jointime" field.
func JointimeNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldJointime, vs...))
}

// JointimeGT applies the GT predicate on the "jointime" field.
func JointimeGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldJointime, v))
}

// JointimeGTE applies the GTE predicate on the "jointime" field.
func JointimeGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldJointime, v))
}

// JointimeLT applies the LT predicate on the "jointime" field.
func JointimeLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldJointime, v))
}

// JointimeLTE applies the LTE predicate on the "jointime" field.
func JointimeLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldJointime, v))
}

// JointimeIsNil applies the IsNil predicate on the "jointime" field.
func JointimeIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldJointime))
}

// JointimeNotNil applies the NotNil predicate on the "jointime" field.
func JointimeNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldJointime))
}

// CreatetimeEQ applies the EQ predicate on the "createtime" field.
func CreatetimeEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatetime, v))
}

// CreatetimeNEQ applies the NEQ predicate on the "createtime" field.
func CreatetimeNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatetime, v))
}

// CreatetimeIn applies the In predicate on the "createtime" field.
func CreatetimeIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatetime, vs...))
}

// CreatetimeNotIn applies the NotIn predicate on the "createtime" field.
func CreatetimeNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatetime, vs...))
}

// CreatetimeGT applies the GT predicate on the "createtime" field.
func CreatetimeGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatetime, v))
}

// CreatetimeGTE applies the GTE predicate on the "createtime" field.
func CreatetimeGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatetime, v))
}

// CreatetimeLT applies the LT predicate on the "createtime" field.
func CreatetimeLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatetime, v))
}

// CreatetimeLTE applies the LTE predicate on the "createtime" field.
func CreatetimeLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatetime, v))
}

// CreatetimeIsNil applies the IsNil predicate on the "createtime" field.
func CreatetimeIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldCreatetime))
}

// CreatetimeNotNil applies the NotNil predicate on the "createtime" field.
func CreatetimeNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldCreatetime))
}

// UpdatetimeEQ applies the EQ predicate on the "updatetime" field.
func UpdatetimeEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatetime, v))
}

// UpdatetimeNEQ applies the NEQ predicate on the "updatetime" field.
func UpdatetimeNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatetime, v))
}

// UpdatetimeIn applies the In predicate on the "updatetime" field.
func UpdatetimeIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatetime, vs...))
}

// UpdatetimeNotIn applies the NotIn predicate on the "updatetime" field.
func UpdatetimeNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatetime, vs...))
}

// UpdatetimeGT applies the GT predicate on the "updatetime" field.
func UpdatetimeGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatetime, v))
}

// UpdatetimeGTE applies the GTE predicate on the "updatetime" field.
func UpdatetimeGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatetime, v))
}

// UpdatetimeLT applies the LT predicate on the "updatetime" field.
func UpdatetimeLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatetime, v))
}

// UpdatetimeLTE applies the LTE predicate on the "updatetime" field.
func UpdatetimeLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatetime, v))
}

// UpdatetimeIsNil applies the IsNil predicate on the "updatetime" field.
func UpdatetimeIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldUpdatetime))
}

// UpdatetimeNotNil applies the NotNil predicate on the "updatetime" field.
func UpdatetimeNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldUpdatetime))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldToken, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldStatus, v))
}

// VerificationEQ applies the EQ predicate on the "verification" field.
func VerificationEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldVerification, v))
}

// VerificationNEQ applies the NEQ predicate on the "verification" field.
func VerificationNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldVerification, v))
}

// VerificationIn applies the In predicate on the "verification" field.
func VerificationIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldVerification, vs...))
}

// VerificationNotIn applies the NotIn predicate on the "verification" field.
func VerificationNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldVerification, vs...))
}

// VerificationGT applies the GT predicate on the "verification" field.
func VerificationGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldVerification, v))
}

// VerificationGTE applies the GTE predicate on the "verification" field.
func VerificationGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldVerification, v))
}

// VerificationLT applies the LT predicate on the "verification" field.
func VerificationLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldVerification, v))
}

// VerificationLTE applies the LTE predicate on the "verification" field.
func VerificationLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldVerification, v))
}

// VerificationContains applies the Contains predicate on the "verification" field.
func VerificationContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldVerification, v))
}

// VerificationHasPrefix applies the HasPrefix predicate on the "verification" field.
func VerificationHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldVerification, v))
}

// VerificationHasSuffix applies the HasSuffix predicate on the "verification" field.
func VerificationHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldVerification, v))
}

// VerificationEqualFold applies the EqualFold predicate on the "verification" field.
func VerificationEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldVerification, v))
}

// VerificationContainsFold applies the ContainsFold predicate on the "verification" field.
func VerificationContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldVerification, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
