// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Inventory is the predicate function for inventory builders.
type Inventory func(*sql.Selector)

// InventoryReservation is the predicate function for inventoryreservation builders.
type InventoryReservation func(*sql.Selector)

// ItineraryStop is the predicate function for itinerarystop builders.
type ItineraryStop func(*sql.Selector)

// Merchant is the predicate function for merchant builders.
type Merchant func(*sql.Selector)

// MerchantConfig is the predicate function for merchantconfig builders.
type MerchantConfig func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderItem is the predicate function for orderitem builders.
type OrderItem func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// ProductPackage is the predicate function for productpackage builders.
type ProductPackage func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// Traveler is the predicate function for traveler builders.
type Traveler func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Voucher is the predicate function for voucher builders.
type Voucher func(*sql.Selector)
